### ISSUE TITLE
使用StorageManager.mountObb的方式加载obb无法正常拉起

### ISSUE THREAD

**Issue by lpcdma** [android-hacker/VAExposed#1002]
## 问题描述

使用一下代码加载obb文件
```
StorageManager mSM = (StorageManager) application.getApplicationContext().getSystemService(Context.STORAGE_SERVICE);
mSM.mountObb()
```

## 复现步骤

必现，错误日志
```
/system_process W/StorageManagerService: Denied attempt to mount OBB /storage/emulated/0/Android/obb/com.xxx.yyy/main.1692647.com.xxx.yyy.obb which is owned by com.xxx.yyy
/system_process W/StorageManagerService: Failed to find OBB mounted at /storage/emulated/0/Android/obb/com.xxx.yyy/main.1692647.com.xxx.yyy.obb
```

## 环境

机型：
系统版本：8.1.0 
ROM版本：MIUI
Xposed 插件以及插件版本：无
VirtualXposed版本：0.20.3

## 补充

没有权限?

想通过hook StorageManagerService.isUidOwnerOfPackageOrSystem函数来解决，不过这个类又是在system_server中加载的。
暂无其他办法了。

**Comment by remixer-dec** [comment]
I faced a similar issue using another virtualization app. To bypass this Android limitation, target obb files should be [modified](https://github.com/remixer-dec/OBBImageExtractor/blob/master/app/src/main/java/ru/remixer_dec/cache_extractor/ObbPackageInfoReplacer.java#L14) (package name in the end) and placed in the obb folder of an app that is trying to mount them.  Another solution is to modify target app's apk, calling successful onObbStateChange and replacing getMountedObbPath() requests with fixed path string which leads to folders with [extracted](https://github.com/remixer-dec/OBBImageExtractor) obb content.

**Comment by lpcdma** [comment]
> I faced a similar issue using another virtualization app. To bypass this Android limitation, target obb files should be [modified](https://github.com/remixer-dec/OBBImageExtractor/blob/master/app/src/main/java/ru/remixer_dec/cache_extractor/ObbPackageInfoReplacer.java#L14) (package name in the end) and placed in the obb folder of an app that is trying to mount them. Another solution is to modify target app's apk, calling successful onObbStateChange and replacing getMountedObbPath() requests with fixed path string which leads to folders with [extracted](https://github.com/remixer-dec/OBBImageExtractor) obb content.

thank！
