### ISSUE TITLE
launcher模块怎么引入

### ISSUE THREAD

**Issue by lishangwl** [android-hacker/VAExposed#1008]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by lishangwl** [comment]
VirtualXposed中implementation project(':launcher')，launcher模块怎么引入

**Comment by lishangwl** [comment]
> VirtualXposed中implementation project(':launcher')，launcher模块怎么引入

各位大佬

**Comment by tiann** [comment]
请仔细阅读 ReadMe
