### ISSUE TITLE
virtual xposed 64位框架和32位框架无法同时兼容QQ和微信

### ISSUE THREAD

**Issue by huijiawanquba** [android-hacker/VAExposed#1018]
## 问题描述

0.18.2和0.20.3版本无法同时兼容QQ（官网的32位）和微信（官网的64位）
## 复现步骤

1、安装0.20.3、0.18.2版本的virtual xposed。
2、安装微信、QQ进行测试。

## 环境

机型：华为荣耀note 10（RVL-AL09）
系统版本：Android 9
ROM版本：9.1.0.339(C00E333R1P11patch01)GPU Turbo
Xposed 插件以及插件版本：3.1.5
VirtualXposed版本：0.20.3 0.18.2

## 补充
1、0.20.3版本无法安装32位的QQ，可以正常安装、运行微信。
2、0.18.2版本可以正常安装、运行QQ。可以正常安装微信，但是无法运行，打开一直黑屏，直到退出程序。
运行微信报错如下：
![image](https://user-images.githubusercontent.com/17696974/124092409-654f4280-da89-11eb-87d4-ebcc6daf511d.png)
![image](https://user-images.githubusercontent.com/17696974/124092452-739d5e80-da89-11eb-9bfd-eafaa83ee189.png)

**Comment by huijiawanquba** [comment]
目前官网QQ都是32位的，怎么解决呢？

**Comment by tiann** [comment]
两个办法：
1. 同时安装32位和64位的框架，分开用。
2. 去 Google Play 下载 64 位的 QQ。
