### ISSUE TITLE
可以更新 Xposed API 到 93 吗

### ISSUE THREAD

**Issue by lovelyelfpop** [android-hacker/VAExposed#1050]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

有些模块使用了 93 的新功能，比如 https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences
但是最新的 VirtualXposed API 是 91，无法运行这些模块

## 希望的解决方案

希望更新 Xposed API 到 93

**Comment by tiann** [comment]
为何 API 到 93 之后就不兼容 91 了，这难道不是接口设计的问题吗？

**Comment by lovelyelfpop** [comment]
@tiann 类比你想想，你觉得 Android 1.0 会有 DocumentsProvider 吗？

**Comment by tiann** [comment]
那你同样类比一下，Android 1 上存在的接口，为什么到 Android 10 上调用不了呢？
在 VirtualXposed 里面，原来的接口 XSharedPreference 你可以用到天荒地老，根本不存在任何权限问题，为什么非要做破坏性变更？

**Comment by lovelyelfpop** [comment]
@tiann  XSharedPreference是可以用，还是原来的XSharedPreference类。
只是如果手机上的xposed框架的 Xposed API 是 91，就不支持在安卓N及以后的系统上使用（代码可以写，但实际不生效）。
只有 Xposed API = 93 才有效

**Comment by tiann** [comment]
在 VirtualXposed 里面，不论你 Android 版本是多少，XSharedPreference 都可以用。

**Comment by lovelyelfpop** [comment]
你没看这个嘛 https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences
我是用到了，只有93才支持XSharedPreferences这个新特性

**Comment by tiann** [comment]
我已经重复说了很多遍了。在 VXP 里面，你不需要做什么操作，管你 Android 版本多少，都可以用原来的 XSharedPreference。
