### ISSUE TITLE
微信最新版8.0.14无法打开

### ISSUE THREAD

**Issue by mynamecool** [android-hacker/VAExposed#1051]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

打开微信8.0.14提示打开失败

## 复现步骤

安装最新版微信后，复制到虚拟环境中，无法打开

## 环境

机型：华为nova7pro
系统版本：Android10 鸿蒙2.0
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by wolverinejojo** [comment]
魅族17pro flyme9 一样的

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
