### ISSUE TITLE
华硕rog3，安卓11无法正常使用

### ISSUE THREAD

**Issue by isaacclarke0827** [android-hacker/VAExposed#1052]
## 问题描述

安装好virtualxposed后，点击xposedinstaller启动，然后下方弹出正在打开的窗口，约五到六秒后，直接黑屏，但没有卡死，顶部消息栏在正常工作，但黑屏后再无反应，可以正常上滑退出应用。
在vxposed中安装的其他应用也都是同样的问题，例如微信，知乎。

## 复现步骤

1.安装vxposed
2.启动xposedinstaller

## 环境

机型：Asus ROG 3
系统版本：Android 11
ROM版本：18.0410.2109.172
Xposed 插件以及插件版本：无
VirtualXposed版本：0.20.3

## 补充

无

**Comment by isaacclarke0827** [comment]
另外补充一下，在黑屏前有新窗口打开的动画效果

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
