### ISSUE TITLE
Does not support android 11

### ISSUE THREAD

**Issue by Barshan-Mandal** [android-hacker/VAExposed#1073]
**Is your feature request related to a problem? Please describe.**
no
 I'm always frustrated when using wsa
**Describe the solution you'd like**
implement it

**Describe alternatives you've considered**

**Additional context**

**Comment by ajay9634** [comment]
It creates app data in Android/data 
But should create in VirtualXposed/vsdcard/0/Android/data.
Other issue is
Can't install apk by virtual xposed

**Comment by sunwusunwu** [comment]
什么时候支持安卓11啊

**Comment by Barshan-Mandal** [comment]
when to support android 11

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
