### ISSUE TITLE
Shell access to virtualxposed?

### ISSUE THREAD

**Issue by Inc0n** [android-hacker/VAExposed#1077]
**Is your feature request related to a problem? Please describe.**

I would want a run a binary version that functionaly is similar to Game Gaurdian, i.e. it needs ptrace capability.
Normal `adb shell` outside of virtualxposed, would disallow this. Hence, the requirement of shell access from within virtualxposed.

**Describe the solution you'd like**

Some sort of shell access, similar to `adb shell` or `ssh`.

**Describe alternatives you've considered**

Write an android application that invokes the binary executeble, however, it is not the most optimal, becauese of my preference of CMD over application and an introduction of a new layer of overhead.

**Additional context**

I will provide additional information if requested upon, since I am not aware of any immediately that I should provide right now.

**Comment by tiann** [comment]
Use `Runtime.exec`

**Comment by Inc0n** [comment]
I appreaciate a solution being suggested here, but I also do not understand what you mean by `Runtime.exec`, I would like a more eloborate answer to that.
For example, is there a wiki page for this? How can I access this from the app?

Thank you for your time

**Comment by tiann** [comment]
There are no adbd or sshd in VirtualXposed, it is just a wrapper for apps running in it. If you want to ptrace, just ptrace it, no needing for adb.
