### ISSUE TITLE
Facebook notifications not working on Android 10

### ISSUE THREAD

**Issue by huytc** [android-hacker/VAExposed#1082]
**Describe the bug**
When I click on the Notifications tab in my cloned Facebook app, it crashes.

**To Reproduce**
1. Download [Facebook APK](https://www.apkmirror.com/apk/facebook-2/facebook/facebook-352-0-0-20-117-release/facebook-352-0-0-20-117-17-android-apk-download/).
2. Install Facebook APK using VirtualXposed.
3. Log in to the virtual Facebook app.
4. Click on Notifications tab.
5. App crashes.

**Expected behavior**
App should show notifications properly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 10
 - Browser: stock browser
 - Version 0.20.3

**Additional context**
N/A

**Comment by didiaodanding** [comment]
您好，您的邮件已收到，谢谢。                                    --------李峰
