### ISSUE TITLE
最新版卡opening

### ISSUE THREAD

**Issue by lsh1215225** [android-hacker/VAExposed#1084]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

刚安装好添加应用后能正常打开使用，全部关闭后等一段时间再打开就卡opening

## 复现步骤

每次必现

## 环境

机型：坚果R2
系统版本：Android10
ROM版本：8.1.2.2
Xposed 插件以及插件版本：
VirtualXposed版本：0.20.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
