### ISSUE TITLE
License question. GPL Free Software?

### ISSUE THREAD

**Issue by davidalanreid** [android-hacker/VAExposed#1091]
**Is your feature request related to a problem? Please describe.**

The license information is not clear. 
According to LICENSE.txt, it is licensed under GPL as free software. But it appears to come from asLody/VirtualApp, which seems to have a commercial license.          

**Describe the solution you'd like**

A clear description of the license terms

**Describe alternatives you've considered**

There seem to be many copies of this code on github with a free license or no license. 

**Additional context**

What are the license options for this software?

**Comment by tiann** [comment]
#138
