### ISSUE TITLE
Not opening virtualxposed

### ISSUE THREAD

**Issue by jhonmaw** [android-hacker/VAExposed#1094]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Not opening the virtualxposed

**Comment by Devblade06** [comment]
Apps not opening
![Screenshot_20220418-202014_VirtualXposed](https://user-images.githubusercontent.com/103834752/163846761-74929f35-1db1-4563-b35e-53cb6af5993f.jpg)

**Comment by RynKings** [comment]
![Screenshot_2022-04-19-00-57-55-327_io.va.exposed64.jpg](https://user-images.githubusercontent.com/39035843/163872103-287d7dc8-73db-4905-9ef5-0c2ab8f77392.jpg)

Apps not showing too.

**Comment by Portpholio** [comment]
Same. Not showing while listed in manage apps.
& doesn't even launch after installing.

Miui 13

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
