### ISSUE TITLE
小米10更新到MIUI13.0.4 无法正常使用，应用列表中所有软件消失

### ISSUE THREAD

**Issue by seekriver** [android-hacker/VAExposed#1095]
## 问题描述

小米10 使用MIUI12.5 可以正常使用，昨晚小米10更新到MIUI13.0.4 （安卓12）之后，在VirtualXposed的应用列表中所有软件消失，但是在VirtualXposed的设置中的应用管理中可以看到已经安装的软件，其模块管理选项中也看不到已经安装的模块。

## 复现步骤

更新系统后出现
## 环境

机型：小米10 
系统版本：安卓12
ROM版本：MIUI13.0.4.0  SJBCNXM 稳定版
Xposed 插件以及插件版本：tiktok 23.9.5  tiktok助手1.0.0
VirtualXposed版本：0.20.3

## 补充
卸载重装VirtualXposed也无法恢复，在克隆软件安装完成后有个打开软件的按钮，点击打开会一直走进度条但打不开

**Comment by Sweetestcc** [comment]
同为小米10为13.0.3稳定版，出现同样问题

**Comment by lzp0528** [comment]
红米k40也有这种情况，应用安装后无显示并且打不开，点击模块管理也无反应
机型：红米k40
Android版本：12
MIUI版本：13.0.3
VirtualXposed版本：0.20.3

**Comment by yuandongfang** [comment]
同样的问题, 求助

**Comment by InoriILU** [comment]
k30pro 同状况，
MIUI 13，Android 12，
第一次使用，我还以为是我打开的方式不对，，

**Comment by T-SX** [comment]
Redmi10Pro同

**Comment by jokermonn** [comment]
MI11，MIX4 同

**Comment by mlsqq** [comment]
小米10最新内测同

**Comment by zmorningstart** [comment]
MIUI13.0.9稳定版本也是同样问题

**Comment by 954L** [comment]
同

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0
