### ISSUE TITLE
陌陌抢红包

### ISSUE THREAD

**Issue by 54huige** [android-hacker/VAExposed#1107]
## 场景描述

我想要在陌陌社交软件的群里自动抢红包，最好是每次都是最佳手气。具体原理可能不大明白，但是有人做过

## 希望的解决方案

我希望有这么一个插件

## 其他信息

实现的方式可能是大概率抢到红包吧，可能是解析红包里的数据获取是做第一个人去抢还是抢中间 还是抢结尾

**Comment by thisdk** [comment]
好的,我今晚开一家公司,请十几个人来帮你开发这个插件.保证能把整个红包抢过来.
