### ISSUE TITLE
能不能把http请求和tcp请求去掉

### ISSUE THREAD

**Issue by passerbyo** [android-hacker/VAExposed#1115]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

[(链接)](https://www.virustotal.com/gui/file/200d866f81ea46228de31fc4066cceeffab8e569b0fed0be34fa5a1091f6727c/behavior)

## 希望的解决方案

去掉http和tcp请求

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
自己 fork
