### ISSUE TITLE
MIUI 13 安装无显示内容

### ISSUE THREAD

**Issue by Root-1404** [android-hacker/VAExposed#1116]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

（请尽量详细地描述你遇到的问题）

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）
![Screenshot_2022-06-21-20-13-04-141_io va exposed6](https://user-images.githubusercontent.com/77722478/174803707-8253ddd8-b047-4f45-9e85-1d6d9434c8eb.jpg)
![Screenshot_2022-06-21-20-13-13-044_io va exposed6](https://user-images.githubusercontent.com/77722478/174803714-f4502e2d-3e8c-4a21-80a4-3530d6e3a65a.jpg)
![Screenshot_2022-06-21-20-16-32-049_com android se](https://user-images.githubusercontent.com/77722478/174803719-7a527b32-670a-46a0-80a5-f62c51f935f6.jpg)

视频链接：https://share.weiyun.com/Jk32tOuY
## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by huozaiwuli** [comment]
同样问题

**Comment by AzraelWarrior** [comment]
> 同样问题

用最新版本

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chn-yang** [comment]
在官网下载的0.20.3无法打开， 要在github release 下载0.22.0才可以

**Comment by jinx0321** [comment]
我也是,大佬救救我

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sanyang01** [comment]
use version 0.22，but new problem is #1131

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
