### ISSUE TITLE
打包后的virtualbox release版本在virustotal里报毒

### ISSUE THREAD

**Issue by passerbyo** [android-hacker/VAExposed#1120]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
打包后的virtualbox release版本在virustotal里报毒，报毒链接 https://www.virustotal.com/gui/file/2220ff9f016c538df9d757539a72ce04f42b2ebba5ec7ddf317b2098e0f2e48b

## 复现步骤

无

## 环境

机型：nexus
系统版本：android 11
ROM版本：稳定版本
Xposed 插件以及插件版本：无
VirtualXposed版本：最新

## 补充

打包后的virtualbox release版本在virustotal里报毒，报毒链接 https://www.virustotal.com/gui/file/2220ff9f016c538df9d757539a72ce04f42b2ebba5ec7ddf317b2098e0f2e48b 如何修复

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
仔细阅读 README
