### ISSUE TITLE
商用需要授权吗？

### ISSUE THREAD

**Issue by newlifepp** [android-hacker/VAExposed#1146]
不是GNU General Public License v3.0协议吗？为什么商用还需要授权才行？

**Comment by tiann** [comment]
本项目部分代码 fork 自 VirtualApp，“商用授权”来自于 VirtualApp 权益人提出的要求，在此我申明两点：

1. 项目中除 VirtualApp 外所有我贡献的代码为 GPLv3 协议。
2. VirtualApp 的代码 fork 自 GLPv3 的 commit 参见https://github.com/android-hacker/VirtualXposed/issues/138 因此理论上这个项目是纯正的 GPLv3。但我个人不懂法律，也不想因为这件事跟 VirtualApp 惹得一身骚，所以保留的上述声明；任何人可以基于自己的理解使用代码，当然你需要自己承担相应后果，并且一切后果与我本人无关。
