### ISSUE TITLE
Future, Open Source and relation to TaiChi

### ISSUE THREAD

**Issue by fungs** [android-hacker/VAExposed#1173]
Hi,

I was using VirtualXposed via F-Droid on past Android releases. Newer Android versions > 12 seem not to be supported properly. Looking at the state of development, I have some major questions which would help users understand where the whole thing is going.

1.  Development has stalled over the last years. What is the state of development of VirtualXposed in this repo?
2. What is the relation to TaiChi and is that app ever going to be open source and on F-Droid?

Like many others, I'm reluctant to install apps from untrusted sources and want to see the source code to be sure it is not going to do bad things.

Thanks for answering!

**Comment by tiann** [comment]
1. nearly dead.
2. same author, no other relation.
