### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#1177]
I'm trying to compile VirtualXposed but some sources are missing. VirtualApp lib sources appears to be very outdated, it does not match with the one in VX. What should I do?

![image](https://github.com/android-hacker/VirtualXposed/assets/127546925/d5bba1a7-ecbb-4fc2-9d82-7baf0fd96479)

**Comment by tiann** [comment]
this is `aidl`.

**Comment by ghost** [comment]
> this is `aidl`.

what's that? there is no mention in the Wiki

**Comment by luckyabsoluter** [comment]
https://developer.android.com/develop/background-work/services/aidl
>The Android Interface Definition Language (AIDL) is similar to other [IDLs](https://en.wikipedia.org/wiki/Interface_description_language): it lets you define the programming interface that both the client and service agree upon in order to communicate with each other using interprocess communication (IPC).
