### ISSUE TITLE
点击输入框闪退(所有应用)

### ISSUE THREAD

**Issue by wqk317** [android-hacker/VAExposed#206]
机型：小米8
系统版本：Android 8.1
ROM版本：开发版8.6.5
Xposed 插件以及插件版本：跟插件无关
VirtualXposed版本：0.10.1

部分log如下(酷安app点击搜索框闪退):
06-05 14:07:56.073 17267 17350 V HttpClientFactory$CoolMarketCookieJar: Add cookies, host: api.coolapk.com, at HttpClientFactory$CoolMarketCookieJar.loadForRequest(HttpClientFactory.java:163)
06-05 14:07:56.081  2628  2628 D GestureStubView: resetRenderProperty: showGestureStub
06-05 14:07:56.081  2628  2628 D GestureStubView: showGestureStub
06-05 14:07:56.081  2628  2628 D GestureStubView: resetRenderProperty: showGestureStub
06-05 14:07:56.081  2628  2628 D GestureStubView: showGestureStub
06-05 14:07:56.087  1341  3587 I Timeline: Timeline: App_transition_ready time:1686164
06-05 14:07:56.090  1341  3587 I Timeline: Timeline: App_transition_ready time:1686167
06-05 14:07:56.091  1341  3619 I Timeline: Timeline: App_transition_ready time:1686168
06-05 14:07:56.092  2628  2628 D GestureStubView: gatherTransparentRegion: need render w:54  h:1348
06-05 14:07:56.093  1341  3619 I Timeline: Timeline: App_transition_ready time:1686170
06-05 14:07:56.100  1341  3619 W AutofillManagerServiceImpl: App (package=io.va.exposed, UID=10282) passed component (ComponentInfo{com.coolapk.market/com.coolapk.market.view.search.SearchExtendActivity}) owned by UID 10150
06-05 14:07:56.094  2628  2628 D GestureStubView: gatherTransparentRegion: need render w:54  h:1348
06-05 14:07:56.101 17267 17267 D AndroidRuntime: Shutting down VM
06-05 14:07:56.101 17267 17267 E AndroidRuntime: FATAL EXCEPTION: main
06-05 14:07:56.101 17267 17267 E AndroidRuntime: Process: com.coolapk.market, PID: 17267
06-05 14:07:56.101 17267 17267 E AndroidRuntime: java.lang.SecurityException: Invalid component: ComponentInfo{com.coolapk.market/com.coolapk.market.view.search.SearchExtendActivity}
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2005)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1951)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.autofill.IAutoFillManager$Stub$Proxy.startSession(IAutoFillManager.java:397)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at com.lody.virtual.client.hook.base.MethodProxy.call(MethodProxy.java:92)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at $Proxy46.startSession(Unknown Source)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:1012)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:604)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:575)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6990)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.View.onWindowFocusChanged(View.java:12074)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.widget.TextView.onWindowFocusChanged(TextView.java:9618)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.widget.AutoCompleteTextView.onWindowFocusChanged(AutoCompleteTextView.java:1099)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.View.dispatchWindowFocusChanged(View.java:12044)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3931)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6603)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
06-05 14:07:56.101 17267 17267 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
06-05 14:07:56.102  1341  1994 I Timeline: Timeline: App_transition_ready time:1686178
06-05 14:07:56.103   790   790 D libEGL  : eglInitialize: enter
06-05 14:07:56.103   790   790 D libEGL  : eglInitialize: exit(res=1)
06-05 14:07:56.106 17267 17267 I XApp    : uncaught :Thread[main,5,main]
06-05 14:07:56.106 17267 17267 I XApp    : java.lang.SecurityException: Invalid component: ComponentInfo{com.coolapk.market/com.coolapk.market.view.search.SearchExtendActivity}
06-05 14:07:56.106 17267 17267 I XApp    :      at android.os.Parcel.readException(Parcel.java:2005)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.os.Parcel.readException(Parcel.java:1951)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.autofill.IAutoFillManager$Stub$Proxy.startSession(IAutoFillManager.java:397)
06-05 14:07:56.106 17267 17267 I XApp    :      at java.lang.reflect.Method.invoke(Native Method)
06-05 14:07:56.106 17267 17267 I XApp    :      at com.lody.virtual.client.hook.base.MethodProxy.call(MethodProxy.java:92)
06-05 14:07:56.106 17267 17267 I XApp    :      at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
06-05 14:07:56.106 17267 17267 I XApp    :      at java.lang.reflect.Proxy.invoke(Proxy.java:913)
06-05 14:07:56.106 17267 17267 I XApp    :      at $Proxy46.startSession(Unknown Source)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:1012)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:604)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:575)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6990)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.View.onWindowFocusChanged(View.java:12074)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.widget.TextView.onWindowFocusChanged(TextView.java:9618)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.widget.AutoCompleteTextView.onWindowFocusChanged(AutoCompleteTextView.java:1099)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.View.dispatchWindowFocusChanged(View.java:12044)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1398)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3931)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.os.Handler.dispatchMessage(Handler.java:106)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.os.Looper.loop(Looper.java:164)
06-05 14:07:56.106 17267 17267 I XApp    :      at android.app.ActivityThread.main(ActivityThread.java:6603)
06-05 14:07:56.106 17267 17267 I XApp    :      at java.lang.reflect.Method.invoke(Native Method)
06-05 14:07:56.106 17267 17267 I XApp    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
06-05 14:07:56.106 17267 17267 I XApp    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
06-05 14:07:56.107  1341  1376 I ActivityManager: Displayed io.va.exposed/com.lody.virtual.client.stub.StubActivity$C3: +61ms (total +90ms)
06-05 14:07:56.108  1341  1376 E ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
06-05 14:07:56.108   764   764 E ANDR-IOP: IOP HAL: Received pkg_name = io.va.exposed pid = 17267
06-05 14:07:56.108  3610  3755 I WtEventController: AM_Launch: 30009 TAG: 840704
06-05 14:07:56.108  3610  3755 I WtEventController: AM_Launch: 30009 TAG: 239299583
06-05 14:07:56.108   764   885 E ANDR-IOP: io prefetch Capture is deactivated
06-05 14:07:56.119   790   790 D libEGL  : eglInitialize: enter
06-05 14:07:56.119   790   790 D libEGL  : eglInitialize: exit(res=1)
06-05 14:07:56.130 17267 17267 I zygote  : System.exit called, status: 0

**Comment by tiann** [comment]
duplicate #200 

暂时关闭自动填充框架可。

**Comment by wqk317** [comment]
ok, 解决了, 感谢
