### ISSUE TITLE
微信完全无法打开

### ISSUE THREAD

**Issue by shugo-chara** [android-hacker/VAExposed#212]
miui10 vxposed最新。两周天出现微信频繁重新登陆，但是点击密码或任何选项均闪退，只能用声纹登录。
今天发现点击任何聊天框或者输入框都会闪退已无法使用。
卸载重新安装vx和微信后微信在初始界面点击登陆就闪退无法使用。

**Comment by tiann** [comment]
关闭系统的自动填充框架。

**Comment by shugo-chara** [comment]
感谢回复，确实是这个问题导致的，关掉后能正常显示了。
在miui上电池优化和锁定以及白名单都设置好后微信和云音乐后台时依旧会被频繁杀死，尤其是微信。再次登录时就会提示已登录异常。请问有办法解决吗。

**Comment by tiann** [comment]
可以尝试把外面的微信卸载掉，或者开启保守模式，或者不用微X，用微信增强模块替代。
