### ISSUE TITLE
Request for comment/details about VirtualXposed on XDA Developers

### ISSUE THREAD

**Issue by akhilkedia** [android-hacker/VAExposed#214]
**Is your feature request related to a problem? Please describe.**
Thank you for this Awesome project! This is Huge!!
Recently a post on XDA developers about VirtualXposed (https://forum.xda-developers.com/xposed/virtualxposed-xposed-root-unlock-t3760313) has generated a lot of attention. 
However, there is very little information about the specific details of how VirtualXposed actually works, which is leading to a lot of confusion and distrust.

**Describe the solution you'd like**
I have started a new thread on XDA here - https://forum.xda-developers.com/xposed/development/virtualxposed-analysis-module-t3800947
This thread is intended to serve as an All-in-one thread for developers to make modules compatible with VirtualXposed.
If possible, it would be a great help if you can see the thread and clear up issues mentioned there!

**Describe alternatives you've considered**
Currently, we are going through the source-code and doing hit-and-trial to figure what/how things work in VirtualXposed. However, this is a slow and error-prone process.

**Additional context**
What is XDA Developers - The largest website among english-speaking population for rooting/xposed/unlocking/modding/etc.

下面是上述的自动翻译的翻译 - 

**您的功能请求是否与问题有关？请描述。**
感谢你这个真棒项目！这是巨大的！
最近XDA开发者关于VirtualXposed的一篇文章（https://forum.xda-developers.com/xposed/virtualxposed-xposed-root-unlock-t3760313）引起了很多关注。
但是，关于VirtualXposed实际工作方式的具体细节信息很少，这导致了很多混淆和不信任。

**描述你想要的解决方案**
我已经在XDA上启动了一个新线程 - https://forum.xda-developers.com/xposed/development/virtualxposed-analysis-module-t3800947
此线程旨在用作开发人员用于使模块与VirtualXposed兼容的一体化线程。
如果可能的话，如果你能看到主题并清除那里提到的问题，这将是一个很大的帮助！

**描述你已经考虑过的选择**
目前，我们正在通过源代码并进行试用以确定VirtualXposed中的工作方式。但是，这是一个缓慢且容易出错的过程。

**附加背景**
什么是XDA开发人员 - 英语人口中最大的网站，用于生根/播放/解锁/修改/等等。

**Comment by tiann** [comment]
@akhilkedia Thank you, I will try my best to do it.

**Comment by tiann** [comment]
https://forum.xda-developers.com/xposed/development/virtualxposed-analysis-module-t3800947/post76751382#post76751382
