### ISSUE TITLE
在应用管理内增加《标记为开发调试工具》功能选项

### ISSUE THREAD

**Issue by M17764017422** [android-hacker/VAExposed#217]
实现对开发调试工具发起的应用安装请求执行无交互静默安装并立即启动该测试应用，然后在应用调试运行结束后直接返回调试开发工具。
用于AIDE- IDE、C4Droid等开发类工具的快速调试。

**Comment by tiann** [comment]
好的，我看一下怎么弄；谢谢建议。

**Comment by tiann** [comment]
手机上的开发工具？

**Comment by M17764017422** [comment]
是的

**Comment by tiann** [comment]
那没啥需求啊，主要的开发工作还是在电脑上完成的。
如果用AS，可以很方便滴做到：https://github.com/android-hacker/VirtualXposed/wiki/Utilities-For-Xposed-Module-Developer

**Comment by M17764017422** [comment]
还是有一定需求的，在外面的时候，一些临时的修改和测试在手机上做还是比较方便的。
手机写一些小项目的时候，写完直接编译运行肯定比电脑方便。
当然了如果你们认为没必要，那就等需求比较大的时候再实现。
