### ISSUE TITLE
Please consider targeting API 23+ with runtime permission support.

### ISSUE THREAD

**Issue by oasisfeng** [android-hacker/VAExposed#218]
VirtualXposed requires almost all permissions ever available on Android. That's fine, because this is an essential requirement. Still it will scare away many potential users.

I think runtime permission could solve that, at least partially.

With target API level above 23, no scary permissions will be requested at installation time of VirtualXposed.
Later at the launch time of inner app, depending on the target API level of that inner app, permissions could be requested at runtime before launching if it targets pre-23. For inner apps targeting 23+, no permissions need to be requested at launch time, all runtime permission requests could be just as smooth as the outer apps.

In the future, VirtualXposed could even let user reject permissions for inner apps targeting pre-23, with a relatively small efforts.

**Comment by tiann** [comment]
Thank you for your advice. In fact, the built-in permission control is working in progress: #33 

I was concentrating on improving the stability of the hook framework before ( there are so many crash when use some specific Xposed module, which is annoying). But it seems that the permission control is more important, lots of users in XDA are scared away : (

In a word, I will fix this as soon as possible.

**Comment by Enyby** [comment]
There are some problems with this solution. Some firmware with 6 android do not contain a dialog for issuing such permissions. In particular on some TVs. This leads to the fact that if you target an application for 6 android, you can not get permission to display system windows.
For this reason GameGuardian is targeted for android 5. There is no other solution.
However, if this segment of users is not important, then this problem can not be taken into account.

**Comment by tiann** [comment]
@Enyby Thank you for reminding! 

May be build a separate flavor for those users?

**Comment by Enyby** [comment]
I do not know. Solve yourself.
I would not do separate builds. In addition, it should still be explained to users, what it is, why they are needed, and what you need to download.
Many do not know such subtleties and will not understand what it is about.

In my opinion, if the choice between not to frighten users and the fact that it will not work everywhere, then the choice is obvious.

**Comment by oasisfeng** [comment]
It's not just "frighten users", but weakening the overall security integration of VirtualXposed.
Targeting an lower Android version exposes more security and privacy risk to the users, that's why Google started the "lowest target API level" enforcement on Google Play.

I never saw any Android TV devices not supporting the basic runtime permission mechanism. If any in the world, that would be trivial for VirtualXposed, whose user base is almost advanced users. They never use that crap devices at all.

**Comment by tiann** [comment]
I have completed it: https://github.com/android-hacker/VirtualXposed/commit/8ccb74d8f058407e61d22120f12ce48f4bde707d

It seems that Xiaomi device is special: https://github.com/hotchemi/PermissionsDispatcher/issues/187 I am looking into it.

**Comment by Enyby** [comment]
@oasisfeng 
It's all an illusion. The change in the API version can not affect security and any risks.
And Google raises the required version because they need to promote a new version of the OS.
If it were commercially viable, they would not have supported compatibility. But it is not commercially profitable, only because they support it.

**Comment by oasisfeng** [comment]
@tiann The current implementation might have a minor issue. If user grants a runtime permission, he/she thinks that permission is only granted to the currently running inner app, but actually the permission is granted to the whole VirtualXposed environment. As a result, later launched inner apps may implicitly gain permissions which were granted by user before to previous inner apps.

I'd suggest clone the basic UI implementation of stock runtime permission dialog into VirtualXposed and show it for those inner apps requesting permission which were already granted to VirtualXposed by user.

It will not be an easy task. So please just take your time.

**Comment by tiann** [comment]
@oasisfeng Yes, I only implement runtime permission now. Once an app grant a permission, all the other apps grant the permission automatically, so it can not control the permission separately.

In fact, I have been working on built-in privacy control for a while(separate permission control for each app), It has so much work to do. 

Now, I am trying another way: transplant [XPrivacyLua](https://github.com/android-hacker/XPrivacyLua) to VirtualXposed. Although the author said it is impossible, but i think it is feasible.

**Comment by tiann** [comment]
[I have transplanted XPrivacyLua to VirtualXposed](https://github.com/M66B/XPrivacyLua/pull/3) , it works well :)

When @M66B merge the PR, i will close this issue.

**Comment by M66B** [comment]
I won't accept the pull request. See the comments of the pull request about why not.

**Comment by tiann** [comment]
fixed in https://github.com/M66B/XPrivacyLua/commit/2f45dba9b2e7c530af845776bdb4b4ec8f05c821

Many thanks for M66B.
