### ISSUE TITLE
Http injector and ehi opener

### ISSUE THREAD

**Issue by 1nikolas** [android-hacker/VAExposed#219]
**Describe the bug**
After enabling the opener module for http injector app, virtualxposed crashes

**To Reproduce**
1. Install official http injector from play store
2. Add the http injector to virtualxposed
3. Install ehi opener to virtual Xposed (here is the apk http://fii.cz/tefyn)
4. Open http injector (works ok)
5. Now enable the module and reboot
6. Open http injector and virtualxposed crashes

**Expected behavior**
Http injector opens after enabling the module 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Nexus 10 (tablet actually)
 - OS: Android 7.1.2
 - Browser Chrome (Does it matter?)
 - Version Latest

**Additional context**
Ehi opener is an app that unlocks some locked settings when you import http injector configs. It works fine on legit Xposed installation

**Comment by ugwapings07** [comment]
It says injector failed

**Comment by Leslie18yrrOld** [comment]
The new update of http injector doesn't allow ehi opener to work

**Comment by 1nikolas** [comment]
Yeah this issue is 10 months old lol

**Comment by Nonstops** [comment]
Update!!
