### ISSUE TITLE
魅蓝E2提示无法激活Xposed

### ISSUE THREAD

**Issue by starlightjy** [android-hacker/VAExposed#221]
## 问题描述
如下图所示，无法正常激活框架，从而无法使用Xposed模块
![s80606-105002 1](https://user-images.githubusercontent.com/8947443/41191520-6ea0ff22-6c23-11e8-9854-3bb45eee7cec.jpg)

## 复现步骤

1.没有Root的手机，安装VirtualXposed0.10.3
2.原系统安装XposedInstaller 3.1.1
3.添加XposedInstaller到VirtualXposed
4.打开，出现如图所示的问题（一打开XposedInstaller就提示91版已安装，但未激活）
5.如果选择“Version 89”-> Install会提示设备未Root

## 环境

机型：魅蓝E2 (未Root)
系统版本：Flyme6，底层安卓6
ROM版本：6.3.0.2A稳定版
Xposed 插件以及插件版本：3.1.1
VirtualXposed版本：0.10.3

**Comment by tiann** [comment]
参考wiki操作：https://github.com/android-hacker/VirtualXposed/wiki/%E9%AD%85%E6%97%8F%E7%B3%BB%E7%BB%9F%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by starlightjy** [comment]
嗯,流程是对的,就是那个Xposed Installer的版本不对,原来必须要用作者提供的3.1.5~~~这下可以了,非常感谢 @tiann 

小建议:魅族系统上的那个提示系统限制的弹框最好把"务必使用提供的3.1.5版本Xposed Installer"加上去,这样可以更明显一点~~~
