### ISSUE TITLE
华为 nova 2s 微信长期不操作收不到消息

### ISSUE THREAD

**Issue by 545925763** [android-hacker/VAExposed#222]
1. 问题描述

VirtualXposed内运行微信，30分钟左右微信会收不到消息，必须点开微信下拉刷新，新消息才会弹出。

补充：耗电量/后台常驻/WLAN全设置/通知  全设

2. 环境

机型：华为 nova 2s
系统版本：EMUI 8.0.0
Xposed 插件以及插件版本：微信 6.6.6
VirtualXposed版本：0.9.8

**Comment by 545925763** [comment]
已测试

华为荣耀V9
华为nova3e
坚果pro

同样不行，30分钟左右微信会收不到消息，必须点开微信下拉刷新，新消息才会弹出。

**Comment by TheoShira** [comment]
+1 我华为的手机也不行，网易云音乐也会听着听着自动停止
