### ISSUE TITLE
Build fails due to google-cache repo blackout

### ISSUE THREAD

**Issue by tiliarou** [android-hacker/VAExposed#224]
**Describe the bug**
Travis and standard build failing with error message:

> * What went wrong:
> Could not resolve all files for configuration ':app:aospReleaseCompileClasspath'.
> > Could not find common.jar (android.arch.core:common:1.0.0).
>   Searched in the following locations:
>       https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

**To Reproduce**
Build VirtualXposed

**Expected behavior**
Successful build

**Additional context**
Repo jfrog displays the following:

> {
>   "errors" : [ {
>     "status" : 404,
>     "message" : "The repository 'google-cache' is blacked out and cannot serve artifact 'google-cache:android/arch/core/common/1.0.0/common-1.0.0.jar'."
>   } ]
> }

PS: on a side note, I can see in the tree that 1.1.1 is available, any reason not to target this latest version ?
[https://repo.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/google-cache/android/arch/core/common/1.1.1](https://repo.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/google-cache/android/arch/core/common/1.1.1)

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/ae112e15d00c8e560707432bc117f6294c0a09f3

It is a bug of jcenter, please refer: https://github.com/facebook/react-native/issues/19485
