### ISSUE TITLE
特性请求：权限管理器

### ISSUE THREAD

**Issue by MisakaMikoto-35c5** [android-hacker/VAExposed#231]
最新版本的 VirtualXposed 由于支持了 Android 的权限 API，导致我出现了以下两个问题：

- 在拒绝电话权限后，微信提示需要电话权限才能够运行；
- 在拒绝任意权限后，从启动器无法启动 QQ。

VirtualXposed 没有内置权限管理器，而 XPrivacy 在 VirtualXposed 上无法正常使用。我希望能够增加一个内置的可以模拟授权但返回空值的权限管理器。

**Comment by tiann** [comment]
duplicate #33

**Comment by tiann** [comment]
这个已经在进行中了，#33 跟 #217 有比较详细的讨论，这个就关掉了。
