### ISSUE TITLE
App crashing on latest version (0.11.2)

### ISSUE THREAD

**Issue by kolmant** [android-hacker/VAExposed#233]
**Describe the bug**
The app crashes at the start and keeps crashing

**To Reproduce**
Steps to reproduce the behavior
1. Open VirtualXposed and wait a few seconds
2. See error

**Screenshots**
![screenshot_2018-06-12-09-04-00-747_com miui bugreport](https://user-images.githubusercontent.com/4392332/41295468-477baa92-6e20-11e8-885c-3e6b7d57d455.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4
 - OS: Android Nougat
 - Version MIUI 9.5

**Comment by tiann** [comment]
which app? do  you install the GMS support?
