### ISSUE TITLE
Android TV 上 Google 账号登录支持

### ISSUE THREAD

**Issue by yylyyl** [android-hacker/VAExposed#234]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述

在我的设备（Sony Bravia TV, Android 7.0）上安装了 0.11.2 的 VirtualXposed，并且启用了 Google Service
安装 Android TV 版的 Youtube 之后，能正常打开看视频，但是无法登录账号
账号选择器一闪而过
尝试安装了 com.google.android.syncadapters.contacts_9-28_minAPI23(nodpi)_apkmirror.com.apk 但是没有用

PS: Android TV 上面好多按钮点不到，要用虚拟鼠标 😭

**Comment by tiann** [comment]
我用我的小米 MIX 2S试了一下，是可以登陆的。具体问题是什么？

**Comment by yylyyl** [comment]
关于这个问题录了一个视频，请看一下
https://drive.google.com/open?id=1RbJjSUe1mDaPR4mhX6zEb4OERQGcYayJ

不知道是不是 microg 的问题

**Comment by tiann** [comment]
没有Android TV的设备，用TV模拟器只有 x86的版本；我从apkpure上下载的 YouTube for Android TV 不支持 x86。没办法了。

**Comment by yylyyl** [comment]
在 APKMirror 上面找到有 x86 的，麻烦有空看一下
https://www.apkmirror.com/apk/google-inc/youtube-for-android-tv-android-tv/youtube-for-android-tv-android-tv-2-02-14-release/
![image](https://user-images.githubusercontent.com/2050648/41463108-d06e7bbe-70c7-11e8-92ab-3cf9a476d189.png)

**Comment by tiann** [comment]
已经试过了，模拟器上打不开，黑屏。
