### ISSUE TITLE
App crashed on Android TV device

### ISSUE THREAD

**Issue by cw4219** [android-hacker/VAExposed#235]
**Describe the bug**
App crashed on Android TV device
**To Reproduce**
1. Open app and wait a second
2. Crash

**Expected behavior**
Can open it

**Smartphone (please complete the following information):**
 - Device: [RK3328 Evaluation Board]
 - OS: [Android TV 8.1]
 - Browser [Webview]
 - Version [0.11.2]

**Additional context**
If there is no RK3328 EVB, is it possible to reproduce the issue via Android TV emulater?

**Comment by tiann** [comment]
which app crash?
