### ISSUE TITLE
MIUI系统，通知图标为VirtualXposed本身图标，非环境内通知发出的应用的图标

### ISSUE THREAD

**Issue by etnperlong** [android-hacker/VAExposed#237]
## 问题描述

当VirtualXposed虚拟环境内运行应用并收到通知时，MIUI系统会显示VirtualXposed本身图标而非通知发出的应用的图标。

## 复现步骤

打开微信，收到信息后，在MIUI系统上显示的是VirtualXposed本身图标，而非微信图标。如下所示。
![屏幕截图](https://i.loli.net/2018/06/13/5b2111421c6d2.jpg)

## 环境

机型：小米Note顶配
系统版本：MIUI 9.2.3.0 (based on Android 7.1)
ROM版本：稳定版
Xposed 插件以及插件版本：与插件无关
VirtualXposed版本：0.11.2

## 补充

查阅过相关资料，发现Stackflow上有相关信息，不知对解决此问题有否帮助。
[Java Android - Redmi 3 (MIUI) - Notification icons cannot be changed?](https://stackoverflow.com/questions/40146059/java-android-redmi-3-miui-notification-icons-cannot-be-changed)

**Comment by tiann** [comment]
This is behavior of MIUI system. You can not display different icons in notification, by default it takes app icon as notification icon.

**Comment by tiann** [comment]
有帮助，说的是无法解决。
