### ISSUE TITLE
在装有xposed的手机上fc，调xposed的软件 fc 包括 xposed installer

### ISSUE THREAD

**Issue by aaaaasuper** [android-hacker/VAExposed#238]

**Comment by aaaaasuper** [comment]
在装有xposed的手机上fc，调xposed的软件 fc 包括 xposed installer
把xposed 关闭调就可以了。
还有app setting 这个软件 在开与不开xposed 的情况下都fc
还有软件能不能像 类似软件一样，只要带xposed的功能就自动激活了，不用 xposed installer 控制

**Comment by tiann** [comment]
不要在Xposed和 VirtualXposed 中同时启用同一个模块。

**Comment by tiann** [comment]
第二个，自动激活；不会做。
