### ISSUE TITLE
特性请求：新安装应用默认开启存储重定向开关

### ISSUE THREAD

**Issue by Lawn** [android-hacker/VAExposed#239]
希望在高级设置里面添加可选开关：新安装应用默认开启存储重定向。
这样可以使新安装的应用和系统的隔离，方便不用时彻底删除，不用每安装一个应用就单独设置一次。

**Comment by tiann** [comment]
不要把你的需求当作所有用户的需求。

**Comment by Lawn** [comment]
好吧，那看以后有没有更多的人需要这个功能。

**Comment by M17764017422** [comment]
正在查找相关代码，不过我不会安卓开发，正在学习中

**Comment by drcege** [comment]
同需要。其实更多时候是想当虚拟机用，把应用隔离开……
