### ISSUE TITLE
不支持Shortcuts

### ISSUE THREAD

**Issue by toringzhang** [android-hacker/VAExposed#240]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
在VirtualXposed中，APP不支持shortcuts

**Comment by tiann** [comment]
不会支持，没啥用。
现在可以把内部的快捷方式直接创建到系统桌面上，也可以把内部的快捷方式放在VXP的app shortcut上。

虚拟桌面上的shortcut达不到shortcut的作用。
