### ISSUE TITLE
允许把内置的启动器设置为系统启动器

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#242]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
做一个单独的Activity，具有
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.HOME"/>
            </intent-filter>
属性，指向打开内部的启动器，并允许在设置内禁用这个Activity。
另外做一个"临时调用其他启动器"选项给不小心选中作为默认启动器的用户。

**Comment by ghost** [comment]
Um.
`            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.HOME"/>
            </intent-filter>`

**Comment by tiann** [comment]
既然你会写代码，为何不自己做了发个PR过来？
