### ISSUE TITLE
Google service 的地图支持问题

### ISSUE THREAD

**Issue by Arigato** [android-hacker/VAExposed#244]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

     感谢作者努力，我想用virtualXposed解决应用内谷歌地图偏移及google now限制问题，试验多次，仍无法达到目的。具体为：
     使用克隆方式或全新安装方式在VXposed中安装google框架相关包后，有时可以启动登录，有时闪退，有时黑屏，且登录或展示google play商店时非常慢。
     即使登录成功，在其它嵌入google maps的应用中也显示 google service 正在更新，无法正常显示地图。     
## 复现步骤
     使用克隆方式或全新安装方式在VXposed中安装google框架相关包后，通过google 设置或商店登录google ，并使用其它内嵌google 地图的应用打开，查看地图。
## 环境

机型：红米  5 plus
系统版本：miui 9.6.1.0 稳定版
ROM版本：
Xposed 插件以及插件版本：
VirtualXposed版本：0.11.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
“使用其它内嵌google 地图的应用” 举个例子

**Comment by Arigato** [comment]
我用的polar flow、Endomondo 这些运动相关的APP，在运动后，有涉及到地图轨迹的，都会在地图上显示，内嵌的都是谷歌地图，都会提示Google play services are updating。

**Comment by tiann** [comment]
用的是 高级设置里面的添加google服务，还是咋么做的？麻烦说清楚点啊，大哥。

**Comment by Arigato** [comment]
抱歉。我使用高级设置里添加google 服务后，多了microG service，但提示“您必须先更新Google play服务，然后才能运行****"。使用google相关的APP时，选择账户窗口一直弹出选择，无法继续。

**Comment by tiann** [comment]
我下载了一个polar flow，然后出去溜达了一圈；并没有生成任何轨迹，也没看到地图？

**Comment by Arigato** [comment]
烦请下载google play 上的Endomondo，打开锻炼页能否展示地图，锻炼后在动态中能否看到地图上轨迹。polar可能要对应手环产生的数据。另外请问谷歌相关应用都能正常使用吗，我用谷歌健身一直弹出账户选择框，每次选中确定后继续弹出。

**Comment by tiann** [comment]
覆盖安装一下这个：https://github.com/android-hacker/android_packages_apps_GmsCore/releases/download/0.2.4-2018-6-14/play-services-core-release-signed.apk

看能否解决问题；如果不能，那就等microG更新。

**Comment by tiann** [comment]
https://github.com/microg/android_packages_apps_GmsCore/pull/553

**Comment by Arigato** [comment]
谢谢！覆盖安装后，polar flow、Endomondo 对应的地图已能展示，并能不偏移展示轨迹。不过在polar flow中不能切换卫星地图（在手机原系统中可以）。再次感谢！
之前问题中有提到的google 应用使用问题，当前还未能解决：google maps安装后打开黑屏；安装google fit登录后白屏，不能正常使用，也请验证下。

**Comment by tiann** [comment]
microG不是所有都支持的，详细看mircoG的支持列表。这不是VXP的问题，我先关闭了。
