### ISSUE TITLE
Apps/games crash

### ISSUE THREAD

**Issue by ayhamo** [android-hacker/VAExposed#245]
Hi mate again :)
After latest update "google play service" 
When i install it all apps/game crashes on startup
Already tried to see it options but still
And i do appreciate your work :)
And i want to know about using G+ to sign in game
Also If there is any thing about lucky patcher/ and if it would work 
Ty btw :)

**Comment by ayhamo** [comment]
Also i do use this app as emulator in my phone :)

**Comment by tiann** [comment]
which apps/games crash?
will disable the FakeGApps2 in Xposed Installer make it work again?

**Comment by ayhamo** [comment]
Well when i uninstall G services it works agian

**Comment by ayhamo** [comment]
And all apps and game crashes

**Comment by tiann** [comment]
will disable the FakeGApps2 in Xposed Installer make it work again?

**Comment by ayhamo** [comment]
Well
I have tried both activated and deactivated
Both crashes the game and both doesn't work as i tried to add account to YouTube
Also i have only FakeGapps 
Not 2
