### ISSUE TITLE
DexClassLoader 加载的dex  使用 XSharedPreferences 获取的目录是data/data/

### ISSUE THREAD

**Issue by skyun1314** [android-hacker/VAExposed#246]
正常使用 XSharedPreferences 没有问题。
但是 DexClassLoader 加载的dex 。 使用 XSharedPreferences 获取的目录是data/data/

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/XposedBridge/commit/369714963527632147344cdd4595be8cf881c052

**Comment by skyun1314** [comment]
谢谢
