### ISSUE TITLE
为什么0.11.2版本强制要求给QQ权限？

### ISSUE THREAD

**Issue by soeben** [android-hacker/VAExposed#249]
为什么0.11.2版本强制要求给QQ权限？之前没给权限也用的好好的，就算没给权限不能用，建议也不要多此一举，不要终止启动

**Comment by tiann** [comment]
0.11.2 尝试加入了运行时权限，目前还有bug。急什么，慢慢来。

**Comment by tiann** [comment]
之前之所以能用，是因为你装完就默认给了所有权限。

**Comment by soeben** [comment]
但我并没有给VirtualXposed所有权限啊

**Comment by tiann** [comment]
安装的时候，给了很多很多权限。现在你安装的时候，VXP不会请求任何权限。还没做完善，说了有bug，你就不用质疑了。
实在进不去，可以创建一个快捷方式，通过快捷方式进去不验证权限。

**Comment by M17764017422** [comment]
之前之所以能用，是因为你装完就默认给了所有权限。他想说的是在安装完成后又在系统设置里面取消了不需要的权限，但里面的应用不会检测到，所以里面的QQ不会强制退出大多数功能依然能用。而这就是他想要实现的效果，因为现在一些应用喜欢在一开始的时候就动态申请一大堆权限不给就直接退出很烦人，完全不顾动态权限必须时再授权的权限管理理念。

**Comment by tiann** [comment]
我知道他什么意思，说过了还没做完善。

**Comment by tiann** [comment]
已修复。
