### ISSUE TITLE
[0.11.5]无法调用输入法

### ISSUE THREAD

**Issue by cherinyy** [android-hacker/VAExposed#251]
一调用就闪退
另外YalpStore存在问题，在其中下载应用是下载到主系统的Download文件夹中，并且调用的是系统界面的安装器。
并且修改了YalpStore安装配置后，发现VirtualXposed请求了Root权限......

**Comment by tiann** [comment]
关闭系统的自动填充框架即可

**Comment by tiann** [comment]
另外你说的安装调系统，应该是弹的通知那个吧？直接点下面的安装按钮即可。VXP通知弹出的安装，无法决定是安装到系统还是VXP内部。至于请求root的问题，你可以去 YalpStore https://github.com/yeriomin/YalpStore 提。

**Comment by tiann** [comment]
#200
