### ISSUE TITLE
开机后需要手工启动一次微信才能接收消息

### ISSUE THREAD

**Issue by nde123456** [android-hacker/VAExposed#252]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

安装在virtualXposed之外的微信，开机后无需手工启动微信，就能接收消息
安装在virtualXposed里的微信，开机后无法接收消息，需要手工启动一次微信才能接收消息

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：华为p20pro
系统版本：8.1
ROM版本：8.1.0.111
Xposed 插件以及插件版本：
VirtualXposed版本：0.11.5

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不会做这个特殊处理，加了自启动内部别的应用也会启动。

**Comment by muxiaoshan** [comment]
怎么在VX里面让微信自启动？
