### ISSUE TITLE
桌面图标没有红点和角标提示

### ISSUE THREAD

**Issue by nde123456** [android-hacker/VAExposed#253]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

安装在virtualXposed之外的微信，微信未读消息有红点和角标提示
安装在virtualXposed里的微信，微信未读消息没有红点和角标提示

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：华为p20pro
系统版本：8.1
ROM版本：8.1.0.111
Xposed 插件以及插件版本：
VirtualXposed版本：0.11.5

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
快捷方式的图标是不可能有小圆点的，没有任何系统的快捷方式支持快捷方式小圆点。小圆点只能显示在VXP的图标上。

**Comment by nde123456** [comment]
收到。
为何VXP图标上也没有小圆点提示？要如何打开？

**Comment by tiann** [comment]
通知使用权

**Comment by nde123456** [comment]
反复检查过确认，通知权限全部打开了，但是VXP还是没有小圆点

**Comment by tiann** [comment]
可能是系统不支持，MIUI是可以的。

**Comment by jiachengliu** [comment]
`华为手机是没有的，小米手机是有提示的。华为的官方参考代码如下:`try {
                        Bundle bunlde = new Bundle();
                        bunlde.putString("package", "io.va.exposed"); // com.test.badge is your package name
                        bunlde.putString("class", "io.virtualapp.splash.SplashActivity"); // com.test. badge.MainActivity is your apk main activity
                        bunlde.putInt("badgenumber", 12);
                        this.getContentResolver().call(Uri.parse("content://com.huawei.android.launcher.settings/badge/"), "change_badge", null, bunlde);
                    } catch (Exception e) {
                        RLog.d(TAG, "e.get:" + e.getMessage());
                    }
但是不知道在哪点处理收到的通知的，故不是添加到哪里。希望回复一下，万分感谢。
