### ISSUE TITLE
模拟城市我是市长无法运行，闪退

### ISSUE THREAD

**Issue by michaeldyl520** [android-hacker/VAExposed#254]
## 问题描述

http://app.mi.com/details?id=com.ea.simcitymobile.mi&ref=search
此链接下载的模拟城市我是市长，安装在virtualxposed中，点击打开闪退，求解决办法。

## 复现步骤

安装以上APP,点开即可复现

## 环境

机型：小米6
系统版本：8.0
ROM版本：MIUI10 8.6.19
Xposed 插件以及插件版本：未使用
VirtualXposed版本：0.11.5

**Comment by michaeldyl520** [comment]
@tiann 有办法解决吗

**Comment by michaeldyl520** [comment]
@tiann 或者是闪退日志在哪里看，了解下出错的问题。

**Comment by tiann** [comment]
优先级不高，暂不解决。
