### ISSUE TITLE
VXP中的微信和QQ如何模拟位置？

### ISSUE THREAD

**Issue by meetinnet** [android-hacker/VAExposed#255]
。。。。。。

用模拟位置 1.2.681，选择不了vxp里面的程序，只能选择vxp本身， 可是模拟位置之后没有效果，里面的应用，微信或者QQ位置还是系统的，不是模拟之后的。

.

**Comment by tiann** [comment]
把模拟位置装在vxp里面。

另: 提issue之前请先阅读README。
