### ISSUE TITLE
关于动态权限的一点意见

### ISSUE THREAD

**Issue by ColinZeb** [android-hacker/VAExposed#256]
之前我用VirtualXposed是因为手机不方便root，用来体验下一些xposed模块，新鲜劲过了之后就没玩模块了，一直把VirtualXposed当成app沙盒，用于过滤敏感信息，比如联系人、IMEI等。
但是出了动态权限后我发现VirtualXposed会请求敏感权限了，这就没法当沙盒用了，请问能不能在设置中加一条伪装权限的设置，因为国内一些流氓软件不给权限不让打开，比如微博微信等。

**Comment by ColinZeb** [comment]
对了，麻烦问下动态权限之前的版本是哪个，我先用着，谢谢

**Comment by tiann** [comment]
没动态权限之前，问都不会问你，安装之后直接拥有了所有权限。所以你把它当沙盒，是想多了。VirtualXposed 从来没有声称自己是沙盒，也不会把自己做成沙盒。

看个发布日志就能知道的东西，还要提个issue来问？

**Comment by ColinZeb** [comment]
以前的权限全关，并不影响运行，当沙盒有什么问题，你就不能正常点讲话?
我是用着用着，更新了不能用了，需要同意权限申请才能用，所以才来发意见。
而且这是意见类型的issuse，我写什么不行？我又没发到bug类型下

**Comment by ColinZeb** [comment]
> 看个发布日志就能知道的东西，还要提个issue来问？

我这是顺带问一下，又不是专门提个issue来问，不知道你喷个什么劲 @tiann

**Comment by tiann** [comment]
厉害，这就是喷了。惹不起。

**Comment by ColinZeb** [comment]
在你眼里孤儿才是喷对吧。您才厉害，您的app用不起，拜拜了您。

**Comment by tiann** [comment]
赶紧卸载。
