### ISSUE TITLE
支持删除deepshortcut

### ISSUE THREAD

**Issue by TheoShira** [android-hacker/VAExposed#257]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
请问长按“VirtualXposed”出现的下拉框里的快捷方式 如何删除？

我是在“VirtualXposed”中的应用长按创建快捷方式之后，在“VirtualXposed”长按出现的下拉框里就有了=快捷方式，但不知道如何删除

**Comment by tiann** [comment]
目前还不支持删除

**Comment by TheoShira** [comment]
快捷方式 有点长 ，那有啥折中的办法不

**Comment by xinyangslove** [comment]
假如“分身A”软件在系统桌面上创建了快捷方式，但是当删除“分身A”后系统桌面上面的快捷方式没有被删除.请问如何解决？查看了下virtualapp的源码，有一个方法是removeShortcut()，但是使用该方法后发现快捷方式无法删除.

**Comment by tiann** [comment]
不影响使用，暂不修复
