### ISSUE TITLE
0.11.5版本的源码zip包里面的launcher这个module目录是空的

### ISSUE THREAD

**Issue by chenzhihui28** [android-hacker/VAExposed#258]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

（请尽量详细地描述你遇到的问题）
0.11.5版本的源码zip包里面的launcher这个module目录是空的

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）
release页面下载0.11.5版本的源码zip包

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
先读 wiki：https://github.com/android-hacker/VirtualXposed/wiki/How-to-compile
