### ISSUE TITLE
请教装了原版框架和在VXP里面的框架冲突怎么办

### ISSUE THREAD

**Issue by meetinnet** [android-hacker/VAExposed#259]
。。。。

一直没注意，今天才发现，VXP里面的微x，Qx在框架里面都没有勾选，但是微信和QQ都可以防撤回，原来vxp外面的框架还是起作用的。但是模拟位置这个App就不好用，里面外面无论怎么设置，都对vxp里面的微信qq不起作用。现在的问题是，vxp里面的框架不能启用任何模块，随便启用一个，vxp里面所有应用就打不开， 太快了，吃豆豆完了直接就没反应了。去掉模块的勾选，应用都可以正常打开。

装两个框架是因为之前用了分身微信，发现微x不好用，以为是不支持两个号，现在看也是支持，但是模拟位置对分身微信不起作用。

能分析分析这是怎么回事么，感觉好乱，摸不着头绪。

**Comment by tiann** [comment]
这不用分析。

你外面装了XP，你的整个系统就被改了；任意进程启动之后都会有系统的XP框架，VXP本身也不例外。
VXP本身只是一个普通的APP，外部的系统怎样，它就怎样。外部XP加载之后，对VXP内部的任意进程自动生效。

如果你在VXP里面再开启模块，那么模块加载了两次，会出现类冲突。

**Comment by meetinnet** [comment]
。。。

原来这样，这就解释的通了。

那么如果在vxp里面的框架，加载外面系统里框架没有的模块，是不是就不会冲突了呢？

比如在vxp里装一个微信增强模块，外面框架不装， 那么按理论来说，就不会冲突了？

多谢。

**Comment by meetinnet** [comment]
还有就是，上次问过你，模拟位置那个app，本来是在系统外面装的，对vxp里面的应用不起作用，你说应该装在vxp里面，可是装里面也不好用，这好像又跟上面说的不太一样了.

怎么不能编辑帖子呢。

**Comment by tiann** [comment]
跟模块自己的实现也有关系
