### ISSUE TITLE
支付宝APP部分页面打不开

### ISSUE THREAD

**Issue by xplusyi** [android-hacker/VAExposed#260]
## 问题描述

在VXP中启动支付宝，登录账号等一切正常。但是有些控件点击后，没有任何反应，不能打开相应页面。
比如，
（1）首页中部位置的**服务提醒通知框**，点击没反应；
（2）“**我的**”-->右上角“**设置**”-->“**账号管理**”，点击没有反应；
同一个页面的or“手机号”or“安全中心”or“通用”or“求助反映”or“关于”，点击均没有反应；
以及最下面“退出登录”->"换账号登录“，点击也没有反应。

## 复现步骤

每次点击上述界面，100%复现。即使用高级设定中的关闭VXP中的Exposed功能也是一样。
VXP任何历史版本，以及支付宝当前最新版10.1.25.752以及历史版本。
另外，容器APP是没有这个问题的，但是它不支持Android8.

## 环境

机型：小米6
系统版本：Android 8.0.0
ROM版本：MIUI9稳定版
Xposed 插件以及插件版本：框架91版，关闭Xposed也无济于事
VirtualXposed版本：0.11.5以及任何历史版本

## 补充

虽然可以用VXP双开支付宝，但无法实现多账号切换的目的。
请作者百忙之中抽空查看一下，希望能够修复。多谢。

**Comment by tiann** [comment]
把支付宝装里面有什么用途？

**Comment by baskgithub** [comment]
比如多个小号给自己蚂蚁森林浇水啊

**Comment by xpirad** [comment]
装里面防止支付宝在sd卡根目录下面生成垃圾文件

**Comment by tiann** [comment]
VirtualXposed 的主要目的是使用Xposed模块，还有很多重要的问题没解决；这个先放放吧。

**Comment by gordonpro** [comment]
@tiann 这个貌似和 mpaas 的 scheme 方式打开有关

**Comment by 4ft35t** [comment]
@xpirad  如果只是为了防止支付宝在sd卡根目录下面生成垃圾文件，在外面用 Appops 忽略读写权限就可以，除了不能接收发送图片，扫码啥的一切正常。

**Comment by xpirad** [comment]
@4ft35t 这样哦 thanks！

**Comment by xf11075** [comment]
我的也有这个问题

**Comment by xf11075** [comment]
作者停更不维护了，好可惜-_-

**Comment by xpirad** [comment]
@xf11075  22小时前更新过你跟我说不维护了？？？

**Comment by xf11075** [comment]
@xpirad 我是看到0.12.7的版本更新说明里面写的“暂停更新：维护VirtualXposed耗费了我太多太多的时间，得不偿失；目前我已经很满意了，有缘再见。”。。。

**Comment by xpirad** [comment]
@xf11075  这样。。。。。。

**Comment by laidianzan** [comment]
我就是注册个账号来点赞

**Comment by xplusyi** [comment]
好歹支付宝也是装机量第二的APP吧，不完全支持好可惜。。、

**Comment by tiann** [comment]
fixed https://github.com/android-hacker/VirtualXposed/releases/tag/0.14.0

**Comment by xf11075** [comment]
@tiann 多谢大佬的支持！
