### ISSUE TITLE
360 N6 Pro 在GG版本无法添加应用

### ISSUE THREAD

**Issue by BuSheTeam** [android-hacker/VAExposed#261]
在VXP 0.11.2 0.11.5 For GG #直到最新版本 中，均无法添加应用。

**Comment by BuSheTeam** [comment]
Andorid Version 7.1.1

**Comment by tiann** [comment]
具体情况？我测试了一下，正常。

**Comment by BuSheTeam** [comment]
具体情况:在系统桌面打开VXP For GG点击 菜单键 ，选择添加应用之后闪退到VXP桌面(使用非GG版本正常)
(Android 7.1
Qhioo 360 N6 Pro)

**Comment by tiann** [comment]
0.11.5 不会有此问题，0.11.2 可能有，你仔细试下。

**Comment by BuSheTeam** [comment]
问题确实存在在1.1.5

**Comment by BuSheTeam** [comment]
貌似只有我这个机型有问题
360 N6 Pro

**Comment by BuSheTeam** [comment]
请尽快解决这个 Issues

**Comment by tiann** [comment]
我没这机器啊，哪里去尽快？
你可以自己看看原因，解决了给我发个PR。

**Comment by BuSheTeam** [comment]
那么可以披露一下在GG版本当中有哪些改动吗(我bushe就是饿死，从Github大楼跳下去，也不会把这个项目拿来商用(真不香))
