### ISSUE TITLE
xposed模块分身问题

### ISSUE THREAD

**Issue by dmlgzs** [android-hacker/VAExposed#262]
## 问题描述
用VXP安装模块，所有的xposed模块均不支持增加分身（普通应用可以）

## 复现步骤
1、在VXP中增加xposed模块（已在VXP里安装过）
2、无法出现“安装分身”选项
3、应用列表也没有改变

## 环境

机型：华为畅享7plus，360 Q5，红米等机型均出现
系统版本：7.0，6.1，5.1
ROM版本：均为稳定版
Xposed 插件以及插件版本：所有xposed插件
VirtualXposed版本：0.11.5

## 补充
无

**Comment by tiann** [comment]
这是feature，不会修复。
