### ISSUE TITLE
建议可允许内部应用读取内部应用列表

### ISSUE THREAD

**Issue by etnperlong** [android-hacker/VAExposed#263]
## 详细描述
在VXP内部安装酷安后，无法读取已安装应用列表。不知道是暂未支持还是一个BUG，就用Feature模板提ISSUE了。

VXP版本：0.11.5

**Comment by tiann** [comment]
内部APP是可以读取的。酷安不显示列表，是因为酷安的判断规则是：必须读到五个以上的系统应用才显示。VXP内部没有系统应用，所以不显示，这与VXP无关。
