### ISSUE TITLE
关于新版xposed-core把微信的wcdb相关的方法都自动过滤意见

### ISSUE THREAD

**Issue by captain-black** [android-hacker/VAExposed#265]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
看见新版xposed-core把微信的wcdb相关的方法都自动过滤了，是因为后这些native方法会导致问题而过滤了吗？但是如果过滤了，我建议还是在里面输出一下log，告诉开发者，不然会造成困扰啊！就比如我，设置的钩子死活安装不上，弄了很久，上来看源码才明白什么回事，被迫把版本降回0.9.8。

我猜测：这种钩这种native方法造成不稳定的原因是JNI对应的lib还没加载就load class了，后来lib加载了之后又把方法的地址重定向了吧？就比如wcdb，我找到他的主入口类com.tencent.wcdb.database.SQLiteDatabase，先findClass一下（内部会调用load class，SQLiteDatabase类的static块会调用loadlib来加载对应的.so），之后的跟wcdb相关的钩子都能稳定运作了！简单粗暴的将相关钩子忽略了似乎不太妥。

**Comment by tiann** [comment]
你说的是对的，详见： #39 
我可以在exposed 中提前 load wcdb的so绕过这个问题，彻底native方法的 hook 有点麻烦。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/f5a31dbffe9cfa3c7aa746836655e01223f70560
