### ISSUE TITLE
Environment.getExternalStorageDirectory()获取路径问题

### ISSUE THREAD

**Issue by captain-black** [android-hacker/VAExposed#266]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

我自己写自定义插件的时候，Environment.getExternalStorageDirectory()获取路径，据我观察vxp里面的应用目录都重定向到VirtualXposed/vsdcard/下，然后我调用Environment.getExternalStorageDirectory()还是sdcard/，有什么办法准确获取到重定向的路径吗？或者怎么判断插件运行在vxp环境里面，我代码做兼容处理？

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：MI 5
系统版本：Android 7.0
ROM版本：MIUI 9.8.3.26开发版
Xposed 插件以及插件版本：自定义插件
VirtualXposed版本：0.9.8

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
VirtualXposed/vsdcard 目前只有用户主动开启了重定向，才会重定向到这里的；另外，微信和QQ的 /sdcard/tencent目录也会重定向到这里。其他的sd卡访问都是跟正常的一样的。

System.getProperty("vxp") != null 即是在vxp中运行。

**Comment by captain-black** [comment]
好！谢谢！
