### ISSUE TITLE
华为8.0 网易云音乐启动卡屏

### ISSUE THREAD

**Issue by ttorange1** [android-hacker/VAExposed#273]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

打开音量增强器后，网易云音乐不能启动，卡在正在启动界面上。

## 复现步骤

先打开音量增强器，网易云音乐不能启动；反之，先打开网易云音乐，再打开音量增强器，则一切正常，插件工作也正常。

## 环境

机型：华为nova 2s
系统版本：emui 8.0
ROM版本：8.0.0.161(C00)
Xposed 插件以及插件版本：音量增强器，0.2.1或0.2.5
VirtualXposed版本：0.9.9~0.12.1各版本
网易云音乐版本：3.5.2和5.1.0等多个版本均如此

## 补充

清空数据并卸载重装插件、云音乐、vx，问题依旧。

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
卸载所有，用最新的vxp试。这问题已经解决了。

**Comment by ttorange1** [comment]
安装插件和网银云音乐，需要先安装在系统里再安装到vxp，还是直接用vxp的安装器安装？

**Comment by tiann** [comment]
直接在里面安装

**Comment by ttorange1** [comment]
不知道为什么还是不行，我全部都卸载了，也清空了数据，但是重装后问题依旧。

**Comment by ttorange1** [comment]
装vxp 0.12.1后还发现了一个奇怪的现象，原来先打开网易云音乐再打开音量增强器，插件工作是正常的，现在这么操作音量增强器失灵了。当然先打开音量增强器，仍然停在opening界面。
