### ISSUE TITLE
跳一跳插件使用无效问题

### ISSUE THREAD

**Issue by TheoShira** [android-hacker/VAExposed#274]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
请问微信跳一跳辅助（就是推荐的插件）使用一直无效是插件问题还是我手机问题？
其他推荐的 微信插件 网易云插件正常使用

机型：HUAWEI MATERS
系统版本：8.1.0
ROM版本：EMUI 8.1
Xposed 插件以及插件版本：跳一跳辅助1.6&1.7
VirtualXposed版本：0.12.1

**Comment by tiann** [comment]
说明一下具体情况很难？
你当我算命先生，掐指一算就知道问题在哪吗？

**Comment by TheoShira** [comment]
其他推荐的 微信插件 网易云插件正常使用
目前使用当中就跳一跳不行

机型：HUAWEI MATERS
系统版本：8.1.0
ROM版本：EMUI 8.1
Xposed 插件以及插件版本：跳一跳辅助1.6&1.7
VirtualXposed版本：0.12.1

**Comment by tiann** [comment]
微信版本？

**Comment by TheoShira** [comment]
微信是 6.6.7 play版的

刚刚手机自动更新了系统 可以用了 不知道什么情况

**Comment by tiann** [comment]
某些插件play版本不一定支持的，你需要把问题反馈给对应的插件开发者。
