### ISSUE TITLE
建议添加默认重定向开关

### ISSUE THREAD

**Issue by fxsheep** [android-hacker/VAExposed#275]
建议在高级设置里添加一个默认启用应用重定向的开关，开启后新安装的应用默认启用存储空间重定向功能。

其实VirtualXposed既然已经用到了VirtualApp，那么其实很多东西已经和外边隔离开了（例如，已安装应用列表），那存储不隔离开有时候就会冲突（如内外安装同一个应用），所以需要提供一个默认启用的开关

**Comment by tiann** [comment]
#239
