### ISSUE TITLE
“汤来了"闪退

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [android-hacker/VAExposed#277]
## 问题描述

汤来了(google play版)打开闪退
https://play.google.com/store/apps/details?id=com.hochan.coldsoup

## 环境

机型：Xperia XZP
系统版本：8.0.0
ROM版本：2.7.2(play版本)
Xposed 插件以及插件版本：默认
VirtualXposed版本：0.12.1

**Comment by tiann** [comment]
加固应用不支持（此处使用的是乐加固）。
