### ISSUE TITLE
模拟位置闪退

### ISSUE THREAD

**Issue by zzw6776** [android-hacker/VAExposed#282]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

模拟位置闪退

## 复现步骤

打开就闪退

## 环境

机型：nex
系统版本：8.1
ROM版本：稳定版
Xposed 插件以及插件版本：最新
VirtualXposed版本  最新

## 补充
[#]
（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by zzw6776** [comment]
报错截图如下
![image](https://user-images.githubusercontent.com/14048998/41973559-e2577ce8-7a47-11e8-9e74-d9bfd6ee08f6.png)

xposed的日志如下

[1.txt](https://github.com/android-hacker/VirtualXposed/files/2141136/1.txt)

**Comment by zzw6776** [comment]
以下为软件的日志报错

[Crash_180627_2028.log](https://github.com/android-hacker/VirtualXposed/files/2141164/Crash_180627_2028.log)

**Comment by tiann** [comment]
你可以先关闭系统的自动填充框架绕过这个问题。

**Comment by tiann** [comment]
#200

**Comment by zzw6776** [comment]
感谢 已解决
