### ISSUE TITLE
App ops似乎无法禁用 VirtualXposed 权限

### ISSUE THREAD

**Issue by flyher** [android-hacker/VAExposed#285]
## 问题描述
App ops似乎无法禁用 VirtualXposed 权限或者说是VX被设定的权限可能VX内的应用绕过？

## 复现步骤

1. 手机切换到使用数据连接，关闭wifi；
2. 打开app ops权限管理；
3. app ops中禁用VirtualXposed 的wifi自动开启连接权限（测试可以禁用所有权限）;
4. 同时，在系统自带的权限管理中禁止“开启WLAN”
5. 在VirtualXposed中安装百度系软件，例如百度贴吧；
6. 打开百度贴吧，
7. wifi会被自动打开

## 环境

机型：一加
系统版本：官方发行的稳定版本
ROM版本：Android 8.1
Xposed 插件以及插件版本：
VirtualXposed版本：0.12.1及其以前版本

## 补充

扩展一下，如果app ops的权限管理对vx里面的应用无效，
不知道是不是我操作有误，

**Comment by tiann** [comment]
没有用过 App Ops，理论上是不可能的。VirtualXposed 是一个普通的APP，不存在提权的可能。或许你应该反馈给 App Ops。

**Comment by flyher** [comment]
@tiann 
那么去掉2，3条。
仅仅使用第4条，使用系统自带的权限管理。
同样可以复现上述问题。也就是VX里面的软件不能继承VX的被授予的权限

**Comment by tiann** [comment]
你换个别的权限试试。

**Comment by flyher** [comment]
1.经过测试，同一个版本装在VX中，禁止VX自动开启WIFI连接功能。
打开百度贴吧，会唤醒其他百度系软件，并一定大概率开启WIFI连接。
2.同一版本装到系统中，禁用软件的自动开启WIFI连接功能，此时，百度贴吧无法自动开启WIFI连接。

注：测试情况下，自带系统未安装其他百度系软件，VX中安装了百度系软件。

因为没有权限请求记录，没法看到其他权限是不是同样被绕过。WIFI被启用源于习惯用数据流量，偶然间发现WIFI经常被自动打开。

不管能不能解决，希望下面能有更多网友测试一下这个问题。

**Comment by tiann** [comment]
你找个别的权限禁用掉看看能不能获取不就行了。

VX内部的APP的权限都是通过VX本体申请的，不存在内部APP可以绕过的问题；从原理上说不通。

**Comment by tiann** [comment]
“并一定大概率开启” 你把除VX外其他所有软件的WIFI开启权限全部禁止，看一下。

**Comment by flyher** [comment]
@tiann 
```
phone
 |--vx(百度贴吧)
 |--other software
```
百度贴吧在VX里面，按照道理来讲，百度贴吧应该没法唤醒 other software ，只能唤醒VX里面的软件。
而VX我已经禁用了权限。

很认证的重复做了一下操作步骤：
1.禁用phone中所有软件的“开启WIFI连接”权限；
2.启动VX里面的百度贴吧；
3.过一会儿（任务管理只看到VX中的百度系被唤醒），WIFI自动被打开（测试启动VX中其他非百度系软件，WIFI不会自动被打开）；
4.关闭所有软件，安装同一版本百度贴吧到phone中；
5.禁用百度贴吧“开启WIFI连接”权限，并打开百度贴吧；
6.没有发现百度贴吧主动请求打开WIFI；
7.我本机未Root，怀疑是贴吧是不是有检测，居然能绕过，实在想不到是什么原因；


另外怎么查看有没有其他权限被 VX里面的百度贴吧绕过？例如通讯录，不会Android开发，好像这个我解决不了。

**Comment by tiann** [comment]
你把变量控制好仔细测试一下，我觉得这是不可能的。

**Comment by flyher** [comment]
@tiann 
你说的不可能是指我上面7步做的操作是复现不了，还是？
我现在试试删除VX上的百度贴吧重新操作试试。

**Comment by flyher** [comment]
重新安装后打开，直接自动开启了WIFI ，也许你不相信，看起来我需要找个录屏软件。
正因为我觉得不可思议，

**Comment by tiann** [comment]
所谓的双开，其实内部并不存在一个真正的“百度贴吧”，实际上运行的还是VX；如果VX没有权限，是做不到的，从技术上根本就行不通。

内部软件是可以唤醒外部APP的，这并不是一个隔离的环境。

你这个测试有很多变量没有控制好，得出的结论并不可信。比如，打开内部的贴吧唤醒了外部某个有权限的进程等。

**Comment by flyher** [comment]
你说的对，确实有很多变量无法控制好，即使我禁止了所有软件的WIFI权限，依然无法保证不会是某些系统级的软件依然拥有某些权限被唤醒做的手脚。
鉴于清空手机测试似乎成本比较高，且可能依然无法得出好的结论，所以这个issue我暂时关了。
感谢你的回复。
