### ISSUE TITLE
增加一个内置的类似于阻止运行的功能

### ISSUE THREAD

**Issue by ZYFDroid** [android-hacker/VAExposed#286]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
增加一个类似阻止运行的功能，禁止一些应用自启

**Comment by tiann** [comment]
Virtual**Xposed** is not VirtualPreventRunning.

**Comment by ZYFDroid** [comment]
禁止的是VirtualXposed内安装的应用的自启动
