### ISSUE TITLE
VXP里面微信收藏空间的容量为0

### ISSUE THREAD

**Issue by meetinnet** [android-hacker/VAExposed#289]
。。。。。。。。

测试了几次，应该是有问题的。

正常登录系统微信，收藏空间为默认的2G以下，登录VXP里面的微信，收藏空间就是0，无法收藏任何文章，而且以前收藏过的文章，图片，视频，都不可见，当然并没有丢失。

我的是这样，你看看是不是。@tiann

**Comment by tiann** [comment]
请按照 issue 模版说明具体情况。

**Comment by meetinnet** [comment]
没什么好说明的，进去一看就能看到容量。

**Comment by tiann** [comment]
微信版本是多少，VXP版本是多少，有没有开插件，开的什么插件，插件版本是多少？

影响的因素那么多，按照模版说明下情况很难？

你觉得没啥好说的就是那么回事，别人知道你是具体什么情况吗？

**Comment by meetinnet** [comment]
我觉得你应该先看一下自己vxp里面的微信是不是这个情况，如果并没有我提出的这个问题，那么完全可以回复说这问题是个例，再close掉，那我再去找个例的原因，如果你也是有同样的问题，那还需要别人说明那么多因素吗？你们不是更专业？最重要的是，进去看一眼用不了2秒钟，比打那么多字容易太多。

**Comment by tiann** [comment]
你觉得我没看吗？我看到了issue第一时间打开了微信的收藏，可是没看到里面有任何说容量相关的东西。

不要天天在那"我觉得我以为"，你的情况不代表别人的情况，麻烦多现在别人的角度考虑问题。你觉得最重要的是进去用不了两秒钟，我觉得简直就是搞笑，我进去什么都没有。现在是你遇到了问题要我解决，我叫你说清楚情况你还不愿意。你把自己当什么了。

你要是说明怎么看容量，自己微信版本是多少，我说不定几分钟就给你解决了，至于拖这么长时间不了了之？

天天提这种没有意义的issue的人太多了，我没那么多时间跟你们纠缠。不愿意配合就拉倒。

**Comment by meetinnet** [comment]
虽然不想再回复了，这个问题对我来说本也是可有可无，只是觉得还在用vxp，发现问题就应该提出来，可能别人也会遇到。可是觉得确实是挺搞笑的，啥都想到了愣是没想到你是连在哪儿看容量都不会，这是我压根没考虑到的。你点开收藏没看到里面有任何说容量相关的东西就觉得别人提的问题是搞笑，这是不是就是你所说的 “”不要天天在那"我觉得我以为"，你的情况不代表别人的情况“”呢？  退一万步说，即使我开始就按照模板所列，把微信版本是多少，VXP版本是多少，有没有开插件，开的什么插件，插件版本是多少等等情况一一都写上，也断然不会想到还要写上怎么去看容量，你还是不知道在哪看，还是会说点进去了没看到里面有任何说容量相关的东西。没有意义的issue，并不是都是你认为的没有意义，多一句话的事儿，何必那么重的戾气。

**Comment by tiann** [comment]
这不是很正常？微信版本不同，可能界面都不一样。你从来都是站在自己的角度看问题，你不觉得？

你认为我进去看收藏用不了两秒钟，按照模版写说明觉得麻烦，那是为了自己方便。如果你站在我的角度想一下，就会知道我要解决这个问题，的确需要知道更多的信息；但是你并没有。如果你仔细看看issue模版，里面不仅有版本说明，还有复现步骤。

还有，“戾气” 貌似是你先的吧；连几个字都不愿意打，反正我是不想理。算了不扯了。

![image](https://user-images.githubusercontent.com/4233744/42133248-43a60a00-7d59-11e8-9ce7-de0316b14522.png)
