### ISSUE TITLE
Yalp Store 无法下载、更新应用，可能是路径问题

### ISSUE THREAD

**Issue by yylyyl** [android-hacker/VAExposed#290]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

在 Yalp Store 中下载，进度条不走，或者走到接近满时停止不动

## 复现步骤

Yalp Store 中有一个「下载应用到内部存储」设定，是否勾选是两种不同的表现

### 勾选「下载应用到内部存储」

尝试下载任何一个应用，进度条快满时停止不动，logcat 未见有效信息。

### 不勾选「下载应用到内部存储」

此时，「下载目录」可以填写，前缀 ``/storage/emulated/0`` 无法更改，如果填入 ``Download`` 结果为 ``/storage/emulated/0/Download``

进行下载时，进度条不走。

在 logcat 中可以见到这样的字样：

```
06-29 23:32:54.624 23088 24920 I DownloadManagerAdapter: Downloading APK for com.google.android.youtube.tv
06-29 23:32:54.653 23445 23456 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/com.google.android.youtube.tv.20304320.apk
06-29 23:32:54.689 23088 24920 I DownloadManagerAdapter: Download id 10
```

通过 adb shell 可以看到，``/storage/emulated/0/Download`` 目录并不存在：

```
SVP-DTV15:/storage $ ls -la
total 8
drwxr-xr-x  4 root root       120 2018-06-25 17:23 .
drwxr-xr-x 24 root root         0 1970-01-01 08:00 ..
drwx--x--x  4 root sdcard_rw 4096 2015-01-01 00:01 emulated
lrwxrwxrwx  1 root root         7 2018-06-25 17:23 sdcard -> /sdcard
lrwxrwxrwx  1 root root         7 2018-06-25 17:23 sdcard0 -> /sdcard
drwxr-xr-x  2 root root        60 2018-06-25 17:23 self
SVP-DTV15:/storage $ ls emulated/
ls: emulated/: Permission denied
1|SVP-DTV15:/storage $ ls sdcard
Alarms           Android Download Music         Pictures Ringtones     aaa
AllenVersionPath DCIM    Movies   Notifications Podcasts VirtualXposed
```

因为前缀 ``/storage/emulated/0`` 无法修改，下载永远都会失败。

## 环境

机型：Sony Bravia X8566D
系统版本：7.0
ROM版本：SVP4KDTV15_CN-user 7.0 NRD91N.S20 5.381 release-keys
Xposed 插件以及插件版本：FakeGapps 2.0
VirtualXposed版本：0.12.1

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
https://fir.im/2fl4 用这个版本测试一下

**Comment by yylyyl** [comment]
囧，下载不了，达到今日上限了 😢

**Comment by yylyyl** [comment]
使用测试版本确实就可以了 👍

**Comment by tiann** [comment]
IO 重定向的问题，既然解决了我就close了。
