### ISSUE TITLE
能否让我的情迁红包上架这个市场哈 

### ISSUE THREAD

**Issue by lozn00** [android-hacker/VAExposed#291]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
virtualxposed推荐列表希望能推荐一下我的呢，为了提升体验，后期我准备重整模块，只保留qq,然后软件界面设置简化一下。

关于稳定性问题，现在插件是支持virtualxposed和360分身大师x版本了哈。

**Comment by tiann** [comment]
已经添加: https://github.com/android-hacker/VirtualXposed/commit/25179c54e06a41fb74b69c95b860de60da43de07

设置-常用模块  即可看到。

另外提醒一下，在 VirtualXposed 中hook native方法的时候，需要提前加载这个native方法对应的so，不然可能会出现诡异的崩溃。VirtualXposed 无法像Xposed那样修改虚拟机干预 native 方法的执行流程，只能这么做了。

**Comment by lozn00** [comment]
诡异的崩溃我也头疼呀，最近开发新软件总是出现 莫名其妙的信号量11错误，之后我卸载夜神模拟器里面的QQ突然正常了，头疼了。。。

**Comment by lozn00** [comment]
你这个网址是通过git的这个读取显示的？
