### ISSUE TITLE
应用数据备份功能

### ISSUE THREAD

**Issue by qnnnnez** [android-hacker/VAExposed#292]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述

希望能增加一个可以备份应用内部数据的功能，可以在应用管理界面增加导出备份和导入备份两个选项。
如果启用了存储重定向，还可以提供一个选项，在导出备份的时候把重定向的文件也一并导出。

**Comment by tiann** [comment]
#114
