### ISSUE TITLE
File manager

### ISSUE THREAD

**Issue by Scherzhertz** [android-hacker/VAExposed#293]
I need a file manager in virtual xposed , i want to edit some file in the virtual space , i cqnt use es file manager , or any file manager

**Comment by tiann** [comment]
you can use TotalCommander, install it in VirtualXposed, and add a bookmark: /data/data/io.va.exposed

**Comment by Scherzhertz** [comment]
How can i open like android/data/com.tencent.ig in virtual xposed

**Comment by tiann** [comment]
Do you mean /sdcard/Android/data/ ? Just open it as usual.
