### ISSUE TITLE
vivo nex上不能创建快捷图标到桌面

### ISSUE THREAD

**Issue by 154753909** [android-hacker/VAExposed#294]
点击创建无反应。。。微信打开会闪退。但是打开一瞬间立马锁屏可以防止闪退。不知道是不是用了微x模块的原因。。还有就是后台时间长了。微信就自动关闭了。。

**Comment by tiann** [comment]
需要给VXP创建快捷方式的权限。

如果微X不稳定，建议先用别的模块；如微信增强等。
