### ISSUE TITLE
增加类似于阻止运行的特性

### ISSUE THREAD

**Issue by ZYFDroid** [android-hacker/VAExposed#298]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述
为了整治那些国产流氓软件，我把这堆东西全部放进了VirtualXposed(以下简称VX)里面，本来以为可以治理一下这些流氓软件，结果反而为那些流氓软件的自启，关联自启和后台运行提供了保障。我只是刷个贴吧，一会今日头条发来一个新闻，一会微博弹出个消息，我只是想纯粹地刷个贴吧
## 希望的解决方案
增加一个类似于冰箱的功能，可以把一些app拉到这个名单里，然后这个名单里所有APP初次打开VX或重启之后全部被标记为冻结状态，不能自启和后台运行。点击一个APP后该APP解冻，可以和其它app一样运行。再次点击重启之后该名单app全部恢复到冻结状态
## 其他信息
VX的耗电量目前等于五六个流氓软件之和，希望下个版本增加以上功能后能够改善

**Comment by tiann** [comment]
VXP 是用来使用XP的，不是用来整治流氓软件的；有这需求，用冰箱/黑域。
