### ISSUE TITLE
软件后台，没多久就退出了怎么回事

### ISSUE THREAD

**Issue by Sesprie** [android-hacker/VAExposed#301]
## 问题描述

软件后台，没多久就退出了怎么回事

## 复现步骤

打开vx，打开QQ，按下home键，vx已加入系统白名单，
打开系统中的QQ，也加入了白名单，
息屏十来分钟，再打开vx中的QQ，已闪退
打开系统中的QQ，依然正常运行

## 环境

机型：vivo x7
系统版本：android 7.0.0
ROM版本：最终版本Funtouch os 3.0
Xposed 插件以及插件版本：QQ净化
VirtualXposed版本：vx最新版自带

## 补充

请问这是手机的问题吗，如果是，为什么系统自带的软件能够正常后台，vx该加的白名单都加进去了，后台自启，后台高耗电等等，还有一个现象就是，有时候打开vx中的QQ，会黑屏，然后又重启qq，是bug吗，
另外：测试的时候其他的软件没有打开，只开了这两个qq，按理说内存应该是够的

**Comment by ttorange1** [comment]
我用华为 8.0系统，也是一样的问题
网易云音乐，过一会会自动停止播放，有的版本就是黑屏并停止响应，重启vx恢复正常，过一会又如此。
