### ISSUE TITLE
酷安已经解除折叠，求重返

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#305]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
不会再回去了

**Comment by Maolaohei** [comment]
说不定:不知道一天又折叠，还不如不上.

**Comment by Maolaohei** [comment]
作者已经被酷安折叠怕了，都有心里阴影了，至少github不会动不动的就折叠/屏蔽。
