### ISSUE TITLE
Replacement hook calling the original hooked method causes virtualXposed to hang

### ISSUE THREAD

**Issue by akhilkedia** [android-hacker/VAExposed#309]
**Describe the bug**
A replacement hook which calls the original method causes virtualXposed to hang and freeze, and ultimately virtualXposed is killed by Android for not responding.
This hook works perfectly fine with original Xposed.

**To Reproduce**
1. Make an xposed module with this (https://gist.github.com/akhilkedia/ea6350b9e4e5eff2f7f7576f22175416) as the hook code.
2. Install and enable this xposed module into VirtualXposed, then open any hooked app.
3. The app hangs, and virtualXposed is ultimately force closed by android for not responding.

**Expected behavior**
The hooked app opens successfully, and "Finished Invoking original function" is printed to the log.

**Screenshots**
Not relevant, but can supply Screenshots if needed

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser firefox
 - Version Ubuntu version 16.04, firefox version 58

**Smartphone (please complete the following information):**
 - Device: Nexus 6P
 - OS: Lineage OS 14.1 (Based on Android 7.1.2)
 - Browser firefox
 - Version VirtualXposed 0.12.7, firefox version 58

**Additional context**
If you cannot reproduce the error, I can make a repo with full sample xposed module and sample hooked app.

**Comment by tiann** [comment]
#308
