### ISSUE TITLE
Cannot get callback from hooking WebViewClient.onPageFinished()

### ISSUE THREAD

**Issue by akhilkedia** [android-hacker/VAExposed#311]
**Describe the bug**
While hooking into `WebViewClient.onPageFinished()` for app any with `WebView`, the hook callback is never called in VirtualXposed. The callback works in vanilla Xposed.

**To Reproduce**
1. Create a module with the following as the hook code - 
```Java
import android.util.Log;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import de.robv.android.xposed.IXposedHookLoadPackage;
import de.robv.android.xposed.XC_MethodHook;
import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.callbacks.XC_LoadPackage.LoadPackageParam;

import static de.robv.android.xposed.XposedHelpers.findAndHookConstructor;
import static de.robv.android.xposed.XposedHelpers.findAndHookMethod;


public class virtualXposedSample implements IXposedHookLoadPackage {

    public static final HookCallback hookCallback = new HookCallback();

    public void handleLoadPackage(final LoadPackageParam lpparam) throws Throwable {
        Log.i("VirtualXposedSample", lpparam.packageName);
        XposedBridge.log("VirtualXposedSample" + lpparam.packageName);

        // This is to just verify that webviewClient class is indeed instantiated. This callback is successful.
        findAndHookConstructor(WebViewClient.class, hookCallback);
        // This callback is never received
        findAndHookMethod(WebViewClient.class, "onPageFinished", WebView.class, String.class, hookCallback);
    }
}

class HookCallback extends XC_MethodHook {
    @Override
    protected void afterHookedMethod(XC_MethodHook.MethodHookParam methodHookParam) throws Throwable {
        // Just print the name of the method which is hooked
        Log.i("VirtualXposedSample", " Got callback for " + methodHookParam.method.getName());
    }
}
```
2. Install the module into VirtualXposed, enable it in Xposed Installer, Reboot
3. Install any app which has webview - you can use from play store [this app](https://play.google.com/store/apps/details?id=il.co.netix.webviewtest), or you can build [this app](https://github.com/pacificregmi/SimpleAndroidWebViewExample) (While building this app, I had to gradle version in classpath in build.gradle file)
4. Open the page www.github.com
5. The page finishes loading, but no callback comes for `WebViewClient.onPageFinished()`. "Got callback for onPageFinished()" is not printed to log.

**Expected behavior**
Successfully receive callback, like in vanilla Xposed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser firefox
 - Version Ubuntu version 16.04, firefox version 58

**Smartphone (please complete the following information):**
 - Device: Nexus 6P
 - OS: Lineage OS 14.1 (Based on Android 7.1.2)
 - Browser chrome
 - Version VirtualXposed 0.12.7, chrome version 67.0.3396.87

**Additional context**
WebView implementation in Developer Options in Android is set to "AOSP WebView" (The other option, "Chrome Stable", is not selected.)
The "Android System WebView" app in play store is Not installed.
I can provide full sample module and sample hooked app if you cannot reproduce this error

**Comment by tiann** [comment]
I am sorry, it is a defect of VirtualXposed : https://github.com/android-hacker/VirtualXposed/wiki/Difference-between-Xposed-and-VirtualXposed

I have no way to fix it : ( 

Maybe you can try another method to hook?

**Comment by tiann** [comment]
You can hook the constructor of WebViewClient, then you can get all subclass of WebviewClient(subclass's constructor must call super), then you can hook these subclass's onPageFinish.(if it override the method, it cann't be empty)

**Comment by akhilkedia** [comment]
Ah I understand, the problem is that the method `onPageFinished()` is too short?
I'll try to find a workaround.
Thank you for your reply! :)

**Comment by akhilkedia** [comment]
For future reference of anyone else, here is the workaround I am currently using for this - 

Instead of Hooking `WebViewClient.onPageFinished()`, I go up the call stack and am hooking Chromium webview's `WebViewContentsClientAdapter.onPageFinished()`.

The downside of using this approach is that Chrome apk is proguard, so the exact name of function to be hooked needs to be reversed-engineered. This function/class name will also vary between different chromium versions. So the only solution to this is to either host the hooks on some server and keep updating it, or to decompile the chrome-apk on the device itself at runtime to get hook names.

Also, Android <7 and LineageOS use AOSP webview as webview provider and not chromium webview, so that also needs to be hooked.
