### ISSUE TITLE
星之开罗游戏无法运行

### ISSUE THREAD

**Issue by ZxBing0066** [android-hacker/VAExposed#315]
## 问题描述

安装的酷安和星之开罗游戏获取权限都有问题，报错如图：
![image](https://user-images.githubusercontent.com/5652404/43009273-c4af3d36-8c6f-11e8-9316-ef8675e222dd.png)
![image](https://user-images.githubusercontent.com/5652404/43009276-c66c727e-8c6f-11e8-8856-5f84e5ba8ed3.png)

## 复现步骤

酷安：在VirtualXposed中安装后，打开报错，使用XPrivacyLua给酷安读取应用列表权限，重新打开依旧无效。
游戏：在VirtualXposed中安装后打开报错。

## 环境

机型：1加3T
系统版本：氧OS
ROM版本：Android 8.0
Xposed 插件以及插件版本：XPrivacyLua 1.23.17
VirtualXposed版本：最新版0.12.7

## 补充

无

**Comment by tiann** [comment]
酷安可以获取应用列表，但是它的判断逻辑是**少于5个系统应用** 就不给你显示；VXP内部没有系统应用，所以表现是这样。

至于游戏，我不清楚它是个什么情况
