### ISSUE TITLE
如何检测APP是否运行在VirtualXposed中

### ISSUE THREAD

**Issue by zou-xian-liang** [android-hacker/VAExposed#321]
## 场景描述
防止用户利用VirtualXposed的遍历性修改定位，设备码等信息

## 希望的解决方案

希望能给个思路能有效识别APP当前运行环境，防止用户利用软件的便利性，修改设备信息等

**Comment by Maolaohei** [comment]
针对vx
vx环境是不存在通讯录 拨号的
直接检测用户环境是否存在拨号 通信录 系统设置等app，如果不存在，则判断环境存在异常，拒绝服务，就行了。

**Comment by Maolaohei** [comment]
或者想腾讯的微信一样，直接在代码中检测是否存在xposed。

**Comment by zou-xian-liang** [comment]
可以处理打电话的Intent，而且在vx环境中，检测不出来安装了Xposed

**Comment by Maolaohei** [comment]
不，我的意思不是检查xposed的应用，而是检测xposed的运行，部分日厂游戏不是也有检测root 和xposed，有就停止运行的现象。
你可以去看看vx的代码，看看他怎么实现的xposed

**Comment by zou-xian-liang** [comment]
恩，游戏一般是通过自造异常然后通过异常信息来判断是否有Xposed运行；
不过这种方法还是无法检测xv中的Xposed框架

**Comment by Maolaohei** [comment]
如果vx开发者来回答就方便了，如果不回答，就需要要自己研究了，冒昧问一下你们开发的项目是什么？

**Comment by zou-xian-liang** [comment]
内部用的，类似钉钉打卡功能，需要获取设备信息，位置信息等

**Comment by tiann** [comment]
我不会直接回答这个问题。

我能理解你们的场景，并为某些恶意用户提供了便捷的作弊手段表示抱歉。但是，如果所有应用都使用我提供的手段检测VX而拒绝运行，那就没有存在的意义了。

不过你可以按照如下思路进行你们自己的判断：

1. 检测 VirtualApp，网搜一搜就会有很多这种文章，我就不具体举例了。
2. 检测 Xposed 相关类（此方法可能被 Xposed Hider之类的模块绕过，自行处理）。
3. 检测 maps文件。

至于你说的抛异常检测Xposed堆栈，在VX里面是不行的，因为并没有修改 app_process，所以堆栈不会变化。

不知是否能满足你的要求。

**Comment by Maolaohei** [comment]
看开发者解答，我在网上 使用关键词 搜索到了大量关于如何检测自己是否处在vx的文章，看来还是在问问题之前，还是得先搜索一下。

**Comment by zou-xian-liang** [comment]
恩恩，多谢解惑；同时感谢大神分享的牛逼软件。

**Comment by Maolaohei** [comment]
感谢开发者解惑

**Comment by lozn00** [comment]
我觉得商务提问应该给钱，哈哈
