### ISSUE TITLE
源码总是黑屏 但是发布的apk没事 0.12.7版本

### ISSUE THREAD

**Issue by liumengdeqq** [android-hacker/VAExposed#324]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tiann** [comment]
去掉签名验证即可。

**Comment by liumengdeqq** [comment]
verifySignature(env); 是这个么 我已经注释吊了

**Comment by liumengdeqq** [comment]
只有xposed 插件已启动就黑屏
