### ISSUE TITLE
源码编译Xposed 插件启动就黑屏，非Xposed插件没有问题，release版本也没有问题

### ISSUE THREAD

**Issue by liumengdeqq** [android-hacker/VAExposed#325]
1.描述错误描述错误的简洁描述。
  点击xposed插件按钮 出现打开失败
2.重现行为重现行为的步骤：
  (1) 打开软件 安装xposed插件 fakelocation 
  (2)点击fakelocation插件 出现打开失败或是黑屏
3. 预期行为
对您期望发生的事情进行简明扼要的描述。
 (1) 可以进入插件页面
屏幕截图
如果适用，请添加屏幕截图以帮助解释您的问题。
![wechatimg20](https://user-images.githubusercontent.com/3909394/43560963-67bf6e2a-9647-11e8-904e-ed5294be006c.jpeg)
![wechatimg21](https://user-images.githubusercontent.com/3909394/43560972-756d677a-9647-11e8-951b-4f2a3c464388.jpeg)

操作系统：[android]
浏览器[]
版本[8.0]
智能手机（华为荣耀9青春版）：
设备：[华为]
操作系统：[emui8.0]
浏览器[]
版本[8.0]

**Comment by tiann** [comment]
请按照issue模版来，说明详细情况。

**Comment by liumengdeqq** [comment]
已经更新

**Comment by tiann** [comment]
epic版本的问题，不支持8.0.
