### ISSUE TITLE
VT reports a lot of findings

### ISSUE THREAD

**Issue by IzzySoft** [android-hacker/VAExposed#326]
For the latest APK, please check [this report at VT](https://www.virustotal.com/de/file/95907c0afcff1da8c3d743d5dfdcb41c6fef2f2be21e1d1c5cb384131cfedfbd/analysis/1533152877/). Looks pretty bad. Anything you can do about this?

**Comment by IzzySoft** [comment]
OK. The app is removed from [my repo](https://apt.izzysoft.de/fdroid/repo) for now because it doesn't meet the security standard. As soon as some human gets in contact with me and gets the issue solved, it can of course be relisted.

PS: I'm aware it is a bot that closed this. But the issue template isn't fitting this report, so I cannot use it.

**Comment by tiann** [comment]
As i mentioned before: https://github.com/android-hacker/VirtualXposed/issues/10#issuecomment-377295527, I don't want to entangle with the antivirus engine anymore.

And also, VirtualXposed is open source, many malware use the source code to do bad things, which leading to the engine make a false judgment.

**Comment by IzzySoft** [comment]
OK @tiann – thanks and understood. While I usually ignore the few PUP/PUA reports (mostly comming from WhiteArmor and the likes), 16 engines reporting Riskware/Trojans/Banking are hard to ignore and quite unsettling to users. So no bad feelings, but I rather keep it off my repo – though with tears in my eyes.

And yes: malware using it indeed might be bringing "signatures" into the AV databases which then match your app – so it's not that I wouldn't believe you.
