### ISSUE TITLE
epic 没有0.5.9

### ISSUE THREAD

**Issue by liumengdeqq** [android-hacker/VAExposed#327]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
是的，并没有push。如果你是测试用，那个版本已经够用了。
