### ISSUE TITLE
安卓 9 正式版提示框架已安装，但未激活

### ISSUE THREAD

**Issue by Tabll** [android-hacker/VAExposed#330]
## 问题描述

安卓9正式版本，使用0.12.9版本时，显示 Xposed 框架 91 版已安装，但未激活。
日志提示：Cannot read log/data/user_de/0/de.robv...

## 复现步骤

重新安装，清除数据都无法解决

## 环境

机型：Google Pixel 2 XL
系统版本：Android 9
ROM版本：稳定版
Xposed 插件以及插件版本：Xposed Installer 3.1.5, Xposed 框架 91 版
VirtualXposed版本：0.12.9

## 补充
无

**Comment by thekingofcity** [comment]
**复议**
同样问题

机型：Essential Phone PH-1
系统版本：Android 9
ROM版本：稳定版
Xposed 插件以及插件版本：Xposed Installer 3.1.5, Xposed 框架 91 版
VirtualXposed版本：0.12.9

**Comment by ytdttj** [comment]
+1
机型：Google Pixel
系统版本：Android 9
ROM版本：稳定版
Xposed 插件以及插件版本：Xposed Installer 3.1.5, Xposed 框架 91 版
VirtualXposed版本：0.12.9

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/releases/tag/0.13.0

**Comment by SetoKaiba** [comment]
active了但是好像无法联网 @tiann
