### ISSUE TITLE
Android 9.0相关问题

### ISSUE THREAD

**Issue by xausky** [android-hacker/VAExposed#335]
首先感谢作者为这个项目长期的付出。  
我是隔壁Unity模组管理器的作者，我的项目里面使用这个项目作为虚拟环境的引擎，提供对游戏文件修改的免Root解决方案。  
https://github.com/xausky/UnityModManager

## 场景描述

近期我的项目陆续开始有人使用 Android 9，并且开始向我报告一些错误，就是：Uable to parse the package  
我看到新发布的0.13.0版本有对 Android 9 进行适配，于是下载了apk尝试，正常运行，但是当我使用源码编译到我的程序中发现还是有一样的问题。  
后来我发现是源码与apk不一致的原因，apk里面版本是0.13.0，但是源码不管是exposed，还是 tag 0.13.0，还是relases里面的zip包，都是0.12.7版本的，使用这些源码编译的包都问题依旧。

## 希望的解决方案

如果可以的话希望可以放出0.13.0的源码以供使用，谢谢。

## 其他信息

再次感谢作者的辛苦付出。

**Comment by Maolaohei** [comment]
崩坏3模型修改器的作者吗？有辛使用过你的修改器，虽然现在没玩了。

xausky <notifications@github.com> 于 2018年8月13日周一 下午9:51写道：

**Comment by Maolaohei** [comment]
推测开发者想等android p兼容性进一步提升，才会放出vx源码。

**Comment by tiann** [comment]
目前Android 9.0上问题还很多，源码放出去了也基本不能用，等我研究清楚了再说吧

**Comment by xausky** [comment]
恩恩，那我就再等等吧，再次感谢。

**Comment by SetoKaiba** [comment]
Android Pie什么时候能用上，早知道就不升级系统了。。现在的打开程序在联网的地方卡住。。

**Comment by tiann** [comment]
代码已上传，但是可能还会存在很多问题。

**Comment by ghost** [comment]
Android 9，卸载旧版本，安装新版本后 Xposed 直接打不开了

**Comment by SetoKaiba** [comment]
这个问题应该在 0.14.5上修复了；QQ的问题见 #335

所以QQ的问题是还没修复的意思吗？留意后续的意思吗？

**Comment by tiann** [comment]
qq的应该没有

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/releases/tag/0.15.1

**Comment by SetoKaiba** [comment]
@tiann 还是有一些bug，QQ电话无法打开，vxp已经授权所有权限
