### ISSUE TITLE
Android9.0中QQ提示Appid is invaild.

### ISSUE THREAD

**Issue by MlgmXyysd** [android-hacker/VAExposed#339]
## 问题描述
打开qq和登录时提示appid is invaild且无法登录

## 复现步骤
见上

## 环境

机型：Oneplus 6
系统版本：9.0
ROM版本：公测版
Xposed 插件以及插件版本：无
VirtualXposed版本：0.13.0

## 补充
在8.1(0.12.7)时没有此问题。

**Comment by tiann** [comment]
统一到 #335

**Comment by tnti** [comment]
嗯 最新的一加Oneplus5 Android9.0系统中依旧没法双开QQ 装了个太极最新版 不知道是不是那玩意惹事了
 VirtualXposed是0.17.3
