### ISSUE TITLE
0.13.0 普通版使用部分插件闪退但 GameGuardian 版却不会闪退

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#348]
## 问题描述

0.13.0 普通版使用 XprivacyLua 禁止应用权限后，启动应用时提示已停止运行
0.13.0 for GameGuardian 使用 XprivacyLua 禁止应用权限后，应用能正常运行但略感卡顿

## 复现步骤
在 0.13.0 普通版上安装 XprivacyLua 并激活，安装微信并在 XprivacyLua 中禁止微信除录音、录像和拍照外的所有权限，在启动微信的等待界面时系统提示已停止运行
在 0.13.0 for GameGuardian 上安装 XprivacyLua 并激活，安装微信并在 XprivacyLua 中禁止微信除录音、录像和拍照外的所有权限，能正常启动微信并且 XprivacyLua 模块生效，但使用时感觉卡顿

## 环境

机型：Redmi Note 5
系统版本：Android 9.0.0_r1
ROM版本：Pixel Experience 9.0
Xposed 插件以及插件版本：XprivacyLua 1.23.20
VirtualXposed版本：0.13.0 和 0.13.0 for GameGuardian

## 补充

还有一个之前别人提到过的issue，0.13.0 和 0.13.0 for GameGuardian 都不能正常使用 QQ/TIM，点击登录按钮后一直显示登录中，希望能修复

我为了不 root 控制权限把很多应用（如微信，QQ/TIM）装在 VirtualXposed 里，非常感谢作者的作品

**Comment by tiann** [comment]
统一到 #335
