### ISSUE TITLE
开发模块 一直无法正常打断点debugger调试

### ISSUE THREAD

**Issue by 23233** [android-hacker/VAExposed#349]
## 问题描述

 通过WIKI 中的 Utilities For Xposed Module Developer 配置项目后 确实可以重启模块 安装应用 

 但是 每次点击debug 都会先弹出一次apk的安装 会随机被安装在 真机 或 虚拟环境内 (根据当前 如果是真机中 就是安装在真机 如果是在环境内 就是安装在环境内)

 之后会重启环境 然后 会重启微信 但是在这个时候会同步 弹出一次apk的安装 (基本都是安装在真机中)

 在IDE Android Studio debug下  要么会弹出无法连接安装apk 请求重按 要么会无限的等待重连 或者无法连接

 确认在xpinstall中 勾选了模块 不论点击真机中的app 还是 环境中 app 均无法连接上远程调试 

## 复现步骤

 1. git clone https://github.com/Blankeer/WechatBotXposed
 2. 在 Android Studio 载入项目 
 3. 根据 WIKI 更改 Android Studio  Edit Configuration 配置
 4. shift+f9 开始debug 

## 环境

华为emui 8.0
Android Studio

VirtualXposed 0.12.7 GameGuardian

## 补充

 如何才能正常进行打断点进行debug调试呢?

**Comment by tiann** [comment]
并不是“随机安装”，检查一下：

![image](https://user-images.githubusercontent.com/4233744/44735095-138a4f00-ab1e-11e8-8ea9-ee10e1f18e5f.png)

能否debug跟这个无关，直接下断点就OK。

**Comment by 23233** [comment]
@tiann  老哥 你回复的太快了  

最后再请教你一个问题 

我照你这样设置之后 是会安装到真机一个apk 一个在虚拟环境中

但是我点击开虚拟环境中的 apk 不能在 android studio 3 中的 attach debugger 中找到包名 

点开真机环境的apk 就可以找到 

懵逼了 到底怎么调试啊 

是点开真机环境吗?

**Comment by tiann** [comment]
不是，首先你得设置下as让它不要自动安装。其次，你得attach双开的那个进程，而不是原app进程。

**Comment by 23233** [comment]
@tiann 这是我的as debugger 配置

![tim 20180905224151](https://user-images.githubusercontent.com/12870070/45100900-ec0a3680-b15c-11e8-8e3c-847262b1bfee.png)

翻遍了google 实在木有找到 如何让as不自动安装 

望老哥能指点迷津  十分感谢!

**Comment by tiann** [comment]
![image](https://user-images.githubusercontent.com/4233744/45131098-06c0c780-b1be-11e8-91ec-5dc8c26b0366.png)
![image](https://user-images.githubusercontent.com/4233744/45131114-1a6c2e00-b1be-11e8-8e10-139266a4c6e9.png)
![image](https://user-images.githubusercontent.com/4233744/45131118-1fc97880-b1be-11e8-9c67-94891c41fed6.png)

这样的话，就不会自动安装。

**Comment by lly835** [comment]
如何快速的把apk安装到virtual xposed里呢？

**Comment by RainUUU** [comment]
最近也碰到了断点调试问题，attach 插件进程， 插件之外的代码是可以断点的，但是插件里面的hook代码无法设置断点。 不知道如何处理

**Comment by magicxiaobao** [comment]
> 不是，首先你得设置下as让它不要自动安装。其次，你得attach双开的那个进程，而不是原app进程。

请问下双开的那个进程如何找到名称呢？能发一个具体的命令例子吗

**Comment by chenxinxun** [comment]
最新版本如果是支持64位 需要将 io.va.exposed.CMD 改成 io.va.exposed64.CMD
