### ISSUE TITLE
Android 9 无法启动 Xposed Installer

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#356]
## 问题描述

- Android 9，VirtualXposed 0.14.0 无法启动 Xposed Installer
- Android 9，VirtualXposed 0.13.0 没有问题
- Android 8.1.0，VirtualXposed 0.14.0 没有问题

## 复现步骤

- Android 9 打开 VirtualXposed 0.14.0 后，点击 Xposed Installer 卡在启动界面

## 环境

机型：Redmi Note 5
系统版本：Android 9
ROM版本：Pixel Experience
Xposed 插件以及插件版本：无
VirtualXposed版本：0.14.0

## 补充

- ### **希望作者能解决一下 Android 9 上在 VirtualXposed 中 QQ/TIM 能打开但不能登录，提示无网络的问题，谢谢**

**Comment by tiann** [comment]
这个问题应该在 0.14.5上修复了；QQ的问题见 #335 

这个先关了
