### ISSUE TITLE
能否增加“自动检查更新”的开关

### ISSUE THREAD

**Issue by tookdes** [android-hacker/VAExposed#358]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

VX 用于自动化测试流程。每次有更新，流程都会被弹出窗口打断。误事好几次了。

## 希望的解决方案

当然是可以在流程里每次去点击取消，但是按照一般 APP 的做法，还是建议增加“自动检查更新”的开关。

## 其他信息

无

**Comment by tiann** [comment]
不可以。VirtualXposed 目前还需要用户做充分测试，如果加上这个开关；升级率会很低。

你可以升级到最新版来做自动化测试。
