### ISSUE TITLE
Pixel 2 with Android 9.0， 微信 6.6，微x模块不能使用

### ISSUE THREAD

**Issue by xyou365** [android-hacker/VAExposed#360]
## 问题描述

我是Pixel 2，刷的 Android 9.0，还没root想尝试免root下怎么玩Xposed。
现手机装的是微信 6.6，微x模块各个版本都尝试了，不能使用。开了微x后微信就不能开启。

## 复现步骤

不装微x模块的情况下，微信可以双开。装了以后，微信便打不开。然后微x那边的管理给的回复是，
![](https://www.gfan.loan/wp-content/uploads/2018/09/20180904104546.jpg)
想用，但是作为渣渣用户，怪自己没用不会自行解决，过来PR下看下大佬们有没有解决方案。
## 环境

机型：Pixel 2
系统版本：Android 9.0
ROM版本：稳定版
Xposed 插件以及插件版本：微x模块31_1.22
VirtualXposed版本：0.14.6

**Comment by tiann** [comment]
装回 8.x，9.0系统目前不完善也是正常。https://github.com/android-hacker/VirtualXposed/issues/335
