### ISSUE TITLE
Spoof prop values to improve compatibility

### ISSUE THREAD

**Issue by mo123** [android-hacker/VAExposed#361]
To be able to change sensitive props with a built-in setting
https://www.didgeridoohan.com/magisk/MagiskHideMore

To be able to change values like this module does.
https://github.com/bigsinger/AndroidIdChanger
Or this one that can load different values automatically
https://github.com/pbombnz/Spoof-My-Device
Both above modules don't work in VirtualXposed correctly, they are missing prop fields and don't support Nougat 7.1, Oreo 8.1 devices. After enabling these modules, opening an app in VirtualXposed would just quit that checks prop values.

So some built-in setting would work better or if someone can recommend an Xposed module that can actually work like Prop-Config but for Xposed - https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config

**Comment by tiann** [comment]
You can use this Xposed module: https://github.com/kingsollyu/AppEnv-Kotlin
