### ISSUE TITLE
基于Web* 技术的应用运行效率很差

### ISSUE THREAD

**Issue by 404neko** [android-hacker/VAExposed#362]
比如html5app 这种混合APP
还有React

有什么改进思路么

我可以贡献相关的代码

**Comment by tiann** [comment]
有相关数据说明么？

**Comment by 404neko** [comment]
@tiann 
比较明显的例子是 去哪儿APP
每次点击后需要等待30 秒以上UI 才会更新
但是在宿主机上没有这种问题

**Comment by tiann** [comment]
每次都这样，还是只有安装之后第一次？

**Comment by 404neko** [comment]
@tiann

每次都是这样的
