### ISSUE TITLE
安卓9.0 网易云音乐在VXP内无法打开

### ISSUE THREAD

**Issue by shanligang1017** [android-hacker/VAExposed#365]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
安卓9.0 网易云音乐在VXP内无法打开

## 复现步骤

应用为复制安装，打开云音乐出来如下提示，之后弹出来的权限要求全给
![screenshot_20180906_083344_io va exposed](https://user-images.githubusercontent.com/28751979/45128786-75982380-b1b2-11e8-9fb4-33498c3fe93f.jpg)

但是最后卡在如下图，过一会就VXP闪退
![screenshot_20180906_084229_io va exposed](https://user-images.githubusercontent.com/28751979/45128787-75982380-b1b2-11e8-8520-f20efc2358fc.jpg)

## 环境

机型：华为mate10 全网通
系统版本：安卓9.0
ROM版本：EMUI9.0  
Xposed 插件以及插件版本：云音乐5.5.0
VirtualXposed版本：0.15.1

## 补充
同样微信复制可以正常打开，不知道大神有啥解决方法，最好哪里设置下就能解决，谢谢！

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by shanligang1017** [comment]
补充下，VXP还未装任何插件

**Comment by Seumi** [comment]
同样的问题，一加6，安卓9.0，装了大喇叭，一直在opening

**Comment by shanligang1017** [comment]
看来是9.0的通病，可能跟9.0权限机制有关系

**Comment by cingneimaa** [comment]
android8.0  三星s8+ 网易云5.5 vxp0.15.1  同样打不开   且旧版本网易云从vxp取消保守模式的版本开始就一直很容易被杀（播放歌曲   然后打开几个app或者网页   或者什么也不干等一会也可能被杀）（没有黑阈 手机智能管理器白名单  进程白名单）

**Comment by haibugouing** [comment]
S9一样，新版网易云一播放歌曲 VXP就停止响应  。还有  网易云使用一段时间后  突然播放停止。这个是老问题了（无任何插件）

**Comment by Andersorz** [comment]
Mix2s，MIUI10开发版，9.0，同样的问题

**Comment by shanligang1017** [comment]
今天回退系统，发现8.1这个云音乐版本一样打不开，下个4.3.1版本可以用

**Comment by Criogaid** [comment]
这里8.1也是打不开的

**Comment by shanligang1017** [comment]
> 这里8.1也是打不开的

8.1用云音乐的历史版本，我4.3.1的云音乐可以，新版和旧版云音乐的权限获取方式有点不一样，新的打开的时候会提示什么要先获取权限的对话框

**Comment by Criogaid** [comment]
> > 这里8.1也是打不开的
> 
> 8.1用云音乐的历史版本，我4.3.1的云音乐可以，新版和旧版云音乐的权限获取方式有点不一样，新的打开的时候会提示什么要先获取权限的对话框

我尝试旧版本云音乐的时候会导致直接无法播放 下载也没有存储路径 可能是因为降级安装了 晚点我尝试全新安装

**Comment by derleythiago** [comment]
Quero estalar

**Comment by shanligang1017** [comment]
这几天又升级了9.0，用旧版本的云音乐也没用，8.1用旧版本的云音乐还可以

**Comment by shanligang1017** [comment]
刚更新了vx1.6.0问题依旧，希望大神能够查下问题谢谢！

**Comment by shanligang1017** [comment]
用了最新的太极也一样打不开，闪退

**Comment by yhf7952** [comment]
可能是安卓9.0的问题
我的是企业微信一直opening…
启用模拟位置就打不开，不启用正常

**Comment by 2767321434** [comment]
怀疑是这个文件里的VirtualApp\lib\src\main\jni\Foundation\VMPatch.cpp
下面这段代码的问题
void disableJit(int apiLevel) {
#ifdef __arm__
    void *libart = fake_dlopen("/system/lib/libart.so", RTLD_NOW);
    if (libart) {
        // disable profile.
        void *processProfilingInfo = NULL;
        const char *processProfileInfoFunc =
                apiLevel < 26 ? "_ZN3art12ProfileSaver20ProcessProfilingInfoEPt" :
                "_ZN3art12ProfileSaver20ProcessProfilingInfoEbPt";
        processProfilingInfo = fake_dlsym(libart, processProfileInfoFunc);
        ALOGE("processProfileingInfo: %p", processProfilingInfo);
        if (processProfilingInfo) {
            MSHookFunction(processProfilingInfo, (void*)processNothing, (void**)&orig_ProcessProfilingInfo);
        }

        // disable jit
        void *compileMethod = NULL;
        compileMethod = fake_dlsym(libart,
                                   "_ZN3art3jit3Jit13CompileMethodEPNS_9ArtMethodEPNS_6ThreadEb");
        ALOGE("compileMethod: %p", compileMethod);
        if (compileMethod) {
            MSHookFunction(compileMethod, (void*) compileNothing, (void**) &orig_CompileNothing);
        }
    }
#endif

**Comment by marcycrass** [comment]
Pls help. How can I run Virt xposed under android 9.I will much appreciate it
Many thanx
