### ISSUE TITLE
Mix2几乎无法正常使用

### ISSUE THREAD

**Issue by rainywan** [android-hacker/VAExposed#368]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

第一次尝试用VXP，感觉状况百出啊，不知道是否只有我一个人这样，搜了一下issue好像也没类似的。
个人的核心需求只有微信群分组，按时间顺序先后尝试了“微X助手”、“微信分组模块”、“微信群消息助手”、“微信巫师”，都有问题
另外xp里的模块也无法卸载，点击卸载后，空有toast弹出

## 复现步骤

微X助手开启分组后，图片无法发送成功（感叹号），重启后，微信闪退，再也进不去了
然后用了微信分组模块，闪退
微信群消息助手，无效果
微信巫师，无效果
最后重新尝试用微X助手，发现不会再闪退了，模块已加载，但不运作（右上角无设置图标）

## 环境

本人机型mix2 开发版，Android8.0.0，微信6.6.7，vxp、xp和模块都是用的最新发布版。

## 补充

我只是希望能搞个微信分组...
如果有能实现稳定微信分组的办法，比如用某版本的微信或模块，之类的，请告诉我

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
把不用的模块关了，一个个试，这些模块我都没用过，可能支持不好。

**Comment by rainywan** [comment]
您好，我确实是一个个去试的，如上所述基本都无法使用。
我个人怀疑是环境污染的问题，微X模块 崩溃之后，环境污染导致后面的模块都无法正常使用。
我其实最想知道的是，为什么我无法卸载模块呢？
点击卸载后，空有toast弹出，然而软件没卸载

**Comment by rainywan** [comment]
每个模块我都是单独运行的

**Comment by tiann** [comment]
1. 微x模块有可能写坏数据库，一旦出现这种情况；即使不开启任何模块都会闪退，只能清除数据才能解决。
2. 强制停止vxp之后应该可以看到卸载的结果。
