### ISSUE TITLE
在android模拟器中安装virtual xposed后，打开xposed install后显示黄色警告，“Xposed 框架91版已安装，但未激活。请检查日志的详细信息”

### ISSUE THREAD

**Issue by nbalichaoq** [android-hacker/VAExposed#369]
在android模拟器中安装virtual xposed后，打开xposed install后显示黄色警告，“Xposed 框架91版已安装，但未激活。请检查日志的详细信息”。打开日志后只有一条"Cannot read log/data/data/de.robv.android.xposed.installer/log/error.log: open failed: ENOENT (No such file or directory)"。
         在模块页面中，也有警告“最新版Xposed当前未激活。你是否已安装框架并重启"。因为是在Virtual xposed里操作的，Version 89 的framwrok已经自动安装好了。
          我在android studio自带的模拟器和网易mumu模拟器中都尝试了，还是一样的问题。模拟器都是andriod6.0的，x86构架。
           请问如何解决？谢谢

**Comment by lantiao** [comment]
Cannot read log/data/data/de.robv.android.xposed.installer/log/error.log: open failed: ENOENT (No such file or directory)
