### ISSUE TITLE
在android模拟器中安装virtual xposed后，再打开xposed install后显示黄色警告，“Xposed 框架91版安装，但未激活。请检查日志的详细信息”。

### ISSUE THREAD

**Issue by nbalichaoq** [android-hacker/VAExposed#370]
![screenshot_1536242217](https://user-images.githubusercontent.com/15140799/45162102-cc881200-b21f-11e8-8958-50f1e46428b2.png)
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

   在android模拟器中安装virtual xposed后，打开xposed install后显示黄色警告，“Xposed 框架91版安装，但未激活。请检查日志的详细信息”。打开日志后只有一条"Cannot read log/data/data/de.robv.android.xposed.installer/log/error.log: open failed: ENOENT (No such file or directory)"。
        在模块页面中，也有警告“最新版Xposed当前未激活。你是否已安装框架并重启"。因为是在Virtual xposed里操作的，Version 89 的framwrok已经自动安装好了。
        我在android studio自带的模拟器和网易mumu模拟器中都尝试了，还是一样的问题。模拟器都是andriod6.0的，x86构架。
        请问如何解决？谢谢

## 复现步骤

1.打开android模拟器；
2.在模拟器中安装Virtual xposed apk
3.打开virutal xposed等待framword自动安装后即出现上述情况

## 环境

机型：
系统版本：android6.0
ROM版本：模拟器镜像
Xposed 插件以及插件版本：verision 89
VirtualXposed版本：0.15.1和0.12.7（情况一样）

**Comment by tiann** [comment]
不支持x86
