### ISSUE TITLE
Random package name

### ISSUE THREAD

**Issue by mo123** [android-hacker/VAExposed#371]
**Is your feature request related to a problem? Please describe**.
Not a current problem, a future one.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
Some apps installed in Android will detect the package name of VX in future and then won't start.

**Describe the solution you'd like**
To add a new setting so VX can change it's package name to a random one or clone itself to a random package name and remove the old one that will be different on every system.
So a hardcoded value to check that VX is installed by apps won't work.

**A clear and concise description of what you want to happen.**
As above

**Describe alternatives you've considered**
None

**A clear and concise description of any alternative solutions or features you've considered.**
None

**Additional context**
N/A

**Add any other context or screenshots about the feature request here.**
N/A

**Comment by tiann** [comment]
Sorry, I won't do that.
