### ISSUE TITLE
升级到0.15.1版本 清除数据 再启应用打开失败

### ISSUE THREAD

**Issue by WangJarvis** [android-hacker/VAExposed#375]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

 长按应用点击【清除数据】，长按应用点击【强制停止】，启动应用打开APP失败

## 复现步骤
 长按应用点击【清除数据】，长按应用点击【强制停止】，启动应用打开APP失败
必现

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
说了这么多，跟白说一样。

什么应用打不开？之前的版本能打开么？

**Comment by WangJarvis** [comment]
非常抱歉，我描述的不清楚，我拍了个视频给你看下。使用0.13这个版本没有发现这个问题，0.14和0.15都会有这个问题。我发现大部分应用通过这种操作都会出现这个情况（摩拜单车）[演示视频](https://v.youku.com/v_show/id_XMzgxNTk0MDg4OA==.html?spm=a2h3j.8428770.3416059.1)

**Comment by lki2019** [comment]
是的，以前的版本 清除数据 比如一些需要登录输入账号的app  输入一次账号后 以后就是自动登录
清除了数据后，就是需要再次输入账号·就类似这样的

现在的版本 清除数据后，打开app失败了就

**Comment by lki2019** [comment]
在说一个和本主题无关的问题

1.更新新版本后，之前在虚拟机里安装过的app都没了···还需要从新再安装，这个问题是不是无解呢？在更新了新版本后 之前安装过的应用还保留下来

2.最近这2个版本，安装后，本机的所有app都出现在虚拟机里了，
我觉得不是很方便，以前的版本 安装虚拟机后，进入桌面是空的 这样安装新的应用可以一目了然
目前仍在0.14.0版本 这个版本安装后 本机的所有app不会出现在桌面

**Comment by tiann** [comment]
@lki2019 
1. 升级系统之后app数据都在，需要重新安装；可以解决，但是没时间。
2. 升级到 0.15.1，关闭高级设置中的桌面功能即可。

这个问题我已经知道咋回事了，下次再解决。

**Comment by lki2019** [comment]
@tiann 
好的，期待新版本！感谢！
