### ISSUE TITLE
求正确编译方法

### ISSUE THREAD

**Issue by yuninf** [android-hacker/VAExposed#376]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

下载的apk，能正常运行自己写的hook。

而用下载（或Git）的源码自己编译，则不能正常运行hook。

打开XposedInstaller 中的日志，查看报错：
module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled

所以我想问下是不是哪个步骤错了

## 复现步骤

下载源码，AS打开VirtualApp目录，菜单Build->generate signed apk

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

这是我的代码
            XposedHelpers.findAndHookMethod("com.alipay.mobile.payee.ui.PayeeQRSetMoneyActivity",paramClassLoader,"onCreate", Bundle.class,new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {
                    XposedBridge.log("======运行到创建订单=====");
                    Object amount_input = XposedHelpers.findField(param.thisObject.getClass(),"b").get(param.thisObject);
                    Object mark_input = XposedHelpers.findField(param.thisObject.getClass(),"c").get(param.thisObject);
                    XposedHelpers.callMethod(amount_input,"setText","0.01");
                    XposedHelpers.callMethod(mark_input,"setText","skycn");
                    ((Button)XposedHelpers.findField(param.thisObject.getClass(),"e").get(param.thisObject)).performClick();
                }
            });

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
自己编译的版本 epic 版本过低

**Comment by Rosslrs** [comment]
请问楼主问题解决了吗？

**Comment by yuninf** [comment]
没有，不知道怎么更新epic

**Comment by tabs** [comment]
tiann大大怎么不同步更新vx中的epic
