### ISSUE TITLE
像BSD一样脱离https://github.com/asLody/VirtualApp ？

### ISSUE THREAD

**Issue by zaoqi** [android-hacker/VAExposed#378]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案
 完全重写？
(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
意义是什么？

**Comment by zaoqi** [comment]
不被它的license限制。

**Comment by tiann** [comment]
没那个时间和精力，对我也没什么好处。

**Comment by tiann** [comment]
#138
