### ISSUE TITLE
在运行一段时间后virtualxposed中的模块会自动退出

### ISSUE THREAD

**Issue by snfnwgi** [android-hacker/VAExposed#379]
## 问题描述

在运行一段时间后virtualxposed中的模块会自动退出，退出时间不太确定，APP也做很多保活方案，但还是会自动退出，权限等一些相关配置也全配置了
## 复现步骤

 不能稳定复现
## 环境

机型：
小米5a
系统版本：
7.1.2
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
自己用的插件
VirtualXposed版本：
0.14.6

**Comment by tiann** [comment]
玄学问题，没法解决。
