### ISSUE TITLE
youtube中音量键导致的系统崩溃 及 yalp/play store无法装应用

### ISSUE THREAD

**Issue by swearofwind** [android-hacker/VAExposed#381]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

（请尽量详细地描述你遇到的问题）

youtube中音量键导致的系统崩溃 及 yalp/play store无法装应用

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

**手机状况**：无root，无xposed，无解锁
**总体情况**：安装vxp后，往里面装了microG谷歌套件，并通过ApkPure在vxp中安装了google play及youtube

### **情况一**：
youtube中播放视频时按音量键会导致系统崩溃
**表现状况**：蓝底，系统正在优化设置，然后就自动重启了，没有出现关机开机动画，只是那一幕之后直接黑屏，一段时间后，就出现了系统开机之后的界面（屏幕解锁界面，无开机动画）
    
**已知情况**：
>       1. youtube 中无视频播放时按音量键不会崩溃
>       2. youtube 中有视频播放时按音量键一定会崩溃，已测试三次，均为如此
>       3. virtual xposed 桌面中按音量键正常
>       4. 其他具有音频视频播放的app中未测试按音量键
>       5. 崩溃那一幕无法截屏

### **情况二**

**大致描述**： 在yalp与play store中无法安装app
**vxp环境情况**：经过系统的advanced setting中安装的microG，并自己安装了一些必要的组件（详见下方xposed安装的软件）
**谷歌套件情况**：已登录自己的谷歌账号，且youtube， play store正常打开，在微信中能正常使用google pay付费购买wechatout余额。基本上可认为谷歌套件运行一切正常
**具体表现**：

play store中：
> 1. 下载应用，会一直显示downloading，并没有下载进度条显示出来
> 2. 通过流量监控，可以发现已经有在下载，且一段时间后无下载流量，可以认为后台已下载完成
> 3. 有跑流量时在状态栏下拉能发现下载进度条，通知里的进度条跑完后消失，且大流量下载也随即停止
> 4. 在这之后， 没有任何安装迹象，且play中一直显示downloading

yalp store中：
> 1. 选择好应用后，点击download，进度条有在走，流量也有在跑
> 2. 下载进度只剩最后一点点的时候，流量没在跑，就这样了，没有任何安装对话框弹出
> 3. 点击download旁边的三个点，选择manual download，也是这种情况

### 已做的努力
1. 设置yalp中设置下载后不删除安装包，且下载到Download文件夹下，但是下载到最后一点点的时候无法继续下载完成，使用文件管理器，没发现有安装包存在
2. 在vxp中对yalp及play设置了redirect storage，也无法解决上述问题
3. 已知play正常下载时，play中肯定会有下载进度显示，但vxp中的Play却是一直显示download，没有进度条显示。

## 环境

机型：
系统版本：安卓7.1.2
ROM版本：海信A2T  L1413.6.10.01.00
Xposed 插件以及插件版本：Version 89 (3.1.5)  
已装Xposed插件：`DisableFlagSecure`   `FakeGapss`  `XposedGmsCoreUnifiedNlp`  `XposedUnifiedNlp`  `XPrivacyLua`
VirtualXposed版本：0.14.5

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by peter17ji** [comment]
TCL Y660 安卓7.1也有这个问题，怀疑安卓7.1类原生系统普遍有这个问题
