### ISSUE TITLE
Amazon Prime Video tablet app support

### ISSUE THREAD

**Issue by mo123** [android-hacker/VAExposed#387]
**Describe the bug**
Amazon Prime Video TV app doesn't work on lots of AndroidTV devices.
You also can't use Amazon Prime tablet app since it checks for ui television and television permissions and if present refuse to work.

**To Reproduce**
1. In VE install Amazon Prime Video tablet app.
After you play a video it will crash.

**Expected behavior**
Playback should work after choosing a video.

**Screenshots**

**Desktop (please complete the following information):**
Android Nougat/Oreo

**Smartphone (please complete the following information):**

**Additional context**
If VirtualXposed can spoof the framework to believe it's a normal ui instead of tablet ui and also remove television permission, then Amazon Prime Video tablet app should work.
Maybe an extra setting inside VirtualXposed to install Amazon Prime Video and make it work?
It will help users that have AndroidTV on their devices and that can't use the AndroidTV app since it's not compatible with their devices, the tablet app can play video but need different ui and permissions which VE might be able to provide.

**Comment by tiann** [comment]
The main goal of VirtualXposed is to use Xposed, it is not an environment to hook or spoof anything. Maybe i can realize that, but is not my purpose.
