### ISSUE TITLE
框架内的APP不能接收到ACTION_CLOSE_SYSTEM_DIALOGS系统广播

### ISSUE THREAD

**Issue by hekbobo** [android-hacker/VAExposed#391]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

我尝试在开发xposed模块，用vxp测试的时候发现框架内的APP不能接收到ACTION_CLOSE_SYSTEM_DIALOGS系统广播，
测试了ACTION_SCREEN_OFF是可以的，是否对ACTION_CLOSE_SYSTEM_DIALOGS做了特殊处理呢？

## 复现步骤
1. 普通APP注册ACTION_CLOSE_SYSTEM_DIALOGS监听广播
2. 克隆到vxp中
3. 启动APP，按home键，APP中无法收到ACTION_CLOSE_SYSTEM_DIALOGS广播，

## 环境

机型：小米
系统版本：10 8.8.9
ROM版本：（7.1.1）
Xposed 插件以及插件版本：
VirtualXposed版本：89

## 补充

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by liujianying** [comment]
我也遇到这个问题,无法获取

**Comment by liujianying** [comment]
问题已经解决,需要修改SpecialComponentList类添加下        SYSTEM_BROADCAST_ACTION.add(Intent.ACTION_CLOSE_SYSTEM_DIALOGS)
就可以了
