### ISSUE TITLE
源码无法编译通过，版本为0.15.1，报错提示为 laucher项目找不到，看到下laucher下面只有一个文件。

### ISSUE THREAD

**Issue by opperliu** [android-hacker/VAExposed#395]
## 问题描述

源码无法编译通过，版本为0.15.1，报错提示为 laucher项目找不到，看到下laucher下面只有一个文件。

## 复现步骤
1、下载的源码包
2、解压源码包
3、用android studio 打开包里边的项目。
4、编译。 

## 环境

机型：
系统版本：win10
ROM版本： windows
Xposed 插件以及插件版本：0.15.1
VirtualXposed版本：0.15.1

## 补充

源码无法编译通过，版本为0.15.1，报错提示为 laucher项目找不到，看到下laucher下面只有一个文件。

**Comment by tiann** [comment]
wiki 看了吗？
