### ISSUE TITLE
大佬q++可否上架？另外情迁抢包可以下架了，因为已经没维护了哈。

### ISSUE THREAD

**Issue by lozn00** [android-hacker/VAExposed#400]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述
下载地址
http://repo.xposed.info/module/cn.qssq666.q.plus
此软件只针对qq进行了增加，配合机器人可以实现禁言、踢人、发图片、改名片、发卡片消息，插件功能。。
## 其他信息
目前应该稳定性比情迁强包抢了，现在改为严谨模式，之前的那种方式乱七八糟自己都糊涂了，现在只要任何逻辑出问题直接抛出异常，这样也不会导致整个程序 so崩溃啥的。
而且加载路径固定，是根据被hook的包名进行查询，得到so路径，然后把 q++自己的这个so拷贝过去，而且加载的过程中不会跨应用加载其他应用so,之前的问题大部分是因为重复加载多次，导致，现在不存在这个问题了，就算复制失败， 复制使用的方法对于非root机使用java方式复制，所以应该是没什么问题的。

(其他你认为有用的信息)
目前hook似乎出现了一些和正常root机不一样的症状，导致q++某些版本 的版本号的代码初始化没调用 ，尴尬 - -

**Comment by tiann** [comment]
fixed
