### ISSUE TITLE
hook 淘宝偶尔闪退

### ISSUE THREAD

**Issue by gaoyucindy** [android-hacker/VAExposed#401]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
自己开发的模块，主要hook淘宝搜索结果页，正常xposed未出现闪退，vxp中一台米6 miui9未出现闪退，一台mix miui10偶尔出现卡死然后闪退

## 环境
机型：小米mix 
系统版本： android 8.0.0
ROM版本：miui10 8.9.6开发版
Xposed 插件以及插件版本：自己开发的插件
VirtualXposed版本：0.15.1

## 补充

https://github.com/gaoyucindy/test/blob/master/log.txt
日志

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by liujianying** [comment]
我也出现这个问题,应用hook 一段时间,会闪退,特别是android系统8.0.0以上

**Comment by gaoyucindy** [comment]
试了魅族16x不会闪。。

**Comment by tiann** [comment]
能否提供一下被Hook的函数原型，以及对应设备的 libart.so 文件(adb pull /system/lib/libart.so) ？

**Comment by gaoyucindy** [comment]
hook的是淘宝的recyclerview.adapter 的 bindViewHolder  getItemData(淘宝adapter自己定义的方法)这俩，只hook不实现任何方法也有会几率蹦
https://github.com/gaoyucindy/test/blob/master/libart.so

**Comment by tiann** [comment]
fix in newer epic.

**Comment by zhonghuagunwnag** [comment]
能给发个hook淘宝搜索页的demo吗

**Comment by zhonghuagunwnag** [comment]
923613093@qq.com
