### ISSUE TITLE
使用0.15.1源码编译的VX   HOOK支付宝H5RpcUtil.rpcCall报错

### ISSUE THREAD

**Issue by tabs** [android-hacker/VAExposed#408]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

最近想做一个蚂蚁森林自动收能量的xposed插件，插件在xposed测试可以
使用0.15.1release版本的VX并没有发生这个错误，正常使用。

但是我编译VX  0.15.1release 发布页面版本的源代码使用就会报错

编译时候 源码两处《君子坦荡荡，小人常戚戚》代码控制已经注释
既然发布版本能用，源码也一样怎么会出现你发布的那个能用，我自己编译的就不行了呢？
发布版本   是否在源码其他地方有限制呢？
另外会不会是那个lib  版本里面的  exposed.version 、epic 、exposed依赖版本过于陈旧呢？
这个问题困扰了我好几天啦，求大佬解疑。

## 复现步骤

点击进入蚂蚁森林页面

## 环境

机型：小米8
系统版本：8.1.0
ROM版本：开发版本MIUI10
Xposed 插件以及插件版本：自己做的
VirtualXposed版本：0.15.1

## 补充

hook的办法参考
[Android支付宝蚂蚁森林能量自动收取插件开发原理解析 ](https://www.52pojie.cn/forum.php?mod=viewthread&tid=794312&fromguid=hot&from=timeline)

错误日志如下
09-28 16:31:24.360 I/DexposedBridge( 4741): java.lang.reflect.InvocationTargetException
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at java.lang.reflect.Method.invoke(Native Method)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at me.weishu.epic.art.method.ArtMethod.invokeInternal(ArtMethod.java:262)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at me.weishu.epic.art.method.ArtMethod.invoke(ArtMethod.java:248)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.taobao.android.dexposed.DexposedBridge.handleHookedArtMethod(DexposedBridge.java:260)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at me.weishu.epic.art.entry.Entry.onHookObject(Entry.java:69)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:186)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.nebulabiz.rpc.H5RpcUtil.rpcCall(H5RpcUtil.java:44)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.nebulabiz.provider.ao.run(H5SimpleRpcProviderImpl.java:36)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:42)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:98)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.framework.service.common.threadpool.TaskFactory$DelayableRunnable.run(TaskFactory.java:59)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at java.lang.Thread.run(Thread.java:764)
09-28 16:31:24.360 I/DexposedBridge( 4741): Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [1001] : 拒绝访问。
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializer.parser(JsonDeserializer.java:38)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.common.rpc.RpcInvoker.processResponse(RpcInvoker.java:215)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:154)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:67)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at $Proxy69.executeRPC(Unknown Source)
09-28 16:31:24.360 I/DexposedBridge( 4741): 	at com.alipay.mobile.nebulabiz.rpc.H5RpcUtil.rpcCall(H5RpcUtil.java:189)

**Comment by tiann** [comment]
是的，epic的版本过旧。

**Comment by tabs** [comment]
大佬为什么不在gradle配置文件里配置更新呢
