### ISSUE TITLE
VirtualXposed 编译运行后崩溃

### ISSUE THREAD

**Issue by qiang** [android-hacker/VAExposed#410]
## 问题描述

按照 [wiki How to compile ](https://github.com/android-hacker/VirtualXposed/wiki/How-to-compile)中的方式编译运行后，并且注释掉了签名验证，但是仍然出现崩溃。

经过调试发现是由一行代码引起的，但是不知道为啥？

主要是在 NewHomeActivity 中调用 VAVersionService.checkUpdate(...)方法引起的，代码如下：

```
    public static void checkUpdateImmediately(Context context, boolean showTip) {
        Bundle bundle = new Bundle();
        bundle.putBoolean(KEY_SHOW_TIP, showTip);

        VersionParams.Builder builder = new VersionParams.Builder()
                .setRequestUrl(CHECK_VERION_URL)
                .setShowDownloadingDialog(false)
                .setParamBundle(bundle)
                .setService(VAVersionService.class);

        //这行代码会引起程序崩溃
        AllenChecker.startVersionCheck(context, builder.build());
    }
```

## 复现步骤

安装运行之后就会崩溃

## 环境

机型：
系统版本：Android 8.1.0 
ROM版本：ColorOS V5.0 
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
你跟进去看看不就知道了

**Comment by yecw** [comment]
注釋的這一行解決了問題，不進行版本檢測
