### ISSUE TITLE
Downloading http://dl.xposed.info/repo/full.xml.gz failed: 301 (Moved Permanently),  Help me,  plz share +916353583120

### ISSUE THREAD

**Issue by naman8485** [android-hacker/VAExposed#413]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260106-b825f500-c4ff-11e8-9639-10a4b22ed22b.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260119-ddb2fe80-c4ff-11e8-9393-c199d53dfc28.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260128-fe7b5400-c4ff-11e8-866b-ec163bfc6d88.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260132-0dfa9d00-c500-11e8-803c-d720f5991628.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260136-15ba4180-c500-11e8-8a9a-01105e391e85.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260143-413d2c00-c500-11e8-874e-8d4e3c96fc5d.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260144-413d2c00-c500-11e8-934e-213df57c80f8.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260145-41d5c280-c500-11e8-87ec-543133eaeb06.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260146-41d5c280-c500-11e8-913f-52880df9c8d6.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260147-41d5c280-c500-11e8-8d47-5ee60a05f4ed.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260148-426e5900-c500-11e8-9926-c2e4a5c7e3bd.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260149-4306ef80-c500-11e8-9140-8253c91ddd52.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260151-439f8600-c500-11e8-8735-0c86716f2df7.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260152-44381c80-c500-11e8-91ab-ce2e6d34686f.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260153-44381c80-c500-11e8-80bd-7cf7ac21b2a1.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260154-44d0b300-c500-11e8-9b95-49f9cd92fbd4.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260155-45694980-c500-11e8-815a-3cf331081bd1.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260156-45694980-c500-11e8-8f1e-855c33299027.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260157-45694980-c500-11e8-8caf-6eac8df1b3d0.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260158-4601e000-c500-11e8-85ac-629b98008587.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260159-469a7680-c500-11e8-9433-644cdc87a7c6.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260160-469a7680-c500-11e8-97c1-d2590247f26b.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260161-469a7680-c500-11e8-9777-7e0a7b8c88b7.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260162-469a7680-c500-11e8-9141-53a1a6836cd9.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260163-47330d00-c500-11e8-8347-f55e42b07ae8.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260164-47330d00-c500-11e8-9f23-bd17be2bad79.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260165-47cba380-c500-11e8-89d6-22977974439e.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260166-47cba380-c500-11e8-983a-a247928709b1.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260167-48643a00-c500-11e8-8b16-aaa17eb64bb8.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260168-48643a00-c500-11e8-98f3-61e9e95f7a07.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260169-48643a00-c500-11e8-9cf9-c7bb8dd881c2.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260170-48643a00-c500-11e8-9007-8f2194223894.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260171-48fcd080-c500-11e8-8969-22913193817e.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260172-49956700-c500-11e8-8147-3a266d79f1cc.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260173-49956700-c500-11e8-93c7-781fca02fde1.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260174-49956700-c500-11e8-8a54-9f9c134f8308.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260175-4ac69400-c500-11e8-9d94-3b8b22ee0523.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260176-4ac69400-c500-11e8-8494-12f63a9f346e.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260177-4ac69400-c500-11e8-8f31-77afa03c5c8e.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260178-4b5f2a80-c500-11e8-837c-a54e331e675c.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260179-4b5f2a80-c500-11e8-9ada-59d4d171a8d6.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260180-4b5f2a80-c500-11e8-91ae-6d5599e9eccf.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260181-4bf7c100-c500-11e8-82e8-27429d5ba525.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260182-4bf7c100-c500-11e8-9b39-25dfd8dda1c4.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260183-4bf7c100-c500-11e8-8a8d-e273029c4f75.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260184-4c905780-c500-11e8-8490-e0a9221391ee.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260185-4c905780-c500-11e8-97b9-ccd9ca59c6ae.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260186-4c905780-c500-11e8-860c-6f5b19213649.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260187-4d28ee00-c500-11e8-8480-6b9886bab78a.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260188-4d28ee00-c500-11e8-9634-142e92bf55b5.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260189-4dc18480-c500-11e8-86c9-698cd68cbfc9.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260190-4dc18480-c500-11e8-98c2-994aea2a19fb.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260191-4e5a1b00-c500-11e8-880e-a7ff0f5cca51.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260193-4e5a1b00-c500-11e8-8c3b-80ad4ee160fd.jpeg)

**Comment by tiann** [comment]
#415
