### ISSUE TITLE
是否可以对virtualxposed中安装的APP进行设置加白

### ISSUE THREAD

**Issue by snfnwgi** [android-hacker/VAExposed#414]
## 问题描述
在virtualxposed中的APP偶尔会自动退出，做了很多保活方案但还是不可以，在前面我提过问题，https://github.com/android-hacker/VirtualXposed/issues/379

经过漫长的思考有两个问题想请教作者：
1.是否可以对virtualxposed中的app直接加白，从而实现不被系统杀死，目前在系统中权限和电池白名单看不到virtualxposed里面的APP，给加白只是virtualxposed，不是很了解整体运行机制，没有给virtualxposed里的APP加白，系统还是会特定时刻杀掉virtualxposed里没加白的APP。

2.若方案1不可行。在单独启一个APP装在真机  来检测virtualxposed中的某个APP是否启动 （真机上app加白），若没启动唤起virtualxposed中的APP，这个方案可行得通吗？

作者如有其它方案，望您提点！

## 复现步骤

不能稳定复现

## 环境

**机型：**
小米5a
**系统版本：**
7.1.2
**ROM版本：**
**Xposed 插件以及插件版本：**
自己用的插件
**VirtualXposed版本：**
0.14.6

**Comment by tiann** [comment]
不可以。
