### ISSUE TITLE
Downloading http://dl.xposed.info/repo/full.xml.gz failed: 301 (Moved Permanently), Help me, plz share +916353583120,  Redmi note 5 Pro

### ISSUE THREAD

**Issue by naman8485** [android-hacker/VAExposed#415]
**Describe the bug**

**To Reproduce**
![whatsapp image 2018-09-30 at 10 17 51 pm 1](https://user-images.githubusercontent.com/42142076/46260889-d395fd80-c509-11e8-81f1-b30f7af08051.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 2](https://user-images.githubusercontent.com/42142076/46260890-d42e9400-c509-11e8-92d3-1f0c5a90c9eb.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 3](https://user-images.githubusercontent.com/42142076/46260891-d42e9400-c509-11e8-832a-5a2241f5cb5b.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 4](https://user-images.githubusercontent.com/42142076/46260892-d4c72a80-c509-11e8-9fd3-992b7fb972b3.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 5](https://user-images.githubusercontent.com/42142076/46260893-d4c72a80-c509-11e8-898e-7ed8081ab64b.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm 6](https://user-images.githubusercontent.com/42142076/46260894-d4c72a80-c509-11e8-963f-7be40cefa1d2.jpeg)
![whatsapp image 2018-09-30 at 10 17 51 pm](https://user-images.githubusercontent.com/42142076/46260895-d55fc100-c509-11e8-8dfd-afcbbb8947b6.jpeg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Redmi note 5 Pro]
 - OS: [Android]

**Additional context**

**Comment by vlt23** [comment]
This problem is in the server (Xposed repository) side. Clear Xposed Installer data. Don't forget re-enable modules that you installed.
