### ISSUE TITLE
荣耀8x vxp中无法打开微信

### ISSUE THREAD

**Issue by codelion1024** [android-hacker/VAExposed#416]
## 问题描述

荣耀8x vxp中无法打开微信,必现的

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）
1 安装VirtualXposed, 安装后勾选"信任此应用所有权限请求"
2 打开vxp,弹出"关于后台运行"的提示后,选择同意,在下来弹出的"是否忽略电池优化"选择"允许"
3 进入"添加应用"--"内部存储", 选择微信6.7.2的apk文件安装, 过一会提示"微信安装成功"
4 进入"常用模块", 下载"微信增强插件", 之后同样进入"添加应用"--"内部存储",安装插件
5 进入"模块管理",勾选"微信增强插件", 返回设置,点击"重启"重启vxp
6 在VXP内打开微信,提示打开com.tencent.mm失败

## 环境

机型：荣耀8x 4+64GB 全网通
系统版本：安卓8.1.0
ROM版本：EMUI 8.2.0
Xposed 插件以及插件版本：微信增强插件 1.6.0
VirtualXposed版本：0.15.1

## 补充
问题现象截图:  
![screenshot_20181001-102756](https://user-images.githubusercontent.com/35616755/46267051-a70fcf00-c565-11e8-8338-90b327050f43.jpg)

**Comment by earthGavinLee** [comment]
我的华为8x是使用微X插件后，微信闪退，关闭微X插件，微信正常。QQ加QX插件没有问题

**Comment by tiann** [comment]
先用别的插件替代吧，比如微信增强。
