### ISSUE TITLE
编译安装出现错误，直接崩溃

### ISSUE THREAD

**Issue by netstu** [android-hacker/VAExposed#417]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

编译安装出现错误，直接崩溃

## 复现步骤

android studio 升级至3.2以后就不可以了。。。。

## 环境

机型：任何机型
系统版本：6.X，7.x
ROM版本：flymeos, miui, mui等
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

10-06 15:49:42.883: E/VA++(5443): processProfileingInfo: 0xeb9ebff9
10-06 15:49:42.884: E/VA++(5443): compileMethod: 0xeb9e0d01
10-06 15:49:42.935: V/Launcher(5443): LauncherAppState initiated
10-06 15:49:43.004: V/BoostFramework(5469): BoostFramework() : mPerf = com.qualcomm.qti.Performance@4e664a0
10-06 15:49:43.004: I/art(5443): Ignoring second debugger -- accepting and dropping
10-06 15:49:43.017: I/art(5469): Ignoring second debugger -- accepting and dropping
10-06 15:49:43.045: E/VA++(5469): processProfileingInfo: 0xeb9ebff9
10-06 15:49:43.046: E/VA++(5469): compileMethod: 0xeb9e0d01
10-06 15:49:43.301: I/CrashlyticsCore(5443): Initializing Crashlytics 2.6.0.22
10-06 15:49:43.311: D/NetworkSecurityConfig(5443): No Network Security Config specified, using platform default
10-06 15:49:43.330: W/art(5443): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-06 15:49:43.342: W/System(5443): ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
10-06 15:49:43.343: D/ApplicationLoaders(5443): ignored Vulkan layer search path /system/app/MiuiContentCatcher/lib/arm64:/system/lib:/vendor/lib for namespace 0xee4110d0
10-06 15:49:43.343: D/AccessibilityManager(5443): current package=io.va.exposed, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
10-06 15:49:43.372: W/System.err(5443): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10-06 15:49:43.372: W/System.err(5443): SLF4J: Defaulting to no-operation (NOP) logger implementation
10-06 15:49:43.372: W/System.err(5443): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10-06 15:49:43.420: I/Adreno(5443): QUALCOMM build                   : 3b03957, I92eb381bc9
10-06 15:49:43.420: I/Adreno(5443): Build Date                       : 01/04/18
10-06 15:49:43.420: I/Adreno(5443): OpenGL ES Shader Compiler Version: XE031.09.00.04
10-06 15:49:43.420: I/Adreno(5443): Local Branch                     : 
10-06 15:49:43.420: I/Adreno(5443): Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.01.02.269.061
10-06 15:49:43.420: I/Adreno(5443): Remote Branch                    : NONE
10-06 15:49:43.420: I/Adreno(5443): Reconstruct Branch               : NOTHING
10-06 15:49:43.427: I/OpenGLRenderer(5443): Initialized EGL, version 1.4
10-06 15:49:43.428: D/OpenGLRenderer(5443): Swap behavior 1
10-06 15:49:43.494: I/Timeline(5443): Timeline: Activity_launch_request time:541555068
10-06 15:49:43.722: V/BoostFramework(5443): BoostFramework() : mPerf = com.qualcomm.qti.Performance@878519e
10-06 15:49:43.723: V/BoostFramework(5443): BoostFramework() : mPerf = com.qualcomm.qti.Performance@24d147f
10-06 15:49:43.857: V/BoostFramework(5443): BoostFramework() : mPerf = com.qualcomm.qti.Performance@f2f9314
10-06 15:49:43.858: V/BoostFramework(5443): BoostFramework() : mPerf = com.qualcomm.qti.Performance@b89e7bd
10-06 15:49:43.909: D/LoaderTask(5443): loadWorkspace: loading default favorites
10-06 15:49:44.017: W/View(5443): requestLayout() improperly called by com.android.launcher3.graphics.GradientView{6fd3093 V.ED..... ......I. 0,0-0,0 #7f0a00ac app:id/gradient_bg} during layout: running second layout pass
10-06 15:49:44.228: W/System.err(5443): android.content.pm.PackageManager$NameNotFoundException: de.robv.android.xposed.installer
10-06 15:49:44.228: W/System.err(5443): 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:351)
10-06 15:49:44.228: W/System.err(5443): 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:333)
10-06 15:49:44.228: W/System.err(5443): 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1273)
10-06 15:49:44.229: W/System.err(5443): 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getRoundIcon(CustomIconProvider.java:125)
10-06 15:49:44.229: W/System.err(5443): 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getIcon(CustomIconProvider.java:115)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:182)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:178)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.IconCache.cacheLocked(IconCache.java:537)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:479)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:451)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.AllAppsList.add(AllAppsList.java:81)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:821)
10-06 15:49:44.229: W/System.err(5443): 	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:164)
10-06 15:49:44.229: W/System.err(5443): 	at android.os.Handler.handleCallback(Handler.java:754)
10-06 15:49:44.229: W/System.err(5443): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-06 15:49:44.229: W/System.err(5443): 	at android.os.Looper.loop(Looper.java:163)
10-06 15:49:44.229: W/System.err(5443): 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-06 15:49:44.455: D/ProtoStore(5443): no cached data
10-06 15:49:44.455: D/ProtoStore(5443): no cached data
10-06 15:49:46.410: I/art(5443): System.exit called, status: 10
10-06 15:49:46.410: I/AndroidRuntime(5443): VM exiting with result code 10, cleanup skipped.
10-06 15:49:46.456: I/art(5469): Ignoring second debugger -- accepting and dropping
10-06 15:55:40.619: E/VA++(6230): processProfileingInfo: 0xeb9ebff9
10-06 15:55:40.619: E/VA++(6230): compileMethod: 0xeb9e0d01
10-06 15:55:40.671: V/Launcher(6230): LauncherAppState initiated
10-06 15:55:40.734: I/art(6261): Ignoring second debugger -- accepting and dropping
10-06 15:55:40.735: D/TidaProvider(6261): TidaProvider()
10-06 15:55:40.740: V/BoostFramework(6261): BoostFramework() : mPerf = com.qualcomm.qti.Performance@15c39a3
10-06 15:55:40.748: I/art(6230): Ignoring second debugger -- accepting and dropping
10-06 15:55:40.784: E/VA++(6261): processProfileingInfo: 0xeb9ebff9
10-06 15:55:40.785: E/VA++(6261): compileMethod: 0xeb9e0d01
10-06 15:55:41.012: I/CrashlyticsCore(6230): Initializing Crashlytics 2.6.0.22
10-06 15:55:41.023: D/NetworkSecurityConfig(6230): No Network Security Config specified, using platform default
10-06 15:55:41.045: W/art(6230): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-06 15:55:41.057: W/System(6230): ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
10-06 15:55:41.058: D/ApplicationLoaders(6230): ignored Vulkan layer search path /system/app/MiuiContentCatcher/lib/arm64:/system/lib:/vendor/lib for namespace 0xee4110d0
10-06 15:55:41.058: D/AccessibilityManager(6230): current package=io.va.exposed, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
10-06 15:55:41.090: W/System.err(6230): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10-06 15:55:41.090: W/System.err(6230): SLF4J: Defaulting to no-operation (NOP) logger implementation
10-06 15:55:41.090: W/System.err(6230): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10-06 15:55:41.092: I/FlurryROMCollector(6230): start collect...
10-06 15:55:41.094: I/FlurryROMCollector(6230): end collect...
10-06 15:55:41.137: I/Adreno(6230): QUALCOMM build                   : 3b03957, I92eb381bc9
10-06 15:55:41.137: I/Adreno(6230): Build Date                       : 01/04/18
10-06 15:55:41.137: I/Adreno(6230): OpenGL ES Shader Compiler Version: XE031.09.00.04
10-06 15:55:41.137: I/Adreno(6230): Local Branch                     : 
10-06 15:55:41.137: I/Adreno(6230): Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.01.02.269.061
10-06 15:55:41.137: I/Adreno(6230): Remote Branch                    : NONE
10-06 15:55:41.137: I/Adreno(6230): Reconstruct Branch               : NOTHING
10-06 15:55:41.144: I/OpenGLRenderer(6230): Initialized EGL, version 1.4
10-06 15:55:41.145: D/OpenGLRenderer(6230): Swap behavior 1
10-06 15:55:41.218: I/Timeline(6230): Timeline: Activity_launch_request time:541912792
10-06 15:55:41.450: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@878519e
10-06 15:55:41.451: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@24d147f
10-06 15:55:41.583: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@f2f9314
10-06 15:55:41.584: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@b89e7bd
10-06 15:55:41.683: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@9426c34
10-06 15:55:41.683: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@2781a5d
10-06 15:55:41.690: V/GridSizeMigrationTask(6230): Workspace migration completed in 54
10-06 15:55:41.691: D/LoaderTask(6230): loadWorkspace: loading default favorites
10-06 15:55:41.700: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@f30071e
10-06 15:55:41.700: V/BoostFramework(6230): BoostFramework() : mPerf = com.qualcomm.qti.Performance@8d25bff
10-06 15:55:41.750: D/LauncherProvider(6230): loading default workspace
10-06 15:55:41.854: W/View(6230): requestLayout() improperly called by com.android.launcher3.graphics.GradientView{c7dec1d V.ED..... ......I. 0,0-0,0 #7f0a00ac app:id/gradient_bg} during layout: running second layout pass
10-06 15:55:41.971: E/LoaderCursor(6230): Invalid package removed: com.android.contacts
10-06 15:55:41.973: E/LoaderCursor(6230): Invalid package removed: com.android.mms
10-06 15:55:41.975: E/LoaderCursor(6230): Invalid package removed: com.coolapk.market
10-06 15:55:41.976: E/LoaderCursor(6230): Invalid package removed: com.android.browser
10-06 15:55:41.978: E/LoaderCursor(6230): Invalid package removed: com.android.camera
10-06 15:55:42.139: W/System.err(6230): android.content.pm.PackageManager$NameNotFoundException: de.robv.android.xposed.installer
10-06 15:55:42.140: W/System.err(6230): 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:351)
10-06 15:55:42.140: W/System.err(6230): 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:333)
10-06 15:55:42.140: W/System.err(6230): 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1273)
10-06 15:55:42.140: W/System.err(6230): 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getRoundIcon(CustomIconProvider.java:125)
10-06 15:55:42.140: W/System.err(6230): 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getIcon(CustomIconProvider.java:115)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:182)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:178)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.IconCache.cacheLocked(IconCache.java:537)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:479)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:451)
10-06 15:55:42.140: W/System.err(6230): 	at com.android.launcher3.AllAppsList.add(AllAppsList.java:81)
10-06 15:55:42.141: W/System.err(6230): 	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:821)
10-06 15:55:42.141: W/System.err(6230): 	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:164)
10-06 15:55:42.141: W/System.err(6230): 	at android.os.Handler.handleCallback(Handler.java:754)
10-06 15:55:42.141: W/System.err(6230): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-06 15:55:42.141: W/System.err(6230): 	at android.os.Looper.loop(Looper.java:163)
10-06 15:55:42.141: W/System.err(6230): 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-06 15:55:42.385: W/IconCustomizer(6230): can't load transform_config.xml
10-06 15:55:42.841: D/ProtoStore(6230): no cached data
10-06 15:55:42.841: D/ProtoStore(6230): no cached data
10-06 15:55:43.584: I/art(6230): System.exit called, status: 10
10-06 15:55:43.584: I/AndroidRuntime(6230): VM exiting with result code 10, cleanup skipped.
10-06 15:55:43.641: I/art(6261): Ignoring second debugger -- accepting and dropping

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
仔细阅读wiki。
