### ISSUE TITLE
A Lot Of Malware Detection

### ISSUE THREAD

**Issue by 0pLuS0** [android-hacker/VAExposed#422]
**Describe the bug**
VirtualXposed shows malware detection

**To Reproduce**
1. Go to 'virustotal.com'
2. Click on 'choose file button'
3. Scroll down to ' see all the malware detection on virustotal.com - see the link below'

**Expected behavior**
I don't expect to see any detection of malware

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 8.1.0
 - Browser - Privacy Browser
 - Version 8.1.0

**Smartphone (please complete the following information):**
 - Device: One Plus 6
 - OS: Oxygen OS
 - Browser - Privacy Browser

**Additional context**
I understand this is Open Source so I highly doubt someone would push malware like this on an open source project, but it's not the point, people will assume the worse and not take chances.

It would be greatly appreciated if you can fix all these detections...

https://www.virustotal.com/#/file/f4424255705a781d9ba7862592e521f5f718e9325a2cba4d8524a73f4d0dac0b/detection

Thanks

**Comment by tiann** [comment]
in README:

> VirusTotal might report VirtualXposed as a malware, it is stupid, you can refer to my explanation: #10 .
> 
> And obviously, VirtualXposed is open source, so you can refer to the source code. I am sure that it is safe to use.
> 
> If you still couldn't believe in me, you can install version 0.8.7; VirusTotal reports this version as safe.

**Comment by 0pLuS0** [comment]
Regardless of whether it's proprietary or open sourced, you don't want to have source giving off these detections. 

One false positive is one thing, 18 is something else...

Anyhow, I would really like to see this project grow, because the Android Community needs something like this so we don't have to use Xposed.

I hope for future releases you'll have the code cleaned...

Thanks

**Comment by 0pLuS0** [comment]
0.8.7 is going back a lot of versions, which is also not good to keep up to the latest development.

There is also no 0.8.7 listed on your repo only 0.8.8, but older code isn't helping us.

Again, I hope you'll get some newer versions released soon with no issues.

Thanks

**Comment by tiann** [comment]
No, I won't struggle with the stupid anti-virus engine.
