### ISSUE TITLE
在vxp中安装微信，微信图标没有消息红点点提示，通知栏也没有

### ISSUE THREAD

**Issue by kyrie2014** [android-hacker/VAExposed#424]
## 场景描述

在vxp中安装微信，微信图标没有消息红点点提示，通知栏也没有，必须打开微信才能知道有没有新消息，不是很方便，也不适合长期使用。

## 希望的解决方案

希望vxp中的微信使用，可以和原生系统中一样，有新消息提示。

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
1. 图标红点无法实现。
2. 通知栏不显示是rom的原因，暂时不会修复。
