### ISSUE TITLE
vxp内app启动失败

### ISSUE THREAD

**Issue by Nidhoggur1993** [android-hacker/VAExposed#427]
## 问题描述

无法启动app

## 复现步骤

钉钉和MockLocation 4.0，xp内勾选MockLocation插件，钉钉启动失败
不勾选插件则正常启动，其他定位软件如lataclysm一样
对于lataclysm，Settings-PackageName配置了com.alibaba.android.rimet

## 环境

机型：XIAOMI POCOPHONE F1
系统版本：8.1
ROM版本：miui global 9.6
Xposed 插件以及插件版本：lataclysm 1.35 ，Mock Location 4.0
进程名：com.alibaba.android.rimet
VirtualXposed版本：0.15.1

## 补充

报错如图
![image](https://user-images.githubusercontent.com/12947582/46854424-59cc1100-ce33-11e8-93b8-278eb0c239fd.png)

配置如图
![image](https://user-images.githubusercontent.com/12947582/46854431-63557900-ce33-11e8-93fd-35472e249109.png)

**Comment by coolxiaoning** [comment]
我也是这情况，用钉钉和MockLocation 4.0，各种崩溃。

**Comment by Nidhoggur1993** [comment]
@coolxiaoning 对，但很迷的是如果直接用xp就不会有崩溃的问题，怀疑是vxp的某些组件没注入成功@tiann

**Comment by idelin** [comment]
我也是这情况，钉钉根本无法打开，兄弟解决了at下我

**Comment by bebetter1030** [comment]
@idelin @Nidhoggur1993 @coolxiaoning 
我也遇到了，旧工程如果勾选模块，启动不了；但是新建工程就没问题。

步骤：Android Studio新建一个project，然后File -> New -> Import Module，导入旧工程里的Module。

这样的编译出来的apk可以正常使用。
粗略检查了配置没问题，但是就是编译旧工程的无法运行，而新建工程可以。不知道什么原因- -

**Comment by idelin** [comment]
@bebetter1030 可以给我一个编译好的apk吗，zdl0929@gmail.com

**Comment by bebetter1030** [comment]
@idelin  我没办法给你编译钉钉啊- -。其实我的问题跟你们的还是不一样，只是报错类型一样。看其他的issues，钉钉没办法用vxp的。

我遇到的问题是我自行开发的xposed app启动不了，新建工程，导入源码编译才可以用。
