### ISSUE TITLE
对话框取消模块不生效

### ISSUE THREAD

**Issue by stdrc** [android-hacker/VAExposed#430]
## 问题描述

[对话框取消](https://repo.xposed.info/module/com.mhook.dialog) 模块不生效（无法通过点击对话框外来关闭，在其它已 root 的 Android 上是有效的）。

## 复现步骤

在对话框取消模块中开启增强模式并选定某一弹出强制对话框的应用，然后启用设置，保存并重启，预期应该会重启该应用，然后可以关闭强制对话框，但实际上没有重启应用，也无法关闭对话框。

## 环境

机型：OPPO R9 Plus
系统版本：Android 5.1.1
ROM版本：ColorOS 3.0 稳定版
Xposed 插件以及插件版本：对话框取消 com.mhook.dialog 1.5.1
VirtualXposed版本：0.15.1

**Comment by tiann** [comment]
先看说明，这种模块是没法支持的。
