### ISSUE TITLE
貌似按你给出的git clone编译出来不能正常工作

### ISSUE THREAD

**Issue by ppma** [android-hacker/VAExposed#431]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
git clone https://github.com/android-hacker/VirtualXposed.git -b exposed --recursive
按你给出的方法编译出来的VirtualXposed不能正常工作，进入VirtualXposed的桌面后等待几秒闪退
但是你给出的0.15.1版本的apk（https://github.com/android-hacker/VirtualXposed/releases/download/0.15.1/VirtualXposed_0.15.1.apk）能正常工作
（请尽量详细地描述你遇到的问题）

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by yuninf** [comment]
epic版本过低，意思就是不是全开源。

**Comment by tiann** [comment]
既然你要自己编译，你就去把代码看一遍，看了你就明白了，进去就闪退不是epic的问题。

**Comment by ppma** [comment]
看见了，是app模块下的签名校验

**Comment by ppma** [comment]
> 
> 
> 既然你要自己编译，你就去把代码看一遍，看了你就明白了，进去就闪退不是epic的问题。

看见了，`	/**
	 * 君子坦荡荡，小人常戚戚
	 * @param context the context
	 */
	public static void c(Context context) {
		String sig = getSig(context);
		if (!"99A244F52F40581B48E4BA61E3435B6C".equalsIgnoreCase(sig)) {
			System.exit(10);
			android.os.Process.killProcess(android.os.Process.myPid());
		}
	}`
