### ISSUE TITLE
已经安装最新的VirtualXposed_0.15.1版本，但莫名其妙的会提示更新

### ISSUE THREAD

**Issue by willdeadmonkeyking** [android-hacker/VAExposed#432]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

已经安装最新的VirtualXposed_0.15.1版本，但莫名其妙的会提示更新。提示就算了，还会直接中断当前模块。如果可以的话，能否提供设置是否自动更新功能

## 复现步骤

原先安装0.14.5版本，在线更新为0.15.1.然后在线测试自己写的一个模块，准备测试一天一夜。可晚上突然就自动提示要更新新版本，点击更新啥也没用，但测试已经被中断了。原先直接安装0.15.1版本的还没测试是否会如此

## 环境

机型：小米MIX2S
系统版本：Android 8.0.0
ROM版本：MINU 10.0.3 稳定版
Xposed 插件以及插件版本：Xposed 91,Xposed Installer .
VirtualXposed版本：0.15.1

## 补充

只安装了本人自己写的模块，其他模块都没安装

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by bg4hsi** [comment]
我是直接安装0.15.1，也是会提示更新

**Comment by willdeadmonkeyking** [comment]
那这个真是日了狗啊，难道要倒退回旧版本

**Comment by tiann** [comment]
这有什么奇怪的，本来就有更新。

**Comment by willdeadmonkeyking** [comment]
没有更新啊，点击了根本就没响应啊。有正常更新当然就不说了

**Comment by tiann** [comment]
哥，服务器挂了，很奇怪吗？

**Comment by willdeadmonkeyking** [comment]
不奇怪，苦逼的只能再从头测试一下了。大兄弟可以提供不自动更新的选择吗
