### ISSUE TITLE
如何集成自己的apk到xv

### ISSUE THREAD

**Issue by lly835** [android-hacker/VAExposed#433]
## 场景描述
我希望把我的apk打包进xv, 最后生成一个合体的apk, 用户安装后，打开vx, 里面直接有我的apk

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
自己编译源码。

**Comment by lly835** [comment]
> 自己编译源码。

可以具体下吗？放哪个目录下呢

**Comment by tiann** [comment]
难道还要我手把手教吗。。。我可没有这个义务。
