### ISSUE TITLE
不支持Chrome浏览器

### ISSUE THREAD

**Issue by fishjam** [android-hacker/VAExposed#434]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

不支持Chrome浏览器，比如: [AndroidChromium](https://github.com/JackyAndroid/AndroidChromium)

## 复现步骤

1.下载 [AndroidChromium](https://github.com/JackyAndroid/AndroidChromium) 的源码,编译并Clone到 VirtualXposed 里面, 启动时报错，且一直无法连接服务器

## 环境

机型：
系统版本：Android 6.0 和 8.0 上都有问题
ROM版本: 
Xposed 插件以及插件版本：
VirtualXposed版本：151(但似乎各个版本都有问题)

## 补充
  按照 https://github.com/asLody/VirtualApp/issues/490 的说法，在VA的商业版本中已经进行了修复，不过不清楚具体的修复方式

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不清楚 clone Chrome有什么用？这个项目的目的与 VA 不一样，非Xposed相关的问题不会修复。
