### ISSUE TITLE
Newer update not publish on github

### ISSUE THREAD

**Issue by z2z** [android-hacker/VAExposed#435]
`{
  "url":"http://files.git.oschina.net/group1/M00/05/32/PaAvDFvD_NeAPoGpAGpyCkomlaI889.apk?token=65588cea0c0b848e4f66c2684e4fe84f&ts=1539570905&attname=VirtualXposed_0.16.0.apk",
  "versionCode": 160,
  "updateMessage":" 支持一种全新的免Root、免解锁Bootloader，免刷机使用 Xposed 的方式。",
  "url2": "http://files.git.oschina.net/group1/M00/05/32/PaAvDFvD_CaAMDu5AGZMPI2yf4E357.apk?token=d562126bfc864519feee7822932682dd&ts=1539570746&attname=TaiChi_2.9.apk",
  "versionCode2": 28,
  "updateMessage2": "1. 初步支持 VirtualXposed 和 太极互相调用。\n2. 开放云村清洁工模块，请自行测试。\n3. 支持创建TIM。\n4. 支持无障碍；感谢无障碍开发组的支持。\n5. 修复若干界面上的BUG。\n6. 修复取消优化后自动安装的问题。\n7. 支持从模块管理界面打开没有图标的插件。\n8. 修复英文系统下依然显示中二文案的问题。",
  "force": false,
   "title": "重大更新"
}`

Few observation:

1. Newer version code in not push to Github.
2. Why not disturbe apk via [f-droid store](https://f-droid.org/en/)
3. Please check [microG release process](https://github.com/microg/android_packages_apps_GmsCore)
4. Also, update shared thru HTTP.
5. English is more globally understood. No offense against the Chinese but if you want more people to understand and take benefit of your tool. In larger interest, it is better to have it English as a default.

**Comment by tiann** [comment]
Thanks for your advice :)

1. I will publish the new version to github soon.
2. The license of VirtualXposed is a little complicated : #138 it may not be published via f-droid.
3. I will make English the default language, thank you.

**Comment by w27797006** [comment]
Do VirtualXposed support AccessibilityService?  I want use AccessibilityService in VirtualXposed。
I tried, but it didn't work.
