### ISSUE TITLE
怎么抓跳转到webview时的cookie

### ISSUE THREAD

**Issue by lly835** [android-hacker/VAExposed#439]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述
点击app上的一个按钮，跳到了webview, 抓包发现，还带着cookie，如何通过hook抓到这个cookie呢

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
请不要滥用issue功能，这问题你应该去stackoverflow之类的提问。
