### ISSUE TITLE
Create LICENSE

### ISSUE THREAD

**Issue by Generator** [android-hacker/VAExposed#449]
Instead of using 
> Usage for Commercial Purposes are not allowed!!! Please refer to VirtualApp's declaration.

Creating a LICENSE is a better way to protect your code

**Github Help** - [Licensing a repository](https://help.github.com/articles/licensing-a-repository/)  

Heres a list of licenses without that **don't allow** Commercial Use   
https://tldrlegal.com/search?reverse=true&cannot%5B%5D=52c0d009a1ddc9766c00000a

**Comment by tiann** [comment]
This is because VirtualXposed use https://github.com/asLody/VirtualApp, the library has a strange license.
