### ISSUE TITLE
安装在VirtualXposed 0.16.0里面的app发起io.va.exposed.CMD  reboot不起作用

### ISSUE THREAD

**Issue by willdeadmonkeyking** [android-hacker/VAExposed#453]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

安装在VirtualXposed_0.16.0里面的app，发起一个广播，actionName="io.va.exposed.CMD"  cmd="reboot" 好像不起作用。是在app内发的广播VirtualXposed收不到吗？

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：MIX2S
系统版本：Android 8.0.0
ROM版本：MIUI 10.0.3.0
Xposed 插件以及插件版本：0.16.0自带
VirtualXposed版本：0.16.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不支持这么做。

**Comment by willdeadmonkeyking** [comment]
那是否有其他方式，因为app做了自动更新模块，需要重加载模块。不重启的话无法生效

**Comment by tiann** [comment]
不允许插件重启整个虚拟环境，需要的话自己改代码。

**Comment by willdeadmonkeyking** [comment]
需要啊，不知道咋弄。你的意思是自行修改编译这个VirtualXposed? 但据我所知好像你这个不是最新的吧，而且有个什么东西还是旧的
