### ISSUE TITLE
关于科学上网的不情之请

### ISSUE THREAD

**Issue by H-P-C** [android-hacker/VAExposed#456]
场景描述
我有几款vpn的应用，但是会有自启和广告的问题，我希望通过把应用安装在virtualxposed上，
达到禁止其自启和使用插件屏蔽广告的目的。以上是我的应用场景。

希望的解决方案
通过virtualxposed打开其中的vpn应用，并能连接VPN成功。

其他信息
感谢！

**Comment by tiann** [comment]
与 Xposed 无关。
