### ISSUE TITLE
编译完成安装到手机，启动vxp闪退

### ISSUE THREAD

**Issue by gittarko** [android-hacker/VAExposed#463]
## 问题描述
我在Android Studio中编译了本项目，成功编译后开始安装vxp到手机中使用，但是vxp启动到桌面时就闪退；有时刚刚启动就闪退，有时在vxp的桌面中闪退，但是作者的release版本安装到手机无此种情况，所以怀疑是自己编译环境配置问题。

## 复现步骤
上述问题在我的手机上是必现。通过调试能进入NewHomeActivity

## 环境
机型：小米MIX 2S
系统版本：Android 9
ROM版本：小米MIUI 10.8.10.25（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：0.16.1
VirtualXposed版本：3.1.5

**Comment by tiann** [comment]
请仔细阅读源码。。。。

**Comment by gittarko** [comment]
> 请仔细阅读源码。。。。

哈哈，君子坦荡荡，小人长戚戚。学习了

**Comment by SharsDela** [comment]
大哥你好，我跟你一个机子也是miui10。同样的问题。请问是怎么解决的呢？

**Comment by degjeg** [comment]
请问解决了吗，我也 是，下载release apk可以运行，我自己打包闪退

**Comment by gittarko** [comment]
可将源码中的君子坦荡荡，小人长戚戚标注的函数注释掉
