### ISSUE TITLE
WebViewDebugHook 

### ISSUE THREAD

**Issue by ljee-hash** [android-hacker/VAExposed#464]
## 场景描述

接下来用VXP自带的安装器，安装失败：

用VXP安装插件 WebViewDebugHook （同样是个Apk下载）
https://github.com/feix760/WebViewDebugHook/blob/master/WebViewDebugHook.apk
再VXP安装ApiDemos-debug.apk
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ApiDemos-debug.apk
## 希望的解决方案

请问如何手机不root如何安装

**Comment by tiann** [comment]
哪个安装失败？logcat 错误日志有么

**Comment by ljee-hash** [comment]
> 哪个安装失败？logcat 错误日志有么

两个都是失败了

**Comment by ljee-hash** [comment]
> 哪个安装失败？logcat 错误日志有么

您那边不root能成功安装么？

**Comment by tiann** [comment]
你把日志弄到，我看一眼就行了。我可没那么多时间帮你解决问题。

**Comment by tiann** [comment]
小米 MIX2S 两个安装包都能正常安装，不存在所述问题。
