### ISSUE TITLE
在hook的方法中发送网络请求目标App会闪退

### ISSUE THREAD

**Issue by YaoLingOuYang** [android-hacker/VAExposed#469]
## 问题描述

大神，你好！

我下载了0.16.1版本的【VirtualXposed】进行编译和编写了一个【Xposed模块】用来hook目标App。写完代码后，能够正常hook目标App的方法。但是只要在hook的方法中发送网络请求目标App就会闪退（在你发布的VirtualXposed_0.16.1却能够正常运行）。不知道是什么原因呢？

![qq 20181114183424](https://user-images.githubusercontent.com/13212518/48477239-10108500-e83c-11e8-8386-ca1a5a39b1c7.png)

## 复现步骤

1.进入目标App首页（我hook了目标App首页的onResume方法，在该方法结束时发送网络请求）。
2.目标App停止运行（但是我把发送网络请求代码注释了，不会停止运行）。

## 环境

机型：红米4A
系统版本：Android 6.0.1
ROM版本：稳定版
Xposed 插件以及插件版本：自己写的Demo
VirtualXposed版本：0.16.1

## 补充
我已经注释了 签名验证

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by Pangu-Immortal** [comment]
不只是闪退还会黑屏，还会卡死，我刚下载了这个库编译运行了一下，发现不可用。。直接下载现成的apk版本[VirtualXposed_0.8.6.apk](url
https://github.com/android-hacker/VirtualXposed/releases/download/0.8.6/VirtualXposed_0.8.6.apk) 就都是正常的，我目前也是无解，看不出个所以然来。。。感觉不适合使用，放弃了，会有其他的库出来的，再找找吧……

**Comment by tiann** [comment]
#325
