### ISSUE TITLE
能否加入防检测虚拟Xposed环境和防检测Xposed安装情况？

### ISSUE THREAD

**Issue by saymyname77** [android-hacker/VAExposed#470]
## 场景描述
在VXp中运行的软件提示软件包非官方，为第三方。后闪退并受到不良记录。

## 希望的解决方案
根据xposed checker 在vxp中检测结果为：能检测到 虚拟Xposed环境 和 Xposed已安装。
不知软件检测原理，在x隐私lua中已把所运行的软件权限给到最基本。

## 其他信息
Lineage OS 15.1 ，VXp 0.16.1 , 用到的xposed 模块：模拟位置。
在VXp中使用xposed hider，在模拟位置中配置对此软件隐藏等方法均无效。此软件一直提示非官方安装包。
还望不吝指点，sunc404@gmail.com

**Comment by saymyname77** [comment]
@tiann

**Comment by tiann** [comment]
这种技术开源出来那不等于扯淡吗？

**Comment by saymyname77** [comment]
说白了ding+模拟位置无法正常运行在vxp里。直接通知管理员。

**Comment by saymyname77** [comment]
@tiann 大佬求救。
