### ISSUE TITLE
源码无法编译通过

### ISSUE THREAD

**Issue by ctlyh3059** [android-hacker/VAExposed#472]
问题描述
源码无法编译通过，版本为0.16.1，报错提示为 
Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve project :launcher.
Unable to resolve dependency for ':app@aospDebugAndroidTest/compileClasspath': Could not resolve project :launcher.
Unable to resolve dependency for ':app@aospDebugUnitTest/compileClasspath': Could not resolve project :launcher.
Unable to resolve dependency for ':app@aospRelease/compileClasspath': Could not resolve project :launcher
Unable to resolve dependency for ':app@aospReleaseUnitTest/compileClasspath': Could not resolve project :launcher.

复现步骤
1、下载的源码包
2、解压源码包
3、用android studio 3.2.1打开包里边的项目。
4、编译。

环境
机型：
系统版本：win7 64bit
VirtualXposed版本：0.16.1

补充
源码无法编译通过，版本为0.16.1，

**Comment by tiann** [comment]
仔细读wiki。
