### ISSUE TITLE
内置app后启动报错

### ISSUE THREAD

**Issue by andyli386** [android-hacker/VAExposed#473]
## 问题描述
你好，我按照内置XposedInstaller的方法内置了一款应用，同时关闭了VCommends中的校验，启动VXP可以正常运行，但是如果从后台清除再次打开就会崩溃，崩溃之后再次打开又恢复正常，崩溃和正常交替出现。

## 复现步骤
1、内置任一款app
2、关闭VCommends中的校验后编译安装
3、启动VXP
4、打开内置应用
5、从后台中清除VXP
6、再次打开VXP，VXP崩溃
日志如下：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
ABI: 'arm'
pid: 29168, tid: 29168, name: io.va.exposed  >>> io.va.exposed <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IllegalArgumentException: '
    r0 00000000  r1 000071f0  r2 00000006  r3 00000008
    r4 f3dc658c  r5 00000006  r6 f3dc6534  r7 0000010c
    r8 0000000a  r9 00001af0  sl 00000000  fp ffb9f2ec
    ip 0000000b  sp ffb9f1e8  lr f35d6ab3  pc f35d93cc  cpsr 600f0010

backtrace:
    #00 pc 0004a3cc  /system/lib/libc.so (tgkill+12)
    #01 pc 00047aaf  /system/lib/libc.so (pthread_kill+34)
    #02 pc 0001d889  /system/lib/libc.so (raise+10)
    #03 pc 00019295  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 000172ec  /system/lib/libc.so (abort+4)
    #05 pc 00322e3d  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+328)
    #06 pc 000b6ced  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1176)
    #07 pc 0023e2fd  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
    #08 pc 0023e553  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
    #09 pc 000cc7d3  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+42)
    #10 pc 000cc3c3  /system/lib/libart.so (_ZN3art11ScopedCheck11CheckThreadEP7_JNIEnv+362)
    #11 pc 000cb3d7  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+26)
    #12 pc 000ca8a9  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+800)
    #13 pc 000bf9c5  /system/lib/libart.so (_ZN3art8CheckJNI9FindClassEP7_JNIEnvPKc+444)
    #14 pc 000442bd  /data/app/io.va.exposed-1/lib/arm/libva++.so (_ZN8facebook3jni15findClassStaticEPKc+40)
    #15 pc 000376c3  /data/app/io.va.exposed-1/lib/arm/libva++.so
    #16 pc 00044133  /data/app/io.va.exposed-1/lib/arm/libva++.so (_ZN8facebook3jni10initializeEP7_JavaVMONSt6__ndk18functionIFvvEEE+90)
    #17 pc 00037625  /data/app/io.va.exposed-1/lib/arm/libva++.so (JNI_OnLoad+64)
    #18 pc 0023ffc9  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP8_jstringPS9_+1844)
    #19 pc 00003437  /system/lib/libopenjdkjvm.so (JVM_NativeLoad+190)
    #20 pc 00583c75  /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Runtime.nativeLoad+144)
    #21 pc 005838b5  /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Runtime.doLoad+136)
    #22 pc 00584dc1  /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.Runtime.loadLibrary0+540)
    #23 pc 0059d283  /system/framework/arm/boot.oat (offset 0x51b000) (java.lang.System.loadLibrary+78)
    #24 pc 000aaac1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
    #25 pc 0041170d  /system/lib/libart.so (art_quick_invoke_static_stub+228)
    #26 pc 000b1db3  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
    #27 pc 001f1923  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+198)
    #28 pc 001ebec3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+478)
    #29 pc 0040a17f  /system/lib/libart.so (MterpInvokeStatic+238)
    #30 pc 0009da94  /system/lib/libart.so (ExecuteMterpImpl+14612)
    #31 pc 001cf10f  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
    #32 pc 001d3bd9  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
    #33 pc 004009e1  /system/lib/libart.so (artQuickToInterpreterBridge+716)
    #34 pc 000af513  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
    #35 pc 000aaac1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
    #36 pc 0041170d  /system/lib/libart.so (art_quick_invoke_static_stub+228)
    #37 pc 000b1db3  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
    #38 pc 000f2bf9  /system/lib/libart.so (_ZN3art11ClassLinker15InitializeClassEPNS_6ThreadENS_6HandleINS_6mirror5ClassEEEbb+3040)
    #39 pc 000dd1d1  /system/lib/libart.so (_ZN3art11ClassLinker17EnsureInitializedEPNS_6ThreadENS_6HandleINS_6mirror5ClassEEEbb+120)
    #40 pc 001f1991  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+308)
    #41 pc 001ebec3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+478)
    #42 pc 0040a17f  /system/lib/libart.so (MterpInvokeStatic+238)
    #43 pc 0009da94  /system/lib/libart.so (ExecuteMterpImpl+14612)
    #44 pc 001cf10f  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
    #45 pc 001d3bd9  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
    #46 pc 004009e1  /system/lib/libart.so (artQuickToInterpreterBridge+716)
    #47 pc 000af513  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
    #48 pc 0196c2fb  /system/framework/arm/boot-framework.oat (offset 0x18c8000) (android.app.Application.attach+38)
    #49 pc 019cb927  /system/framework/arm/boot-framework.oat (offset 0x18c8000) (android.app.Instrumentation.newApplication+82)
    #50 pc 019cec1d  /system/framework/arm/boot-framework.oat (offset 0x18c8000) (android.app.Instrumentation.newApplication+72)
    #51 pc 019d8c79  /system/framework/arm/boot-framework.oat (offset 0x18c8000) (android.app.LoadedApk.makeApplication+348)
    #52 pc 000aaac1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
    #53 pc 00411605  /system/lib/libart.so (art_quick_invoke_stub+232)
    #54 pc 000b1d89  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+136)
    #55 pc 001f1923  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+198)
    #56 pc 001ebec3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+478)
    #57 pc 00408f8f  /system/lib/libart.so (MterpInvokeVirtual+422)
    #58 pc 0009d914  /system/lib/libart.so (ExecuteMterpImpl+14228)
    #59 pc 001cf10f  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
    #60 pc 001d3bd9  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
    #61 pc 004009e1  /system/lib/libart.so (artQuickToInterpreterBridge+716)
    #62 pc 000af513  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
    #63 pc 000aaac1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)

## 环境

机型：小米note3
系统版本：7.1.1 NMF26X
ROM版本：MIUI Global 9.6.2.0稳定版
Xposed 插件以及插件版本：无
VirtualXposed版本：0.16.1

**Comment by tiann** [comment]
> JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IllegalArgumentException:

**Comment by lvlingit** [comment]
老兄这个问题是我们Java代码写的有问题还是jin写的有问题啊？

**Comment by andyli386** [comment]
> 老兄这个问题是我们Java代码写的有问题还是jin写的有问题啊？

都没有问题，作者在代码里面加了两处验证的，你屏蔽掉就好了

**Comment by lvlingit** [comment]
一处是签名验证，还有一处是什么？

**Comment by andyli386** [comment]
> 一处是签名验证，还有一处是什么？

也是签名，你找找

**Comment by andyli386** [comment]
> 一处是签名验证，还有一处是什么？

君子坦荡荡

**Comment by lvlingit** [comment]
这个已经注了，但是另外一处什么

**Comment by lvlingit** [comment]
没看到哪里还有签名验证啊
