### ISSUE TITLE
最新版快手安装后无法登陆

### ISSUE THREAD

**Issue by ZCShou** [android-hacker/VAExposed#478]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

最新版快手安装后无法登陆，提示无法访问网络

## 复现步骤

1. 安装
2. 登陆

## 环境

机型：
系统版本：8.0
ROM版本：EMUI
Xposed 插件以及插件版本：最新版
VirtualXposed版本：最新版

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by xsren** [comment]
+1

**Comment by qiang** [comment]
> +1

这个是快手证书的问题。你可以试试给手机挂载Charles之后就能登录。或者把快手的证书拷贝的VirtualXposed里面，按照Android官网配置network_security_config.xml 应该就可以了

**Comment by Karl0** [comment]
请问你们解决了吗？我也遇到了类似的问题，now直播app在VirtualXposed中登录有时登录不进去，有时进去没有任何数据。如果已解决请您回复我一下可以吗？万分感谢。邮箱614472117@qq.com
