### ISSUE TITLE
无法安装Google服务

### ISSUE THREAD

**Issue by AGG091** [android-hacker/VAExposed#480]
我用的是一加6T手机，系统是安卓9.0的
在virtualxposed0.16.1版本的Google服务安装不了，他提示手动安装，可是microG的组件也安装失败，怎么才能安装上Google服务呢？

**Comment by daohuosuo** [comment]
我也是，magic 2安卓9.0，无法安装谷歌服务

**Comment by ghost** [comment]
@DengHS @AGG091 Click add app then select your current Google store and Google services

**Comment by ghost** [comment]
same issue on Honor V10. Has the author given up to support microG on VirtualXposed? If so, when will TaiChi support that?

**Comment by tiann** [comment]
#536
