### ISSUE TITLE
安卓9无法打开企业微信

### ISSUE THREAD

**Issue by daohuosuo** [android-hacker/VAExposed#481]
荣耀Magic 2 系统安卓9，启用模拟位置模块后，无法打开企业微信，不启用则可以。

**Comment by yhf7952** [comment]
同样的问题，帮顶一个。
另一个太极应用则完全不支持企业微信…

**Comment by link-duan** [comment]
我是支付宝打不开，提示网络错误，再次尝试则提示操作过于频繁。
关闭了Xposed仍然这样。
在系统桌面上打开则正常

**Comment by Gavinwei** [comment]
同样的问题，有人解决没有？

**Comment by Shelomi** [comment]
华为Pro20 无法打开企业微信

**Comment by tiann** [comment]
这些 App 会检测环境，如果用插件的话，需要插件自己绕过检测。VirtualXposed 本身并不会去对抗检测。
