### ISSUE TITLE
请教下不安装Xposed，怎么实现相应功能？

### ISSUE THREAD

**Issue by JakeWoki** [android-hacker/VAExposed#482]
有些app不安装Xposed也能实现一部分相应功能，是引入哪个库还是怎么实现的？求教

**Comment by tiann** [comment]
可以看看本项目的wiki。

**Comment by JakeWoki** [comment]
@tiann 看了不是很懂，是不安装Xposed引入[epic](https://github.com/tiann/epic)也可以实现对应拦截和插入代码吗？
