### ISSUE TITLE
VirtualXposed源码运行总是闪退

### ISSUE THREAD

**Issue by dreamstartLZ** [android-hacker/VAExposed#484]
## 问题描述
VirtualXposed源码运行总是闪退

## 复现步骤
直接运行

## 环境
VirtualXposed版本0.16.1

机型：
系统版本：Android8.0  Android7.0
ROM版本：release的0.16.1源码
Xposed 插件以及插件版本：源码里面装的,XposedInstaller_3.1.5.apk_
VirtualXposed版本：0.16.1

## 补充
因为我的手机应用安装器不识别VirtualXposed，所以没办法向VirtualXposed上安装apk，想把apk放在源码里面自动安装

JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IllegalArgumentException
at void java.lang.System.loadLibrary(java.lang.String) (System.java:1657)
at void com.lody.virtual.client.NativeEngine.<clinit>() (NativeEngine.java:38)

System.loadLibrary("va++");

**Comment by dreamstartLZ** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:8.0.0/OPR1.170623.032/1809142043:user/release-keys'
 Revision: '0'
 ABI: 'arm'
 pid: 27327, tid: 27327, name: io.va.exposed  >>> io.va.exposed <<<
 signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
 Abort message: 'java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IllegalArgumentException: '
     r0 00000000  r1 00006abf  r2 00000006  r3 00000008
     r4 00006abf  r5 00006abf  r6 fff04768  r7 0000010c
     r8 00000002  r9 fff047c9  sl 0000000a  fp fff047c8
     ip 00000000  sp fff04758  lr eb75d9a7  pc eb78e10c  cpsr 200f0010
 try findMethod[gamecenter://PackageReceiverRouter/Void_onReceive_Context_Intent], result = null!!
 backtrace:
     #00 pc 0004b10c  /system/lib/libc.so (tgkill+12)
     #01 pc 0001a9a3  /system/lib/libc.so (abort+54)
     #02 pc 00337743  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+230)
     #03 pc 00337dd3  /system/lib/libart.so (_ZN3art7Runtime7AborterEPKc+10)
     #04 pc 003eee2d  /system/lib/libart.so (_ZN7android4base10LogMessageD1Ev+456)
     #05 pc 0022f78b  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1262)
     #06 pc 0022f973  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
     #07 pc 000d263f  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+46)
     #08 pc 000d21d7  /system/lib/libart.so (_ZN3art11ScopedCheck11CheckThreadEP7_JNIEnv+354)
     #09 pc 000d09d5  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+604)
     #10 pc 000bd6c7  /system/lib/libart.so (_ZN3art8CheckJNI9FindClassEP7_JNIEnvPKc+450)
     #11 pc 00048501  /data/app/io.va.exposed-sOAEC_9jd62PGjJ4_JaPug==/lib/arm/libva++.so (_ZN8facebook3jni15findClassStaticEPKc+40)
     #12 pc 0003cb93  /data/app/io.va.exposed-sOAEC_9jd62PGjJ4_JaPug==/lib/arm/libva++.so
     #13 pc 000483c3  /data/app/io.va.exposed-sOAEC_9jd62PGjJ4_JaPug==/lib/arm/libva++.so (_ZN8facebook3jni10initializeEP7_JavaVMONSt6__ndk18functionIFvvEEE+82)
     #14 pc 0003cad5  /data/app/io.va.exposed-sOAEC_9jd62PGjJ4_JaPug==/lib/arm/libva++.so (JNI_OnLoad+64)
     #15 pc 0023172f  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP8_jstringP
     #16 pc 0000319b  /system/lib/libopenjdkjvm.so (JVM_NativeLoad+194)
     #17 pc 00275451  /system/framework/arm/boot-core-oj.oat (offset 0x1d3000) (java.lang.Runtime.nativeLoad+160)
     #18 pc 003dc561  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
     #19 pc 003e0bdb  /system/lib/libart.so (art_quick_invoke_static_stub+226)
     #20 pc 000ac47b  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
     #21 pc 001f1807  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JVa
     #22 pc 001ecdb7  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+574)
     #23 pc 003c7525  /system/lib/libart.so (MterpInvokeStatic+324)
     #24 pc 003ce994  /system/lib/libart.so (ExecuteMterpImpl+14612)
     #25 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #26 pc 001d96bb  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
     #27 pc 001ecda1  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
     #28 pc 003c7329  /system/lib/libart.so (MterpInvokeDirect+360)
     #29 pc 003ce914  /system/lib/libart.so (ExecuteMterpImpl+14484)
     #30 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #31 pc 001d96bb  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
     #32 pc 001ecda1  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
     #33 pc 003c6473  /system/lib/libart.so (MterpInvokeVirtual+446)
     #34 pc 003ce814  /system/lib/libart.so (ExecuteMterpImpl+14228)
     #35 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #36 pc 001d96bb  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
     #37 pc 001ecda1  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
     #38 pc 003c7525  /system/lib/libart.so (MterpInvokeStatic+324)
     #39 pc 003ce994  /system/lib/libart.so (ExecuteMterpImpl+14612)
     #40 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #41 pc 001d9609  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
     #42 pc 003bcbad  /system/lib/libart.so (artQuickToInterpreterBridge+960)
     #43 pc 003e0321  /system/lib/libart.so (art_quick_to_interpreter_bridge+32)
     #44 pc 003dc561  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
     #45 pc 003e0bdb  /system/lib/libart.so (art_quick_invoke_static_stub+226)
     #46 pc 000ac47b  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
     #47 pc 000f550d  /system/lib/libart.so (_ZN3art11ClassLinker15InitializeClassEPNS_6ThreadENS_6HandleINS_6mirror5ClassEEEbb+1784)
     #48 pc 000e3c41  /system/lib/libart.so (_ZN3art11ClassLinker17EnsureInitializedEPNS_6ThreadENS_6HandleINS_6mirror5ClassEEEbb+108)
     #49 pc 001f186f  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JVa
     #50 pc 001ecdb7  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+574)
     #51 pc 003c7525  /system/lib/libart.so (MterpInvokeStatic+324)
     #52 pc 003ce994  /system/lib/libart.so (ExecuteMterpImpl+14612)
     #53 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #54 pc 001d96bb  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
     #55 pc 001ecda1  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
     #56 pc 003c6473  /system/lib/libart.so (MterpInvokeVirtual+446)
     #57 pc 003ce814  /system/lib/libart.so (ExecuteMterpImpl+14228)
     #58 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
     #59 pc 001d96bb  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
     #60 pc 001ecda1  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
     #61 pc 003c6473  /system/lib/libart.so (MterpInvokeVirtual+446)
     #62 pc 003ce814  /system/lib/libart.so (ExecuteMterpImpl+14228)
     #63 pc 001d4339  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)

**Comment by lvlingit** [comment]
同问
