### ISSUE TITLE
编译能通过，但是跑起来的时候直接报错了。error: unknown type name 'RegState'

### ISSUE THREAD

**Issue by manqianzhuang** [android-hacker/VAExposed#486]
F:\WWW\box\starskybbs_app\lib\src\main\jni\HookZz\include\hookzz.h
Error:(132, 25) error: unknown type name 'RegState'
Error:(132, 25) error: unknown type name 'RegState'
Error:(133, 26) error: unknown type name 'RegState'
Error:(134, 26) error: unknown type name 'RegState'

**Comment by SharsDela** [comment]
去掉编译x86版本

**Comment by AbyssSee** [comment]
> 去掉编译x86版本

您好，请问“去掉编译x86版本” 这个具体怎么弄？ 不熟悉C和C++，麻烦指导一下，谢谢。

**Comment by SharsDela** [comment]
lib模块的gradle配置里，目标平台
