### ISSUE TITLE
emulator启动VirtualXposed ，Xposed Installer提示Xposed框架91版已更新，但未激活

### ISSUE THREAD

**Issue by tangxuesong6** [android-hacker/VAExposed#495]
## 问题描述
emulator启动VirtualXposed ，Xposed Installer提示Xposed框架91版已更新，但未激活。

## 复现步骤
将VirtualXposed安装到模拟器，启动，打开Xposed Installer。

## 环境

机型：
系统版本：Android 7.1.1
ROM版本：模拟器 x86
Xposed 插件以及插件版本： version89
VirtualXposed版本：0.16.1

**Comment by tiann** [comment]
不支持  x86
