### ISSUE TITLE
把VX安装在工作模式中无法运行Xposed模块，但可以多开

### ISSUE THREAD

**Issue by zhoujun2** [android-hacker/VAExposed#500]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

把VX安装在工作模式中无法运行Xposed模块，但只能多开。

## 复现步骤

APP Settings中 Manage Xposed Modules点不进去

## 环境

机型：SONY
系统版本：安卓7.0、8.0、9.0都测过
ROM版本：索尼应该很接近原生
Xposed 插件以及插件版本：
VirtualXposed版本：0.16.1

## 补充

工作模式是Island创建的。我没找到日志文件在哪，如果谁能告诉我错误日志位置 我可以上传

**Comment by tiann** [comment]
这样做的意义是什么？

**Comment by zhoujun2** [comment]
我想把VX藏起来，放在企业模式里可以停用app

**Comment by tiann** [comment]
与 Xposed 无关
