### ISSUE TITLE
Twitter登录后闪退

### ISSUE THREAD

**Issue by MiracleXYZ** [android-hacker/VAExposed#502]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

最新版release，安装Twitter并登录后发生闪退，再次尝试进入时卡在Opening界面。

## 复现步骤

1. 从官网下载最新版本release。
2. 安装Twitter：如果从原有的系统中直接克隆（原系统中的Twitter在已登录状态），那么Twitter卡在Opening界面不能进入；如果从Apkpure下载apk安装，登录前界面可以进入，只要输入账号密码登陆成功，即刻闪退，再次打开时卡在Opening界面。

## 环境

机型：Xiaomi MI 8
系统版本：Android 8.1.0
ROM版本：MIUI 10.0 稳定版 10.0.11.0 (OEACNFH)
Xposed 插件以及插件版本：Version 90-beta3
VirtualXposed版本：0.16.0

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
Version 90-beta3 系统有Xposed？
