### ISSUE TITLE
如何使得自制Xposed插件能够用于太极？

### ISSUE THREAD

**Issue by Lua12138** [android-hacker/VAExposed#506]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

因目标App无法在VirtualXposed中使用（目标应用会提示被修改），因此“太极”是更好的非Root解决方案。而当前太极使用的是白名单模式，自制的Xposed插件并不能在太极中开启。

## 希望的解决方案

是否能够开放给开发者能够使得其使用自制Xposed插件？
若在太极插件开发过程中与标准Xposed插件不同，能否说明在开发时的差异性。

## 其他信息

无

**Comment by tiann** [comment]
自制的插件用来干啥的？

**Comment by Lua12138** [comment]
就是一些很小众的app，会自己写一个xposed插件来完成自己的需求。

是否有考虑对开发者开放部分权限呢？
