### ISSUE TITLE
登录支付宝的时候提示“您的操作频率过快，请稍后再试”

### ISSUE THREAD

**Issue by ronghuaxueleng** [android-hacker/VAExposed#517]
## 问题描述

登录支付宝的时候提示“您的操作频率过快，请稍后再试”

## 复现步骤

打开支付宝，输入账号，点击下一步

## 环境

机型：
系统版本：华为荣耀8 
ROM版本：EMUI8
VirtualXposed版本：0.16.1

**Comment by tiann** [comment]
支付宝检测，请自行解决。

**Comment by link-duan** [comment]
请问如何解决，关闭了Xposed仍然无法打开。
提示“您的操作频率过快，请稍后再试”
