### ISSUE TITLE
xp模块支持

### ISSUE THREAD

**Issue by as4234426** [android-hacker/VAExposed#524]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

你好，请问XP下的“钉钉红包-v1.3.6”和“dingPass-V4.0.0”是否支持VXP？望回复

## 希望的解决方案
如果，你无法测试。或者请告知如何把XP下的模块自己加入VXP下。

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
自己测试即可。

**Comment by as4234426** [comment]
创建应用，里面没有钉钉。选择安装包也无法安装。模块里面没有那几个插件，我如何安装？直接把xp手机的插件导出安装？

**Comment by tiann** [comment]
这是太极，不是vxp；你问错地方了。现在太极不支持丁丁。
