### ISSUE TITLE
请问支持系统应用hook吗，比如短信，电话 

### ISSUE THREAD

**Issue by KinaZhen** [android-hacker/VAExposed#532]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述 :我在virtualposed里去hook短信，发现无法hook成功，包名是 com.android.phone

（请尽量详细地描述你遇到的问题）

## 复现步骤 打开短信电话应用，无法hook到

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：华为meta8
系统版本：emui5.1
ROM版本：8.1
Xposed 插件以及插件版本：82
VirtualXposed版本：0.16.1

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不支持
