### ISSUE TITLE
求作者适配最新版森林庄园1.1.3b，1.1.2本身有bug

### ISSUE THREAD

**Issue by swh922** [android-hacker/VAExposed#534]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述
支付宝
(请详细和精确地表述你的使用场景)

## 希望的解决方案
森林庄园1.1.2版本有点bug，1.1.3b已经修复了，求作者适配

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by tiann** [comment]
到家了搞

**Comment by swh922** [comment]
@tiann 谢谢，不胜感激

**Comment by tiann** [comment]
irrelative
