### ISSUE TITLE
Google Play Services on 9.0 (Unable to parse package microG's gms)

### ISSUE THREAD

**Issue by TheArmKing** [android-hacker/VAExposed#536]
**Describe the bug**
Followed the wiki guide on how to install google play services using microG, gms services and fakeStore don't install

**To Reproduce**
1. Download the latest gms apk [[link](https://microg.org/download.html)]
2. Click on the APK
3. Click Add to Exposed
4. Click Install

**Expected behavior**
The gms service app and fakeStore should install so that Google Play Services can be used!

**Screenshots**
![screenshot_20190207-212725](https://user-images.githubusercontent.com/41083078/52417772-33875b00-2b1f-11e9-837a-8dd4850455a3.png)

**Desktop:**
 - OS: 9.0.0 (Pie Jan 2019)
 - Browser None
 - Version Latest

**Smartphone:**
 - Device: Xiaomi Mi A1
 - OS: 9.0.0 (Pie Jan 2019)
 - Browser NONE
 - Version Latest

**Comment by 1217965058** [comment]
我也是，me too

**Comment by mickychenchen** [comment]
Me too, Note8

**Comment by wangxiaolinwxl** [comment]
我也是huawei p20 android 9.0

**Comment by krreet** [comment]
Me too

**Comment by AndnixSH** [comment]
Me too

**Comment by ganeshchk** [comment]
Me too, infinix note 5 , 9.0

**Comment by ghost** [comment]
I got the same problem.

**Comment by gussj** [comment]
I have the same problem.

**Comment by wangfeng35** [comment]
看来都是这个问题

**Comment by tiann** [comment]
should be fixed in https://github.com/android-hacker/VirtualXposed/commit/feaea9e9244fb2d947abfd91b4de68d015fc0e68

**Comment by erikaemma** [comment]
我安装成功了，而且安卓是5.1而不是P

**Comment by mickychenchen** [comment]
請問怎麼下載fixed版的apk?

**Comment by tiann** [comment]
Please wait for next release.
