### ISSUE TITLE
淘宝支付宝闪退 

### ISSUE THREAD

**Issue by zaoqi** [android-hacker/VAExposed#539]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
淘宝支付宝闪退 
## 复现步骤
用酷安安裝並打開
## 环境

机型：GOME 2017M27A /U7
系统版本：7.1.1
ROM版本：稳定版 U7——CHN——GM——00——V1.7
Xposed 插件以及插件版本：/
VirtualXposed版本：0.16.1

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by thouger** [comment]
小红书也闪退

机型：Honor 9 Lite
系统版本：8.0.0
Xposed 插件以及插件版本：/
VirtualXposed版本：0.16.1
