### ISSUE TITLE
vaexposed.weishu.me无法访问 

### ISSUE THREAD

**Issue by 1217965058** [android-hacker/VAExposed#542]
## 问题描述
设置中的插件（eg.文件管理器）现在都无法下载了，我查看了一下源码，在OnlinePlugin.java文件中发现都和这个三级域名有关，我试了一下现在这个三级域名已经无法访问了，但是二级域名weishu.me还是可以访问的，我也从其他地方下载了，但是和适配版本是有区别的，所以能不能提供一下别的下载方式啊？

## 复现步骤

设置页面的权限管理，以及高级设置的安装谷歌服务和文件管理，现在都无法下载了

## 环境
任何环境
机型：一加5
系统版本：9.0
ROM版本：氢9.0.1
Xposed 插件以及插件版本：无
VirtualXposed版本：0.16.1

## 补充
无

**Comment by x9y3zn** [comment]
适配版本的文件管理器好像多一个访问VirtualXposed内部存储位置功能，其他地方下载的文件管理器不能办到。接着我找到了一个能访问VirtualXposed存储路径的方法。先下载个re管理器，然后去设定里面把Zip/Tar默认生成文件夹的路径改为/data/data/io.va.exposed/，接着在re管理器随便压缩一个文件，接着在弹出查看压缩文件，就能直接跳转到VirtualXposed存储路径的位置了。
