### ISSUE TITLE
Stuck on "Opening Xposed Installer..."

### ISSUE THREAD

**Issue by AndnixSH** [android-hacker/VAExposed#544]
**Describe the bug**
Xposed Installer will not open. It gets stuck on Opening Xposed Installer...

**To Reproduce**
1. Open VirtualXposed
2. Swipe up to open app drawer
3. Open Xposed Installer

**Expected behavior**
Xposed Installer should open successfully

**Screenshots**
![screenshot_20190217-153956](https://user-images.githubusercontent.com/40742924/52914606-c7e58080-32ca-11e9-87b8-a9f79e44ba52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0

**Smartphone (please complete the following information):**
 - Device: XZ1
 - OS: 9.0
 - Browser: Chrome
 - Version: 72.0

**Additional context**
I downgraded VirtualXposed to 0.16.1 and the Installer works again

**Comment by FreeDreamWings** [comment]
My honor V9 EMUI9.0Android9.0, also flashed back after opening the xposed installer (vx version 0.17.1), other apps in vx run normally, the xposed installer can be opened normally in 0.16.1.But in the 0.16.1 version, when xprivacylua is used in the xposed installer, other apps in vx will not open properly. All app flashed back.I think it should be android9.0's compatibility issues.

**Comment by Junshan233** [comment]
My XiaoMi 8 ,MIUI 10 Android 9,meets the same bug.

**Comment by TalusL** [comment]
My OnePlus A5000 H2OS Android 9,meets the same bug too.

**Comment by zjszzw** [comment]
same bug
pixel experience9.0

**Comment by tiann** [comment]
should be fixed in https://github.com/android-hacker/VirtualXposed/releases/tag/0.17.2

**Comment by linsui** [comment]
问题仍然存在

## 环境

机型：MI 6
系统版本： 9
ROM版本：PixelExperience
Xposed 插件以及插件版本：无
VirtualXposed版本：0.17.2

## 补充

我使用的是 F-Droid 版本

**Comment by qzztf** [comment]
> 问题仍然存在
> 
> ## 环境
> 机型：MI 6
> 系统版本： 9
> ROM版本：PixelExperience
> Xposed 插件以及插件版本：无
> VirtualXposed版本：0.17.2
> 
> ## 补充
> 我使用的是 F-Droid 版本

我的也一直在打开。
我是米9，安卓版本9. VirtualXposed版本：0.17.2，里面的其他程序可以打开。

**Comment by Shahxad-Akram** [comment]
I am still facing the same bug..

**Comment by MAGNETO903** [comment]
Faced the same. 
Redmi Note 10 S
MIUI Global 13.0.10
Android 12
Downloaded version from here https://github.com/android-hacker/VirtualXposed/releases/tag/0.22.0

**Comment by didiaodanding** [comment]
您好，您的邮件已收到，谢谢。                                    --------李峰
