### ISSUE TITLE
virtualxposed 0.17.2 版本打不开微信

### ISSUE THREAD

**Issue by wangxiaolinwxl** [android-hacker/VAExposed#547]
## 问题描述
在virtualxposed中安装微信微信 7.0.3 for Android 正式版发布无法正常使用
具体表现两有：

1. 使用模拟定位软件模块后微信打不开，从virtualxposed模块中去掉模拟定位软件后即可打开微信
2、从xposed中去掉模拟定位后可以打开微信 ，打开微信-》使用微信号/qq-》输入帐号密码后页面闪退，（微信在不同手机上登录需要有一个验证页面，验证页面打不开就闪退）

## 环境
机型：HUAWEI p20 AL00
系统版本：Android 9.0.0
ROM版本：EMUI 9.0.0
VirtualXposed版本：0.17.2

**Comment by wangxiaolinwxl** [comment]
virtualxposed 0.17.2以前版本也存在 同样的问题

**Comment by wangxiaolinwxl** [comment]
微信旧版本也同样打不开

**Comment by toutzhang** [comment]
是的，微信 6.7.4、7.0.3 登录界面输入账号密码后，点击登录出现登录弹框，然后顶部进度条闪了一下再次回到登录界面。另外，微信主界面的“注册”按钮点击无效。

机型：华为 Honor_V10 BKL-AL20
系统版本：Android 9.0.0
ROM版本：EMUI 9.0.0
VirtualXposed版本：0.17.2

**Comment by wangxiaolinwxl** [comment]
跳转微信验证页面时闪退

**Comment by Shelomi** [comment]
同上，只要使用模拟定位软件模块后企业微信就打不开

机型：华为 P20 Pro
系统版本：Android 9.0.0
ROM版本：EMUI 9.0.0
VirtualXposed版本：0.17.2

**Comment by leafzz** [comment]
一样，华为畅享8.0手机 微信7.0.3登录的时候验证页面闪退，提示 ： java.lang.SecurityException: Requesting code from com.tencent.mm

**Comment by understandyou** [comment]
荣耀v10也是

**Comment by kolvs** [comment]
确实有这样问题，可以在外面先登陆一下微信，然后再次登陆xposed里的微信，就可以了

**Comment by leafzz** [comment]
> 确实有这样问题，可以在外面先登陆一下微信，然后再次登陆xposed里的微信，就可以了

它主要是webview打开安全权限异常，就算能登录了，如果在里面打开任何相关的webview页面一样是闪退

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/v0.17.3

**Comment by libingtong** [comment]
@tiann 
在0.17.3下，跳转微信验证页面时依然闪退。

**Comment by hehex9** [comment]
0.17.3 还是不能登录微信
