### ISSUE TITLE
F-Droid app open as Calculator in VirtualXposed

### ISSUE THREAD

**Issue by AndnixSH** [android-hacker/VAExposed#550]
**Describe the bug**
F-Droid opens as Calculator in VirtualXposed

**To Reproduce**
1. Go to https://f-droid.org/en/
2. Download F-Droid APK
3. Install directly to VirtualXposed
4. Open F-Droid from appdrawer

**Expected behavior**
Open F-Droid as normal, No calculator

**Screenshots**
![screenshot_20190226-135628](https://user-images.githubusercontent.com/40742924/53417847-bbea7480-39d6-11e9-9da8-c5d225ffe943.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0

**Smartphone (please complete the following information):**
 - Device: XZ1
 - OS: 9.0
 - Browser: Chrome
 - Version: 72.0

**Comment by linsui** [comment]
同样的现象，安装 F-Droid 后会同时出现计算器的图标，无论点哪个都会打开计算器

**Comment by CrimsonFork** [comment]
Try typing in 1337

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/v0.17.3
