### ISSUE TITLE
findAndHookMethod方法不执行

### ISSUE THREAD

**Issue by haoxionga** [android-hacker/VAExposed#552]
## 问题描述

 `XposedHelpers.findAndHookMethod方法不执行。`

    if (lpparam.packageName.equals("com.example.testdemo")) {
            Class<?> loadClass = lpparam.classLoader.loadClass("com.example.testdemo.TestBean");
            Method[] methods = loadClass.getMethods();
            if (methods != null && methods.length > 0
                    ) {
                for (Method method : methods) {
                    //该方法执行了，在vituralxposed中的xposed的日志中，已经打印出来了实体类的所有方法
                    XposedBridge.log("获取到方法   " + method.getName());
                }
            }
           //方法存在
            XposedHelpers.findAndHookMethod(loadClass, "getSs", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                   //未打印，未执行
                    XposedBridge.log("设置数据 ");
                    param.setResult(99999);
                }

            });

        }

## 复现步骤

 打开需要hook的app。然后查看xposed中的日志。

## 环境

机型：努比亚z17和荣耀8青春版 PRA-AL00
系统版本：努比亚:android 7.1.1,华为:android7.0
ROM版本：努比亚：nubiaUI v6.0 ，华为：EMUI5.0.1
Xposed 插件以及插件版本：自己手动编写的
VirtualXposed版本：0.17.2

## 补充

 努比亚z17手机在vitrualxposed装过的插件基本没生效的，还有部分定位插件，安装了直接导致vitrualxposed中的软件启动不了

**Comment by zhouqihao** [comment]
无
