### ISSUE TITLE
在华为Nexus 6P无法启动微信

### ISSUE THREAD

**Issue by ericliyanghui** [android-hacker/VAExposed#554]
## 问题描述
在nexus 6P中安装从酷安下的微信7.0.3，想结合微信学英语，
一开始装微信可以正常启动，装好Xposed Module并用VirtualXposed的reboot后，打开微信就黑屏，死机。

## 复现步骤
1. 打开VirtualXposed，使用Settings中的Add App将从酷安下载的wechat 7.0.3以及微信学英语1.7.4添加进来，在Manage Xposed Module中看到有微信学英语的Module，并打上勾。
2. 使用VirtualXposed Settings中的Reboot重启。
3. 在VirtualXposed中打开wechat，手机卡死，黑屏。

## 环境
机型：华为 Nexus 6P
系统版本：Android 7.1.2
ROM版本：稳定版
Xposed 插件以及插件版本：
插件：微信学英语（https://www.coolapk.com/apk/com.hiwechart.translate）
插件版本：v1.7.4
VirtualXposed版本：0.17.1

## 补充
log如下：
03-01 18:50:04.475 I/VClientImpl(28480): Binding application com.tencent.mm, (com.tencent.mm)
03-01 18:50:04.581 I/VClientImpl(28480): Xposed is enabled.
03-01 18:50:04.593 I/ExposedBridge(28480): com.tencent.mm is not a Xposed module, do not init epic.force
03-01 18:50:04.598 I/Runtime (28480): is64Bit: false, isArt: true, forceHook: false
03-01 18:50:04.599 I/EpicNative(28480): use unsafe ? false nativeOffset: 28
03-01 18:50:04.605 I/ExposedBridge(28480): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/com.hiwechart.translate/base.apk for process: com.tencent.mm i s c: false
03-01 18:50:04.657 I/ExposedBridge(28480):   Loading class com.hkdrjxy.wechart.xposed.XposedInit
03-01 18:50:04.665 I/Xposed  (28480): hook success: com.tencent.mm  P:com.tencent.mm
03-01 18:50:04.669 I/Xposed  (28480): Loaded app: com.tencent.mm 7.0.3
03-01 18:50:04.670 I/Xposed  (28480): hooks=com.hkdrjxy.wechart.xposed.hooks.p@b6d73ba
03-01 18:50:04.675 I/Xposed  (28480): hooks uid:10002
03-01 18:50:04.685 I/ExposedBridge(28480): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-01 18:50:04.685 I/ExposedBridge(28480): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
03-01 18:50:04.685 I/ExposedBridge(28480): module:/data/user/0/io.va.exposed/virtual/data/app/x.hook.emojihook/base.apk is disabled, ignore

**Comment by ericliyanghui** [comment]
我换了平板解决了，应该是配置不行，毕竟600的机

**Comment by tiann** [comment]
#547
