### ISSUE TITLE
x

### ISSUE THREAD

**Issue by 15565201312** [android-hacker/VAExposed#557]
## 问题描述

 在使用小米Android9.0使用扫码加好友提示 查找失败 ，还有就是在手机保存的图片和视频，然后使用微信找不到。

## 复现步骤

打开微信 ， 保存二维码， 找不到图片，
打开微信，扫码二维码， 查找失败。
## 环境

机型：小米  Redmi 6 Pro
系统版本：Android9.0
ROM版本：MIUI 10 9.21|开发版
Xposed 插件以及插件版本：2.1.5
VirtualXposed版本：0.17.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
关闭存储重定向。

**Comment by 15565201312** [comment]
> 关闭存储重定向。

我关闭存储重定向了， 图片还是没办法保存，
