### ISSUE TITLE
 🐛支付宝安装之后无法登陆，提示您的操作过于频繁

### ISSUE THREAD

**Issue by jzsplk** [android-hacker/VAExposed#558]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

支付宝在环境中无法登陆，提示您的操作过于频繁

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）
1. 在virtualXposed中安装支付宝
2. 登陆支付宝，输入支付宝手机号，点击下一步
3. 支付宝提示您的操作过于频繁，登陆过程被阻断

**Comment by tiann** [comment]
支付宝的安全策略，请自行处理。

**Comment by 282144757** [comment]
@jzsplk 你解决这个问题了吗？

**Comment by 1761630764** [comment]
为啥vmos可以登录
