### ISSUE TITLE
钉钉 v4.6.17 点「签到」「考勤打卡」闪退重启

### ISSUE THREAD

**Issue by yizhichaye** [android-hacker/VAExposed#559]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

钉钉 v4.6.17 点「签到」「考勤打卡」闪退重启

## 复现步骤

每次点击，都是闪退重启，进入到「消息」页面；

## 环境

机型：坚果pro2 os105
系统版本：Android 7.1.1
ROM版本：v6.1.3 官方
Xposed 插件以及插件版本：dingPass v4.1.0
VirtualXposed版本：0.17.2

## 补充

我先在 VirtualXposed 安装了插件 dingPass 模块，并在Xposed 中，打勾；
然后安装 钉钉最新版，v4.6.17，登陆自己的账号，尝试在异地打卡；
在钉钉中，点击「考勤打卡」，弹出加载动画 - 黑屏 - 退出并重启了钉钉 - 进入了消息界面；
以上；

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by CongAn** [comment]
无意中点击进来，看到 @yizhichaye 说的话表示不尊重作者。

**Comment by tiann** [comment]
钉钉检测环境，VirtualXposed 本身不会做这种对抗。
