### ISSUE TITLE
XPrivacyLua安装后里面为空白，没有任何显示

### ISSUE THREAD

**Issue by kettly1260** [android-hacker/VAExposed#560]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

XPrivacyLua安装后里面为空白，没有任何显示，安装版本为1.24最新版，在框架中开启并重启后，XPrivacyLua提示模块未运行或未更新，而且没有任何已安装软件的显示

## 复现步骤

安装可重现

## 环境

机型：HUAWEI P10
系统版本：EMUI9/Android 9.0.1
ROM版本：9.0.1.150
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by wangfeng35** [comment]
直接崩溃打不开

**Comment by fy5220** [comment]
安装1.2.5版本一样闪退
