### ISSUE TITLE
某些使用tinker 热更新的应用程序无法打开

### ISSUE THREAD

**Issue by 2821840032** [android-hacker/VAExposed#561]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

在使用云闪付 Hook的时候发现Application 没有执行onCreate
似乎有些特殊操作 让他崩溃退出
微信也是用的tinker  为什么他的能打开？？
在真机上测试出现 模拟器没有测试

## 复现步骤

安装 -> run -> BUG

## 环境

机型：
系统版本：8.1.0  5.0.2
ROM版本：MIUI9.6 |稳定版  EMUI 3.1.1
Xposed 插件以及插件版本：
VirtualXposed版本：
0.17.1
## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
与 tinker 无关，云闪付检测环境。
