### ISSUE TITLE
0.17.2按照wiki下载源码编译安装后“管理模块”打开失败

### ISSUE THREAD

**Issue by shanzhijian** [android-hacker/VAExposed#566]
## 问题描述

按照wifi描述下载源码，更新到0.17.2，编译完成后安装VirtualXposed，设置中打开“模块管理”失败

## 复现步骤

按照wifi描述下载源码，更新到0.17.2，编译完成后安装VirtualXposed，设置中打开“模块管理”失败

## 环境

机型：谷歌Pix2
系统版本：Android9.0
ROM版本：稳定版
Xposed 插件以及插件版本：无
VirtualXposed版本：0.17.2

## 补充

03-26 10:28:16.265 28473 28473 W System.err: java.lang.ExceptionInInitializerError
03-26 10:28:16.265 28473 28473 W System.err: 	at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(ArtMethod.java:383)
03-26 10:28:16.265 28473 28473 W System.err: 	at com.taobao.android.dexposed.utility.Runtime.isThumb2(Runtime.java:49)
03-26 10:28:16.265 28473 28473 W System.err: 	at me.weishu.epic.art.Epic.<clinit>(Epic.java:69)
03-26 10:28:16.265 28473 28473 W System.err: 	at me.weishu.epic.art.Epic.hookMethod(Epic.java:87)
03-26 10:28:16.265 28473 28473 W System.err: 	at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:144)
03-26 10:28:16.265 28473 28473 W System.err: 	at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:183)
03-26 10:28:16.265 28473 28473 W System.err: 	at me.weishu.exposed.ExposedBridge.initForXposedInstaller(ExposedBridge.java:239)
03-26 10:28:16.265 28473 28473 W System.err: 	at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:84)
03-26 10:28:16.266 28473 28473 W System.err: 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:333)
03-26 10:28:16.266 28473 28473 W System.err: 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214)
03-26 10:28:16.266 28473 28473 W System.err: 	at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:209)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:146)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.os.Looper.loop(Looper.java:193)
03-26 10:28:16.266 28473 28473 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-26 10:28:16.266 28473 28473 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 10:28:16.267 28473 28473 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-26 10:28:16.267 28473 28473 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-26 10:28:16.267 28473 28473 W System.err: Caused by: java.lang.RuntimeException: API LEVEL: 28 is not supported now : (
03-26 10:28:16.267 28473 28473 W System.err: 	at me.weishu.epic.art.method.Offset.initFields(Offset.java:116)
03-26 10:28:16.267 28473 28473 W System.err: 	at me.weishu.epic.art.method.Offset.<clinit>(Offset.java:49)
03-26 10:28:16.267 28473 28473 W System.err: 	... 23 more
03-26 10:28:16.267 28473 28473 D AndroidRuntime: Shutting down VM

**Comment by Bocheng2000** [comment]
Version 0.17.3 has the same problem .
