### ISSUE TITLE
无法安装 microG

### ISSUE THREAD

**Issue by Sylphinford** [android-hacker/VAExposed#571]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
microG 的谷歌服务装不上

## 复现步骤
设置里安装谷歌服务
显示失败，跳转到网页手动安装教程
下载最新的gms, 文件名com.google.android.gms-13280012.apk
在VXP里安装
安装失败，显示错误 unable to parse the package

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：小米mix2s
系统版本：9 PKQ1.1 80729.001
ROM版本：MIUI Global10.2 |稳定版10.2.2.0(PDGMIXM)（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本： 91
VirtualXposed版本：0.17.2

## 补充
microg 上 FakeStore 也装不上，同样的错误信息
（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
#536
