### ISSUE TITLE
如何使用Google登陆？

### ISSUE THREAD

**Issue by erikaemma** [android-hacker/VAExposed#576]
## 问题描述

已经按照wiki手动安装了google服务。想要用google登陆tik tok美服。
## 复现步骤

点击无反应

## 环境

机型：
系统版本：vivo x6s plusd
ROM版本：5.1
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.2

## 补充

其他抖音问题：
edit profile闪退，无论日服还是美服都是如此

**Comment by tiann** [comment]
#536
