### ISSUE TITLE
无法调用外部facebook和line实现第三方登陆

### ISSUE THREAD

**Issue by erikaemma** [android-hacker/VAExposed#577]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

facebook登陆提示invalid key。百度了一下说是facebook的key分debug和release，不知道在xp中是否调用了debug版本的key？
line的话无法调用外部已安装的app，自动打开了网页登陆，但是网页登陆后又无法跳回app所以导致登陆失败（实际line已经提示登陆成功了）

## 复现步骤

google play下载的，日服和美服（新加坡节点）下载的。

## 环境

机型：vivo x6s plus d 
系统版本：5.1
ROM版本：5.1
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.2

## 补充

其他抖音问题：两个版本都是，edit profile闪退。不是vx闪退，是内部的抖音闪退

**Comment by tiann** [comment]
你只能把app加到里面来才可以
