### ISSUE TITLE
无法hook 分身应用，不知道算不算bug，还是限制问题？

### ISSUE THREAD

**Issue by THROFHR** [android-hacker/VAExposed#579]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

首先我在xposed里安装了一个支付宝。
然后，写了个hook，它能work。
接着，安装了支付宝的分身，启动第二个支付宝，并没有hook成功，第一个支付宝还正常hook。

## 复现步骤

首先在xposed里安装了一个支付宝。
安装支付宝hook插件
安装了支付宝的分身。
启动第二个支付宝，并没有hook成功，第一个支付宝还正常hook。

## 环境

机型：ONEPLUS A3000
系统版本：Android 8.0.0
ROM版本：H2OS 版本  OP3_H2_BEAT_37
Xposed 插件以及插件版本：Xposed3.1.5
VirtualXposed版本：0.17.2

## 补充

```
findAndHookMethod("android.app.Activity",lpparam.classLoader,"onCreate",Bundle.class,new XC_MethodHook() {
    @Override
    protected void afterHookedMethod(MethodHookParam param) throws Throwable {
        super.afterHookedMethod(param);
        Activity activity = (Activity)param.thisObject;
        Toast.makeText(activity,"啦啦啦",Toast.LENGTH_LONG);
    }
});
```
插件是自己写的，就一个Toast。

同一应用只有第一个应用会hook成功。

### 想问一下，这个是否是VA的限制，是否有方法解决？

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
有办法解决

**Comment by THROFHR** [comment]
> 有办法解决

是否能简单讲一下，怎么才能hook 分身应用
