### ISSUE TITLE
VirtualXposed 中的 XposedInstaller 3.1.5分支是哪个？

### ISSUE THREAD

**Issue by THROFHR** [android-hacker/VAExposed#580]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

VirtualXposed 中的 XposedInstaller 3.1.5 的源代码是哪个版本/分支？
我编译了最新版本的 [XposedInstaller]( https://github.com/rovo89/XposedInstaller)，发现它好像不起作用，所有的插件都不工作。

## 希望的解决方案

我想知道哪个版本的XposedInstaller编译后能在VirtualXposed中正常工作。

## 其他信息

(其他你认为有用的信息)

**Comment by shanzhijian** [comment]
是没有安装吧，VirtualXposed源码里，安装XposedInstaller是要验证MD5的，自己编译的可能安装不上去：
if ("8537fb219128ead3436cc19ff35cfb2e".equals(MD5Utils.getFileMD5String(xposedInstallerApk)))

**Comment by THROFHR** [comment]
> 是没有安装吧，VirtualXposed源码里，安装XposedInstaller是要验证MD5的，自己编译的可能安装不上去：
> if ("8537fb219128ead3436cc19ff35cfb2e".equals(MD5Utils.getFileMD5String(xposedInstallerApk)))

不是没安装，我是想自己编译一个，我用了XposedInstaller的源码编译出来的那个版本不能工作

**Comment by tiann** [comment]
这个 organization 下面有一个 XposedInstaller。

**Comment by THROFHR** [comment]
> 这个 organization 下面有一个 XposedInstaller。

谢谢提醒，我有在wiki中看到。但是我不是想要XposedInstaller 3.1.5 的安装包，我是想自己编译一个。
我看到XposedInstaller是开源的，但是没找到对应的在VXP分支，我直接编译了XposedInstaller代码（ https://github.com/rovo89/XposedInstaller/tree/master ）。 发现它在VXP中不工作，我想问下VXP中XposedInstaller_3.1.5是否有开源？有的话对应的是那个提交，我是想自己编译一个。

**Comment by THROFHR** [comment]
> 这个 organization 下面有一个 XposedInstaller。

不好意思，一开始没反应过来。现在做个mark XposedInstaller https://github.com/android-hacker/XposedInstaller/
感谢weishu
