### ISSUE TITLE
微信7.0.3登录输入账户密码闪退

### ISSUE THREAD

**Issue by leafzz** [android-hacker/VAExposed#581]
## 问题描述
微信7.0.3登录输入账户密码闪退
提示 ： java.lang.SecurityException: Requesting code from com.tencent.mm

## 环境

机型：华为 Honor_V10 BKL-AL20
系统版本：Android 8.0.0
ROM版本：EMUI 8.0.0
VirtualXposed版本：0.17.2

**Comment by zy990081568** [comment]
请问这个是怎么解决的?
