### ISSUE TITLE
红米note5在更新底层为安卓9.0以后无法正常启动应用

### ISSUE THREAD

**Issue by Teages** [android-hacker/VAExposed#585]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

红米note5在更新安卓9.0后完全无法启动主程序（即进入VirtualXposed桌面）

## 复现步骤

在桌面点击VirtualXposed的图标
（显示VirtualXposed第一屏）
（VirtualXposed自动关闭）

## 环境

机型：红米note5pro
系统版本：Android
ROM版本：MIUI国际版9.4.1
Xposed 插件以及插件版本：未安装
VirtualXposed版本：0.17.3及之前所有发布版本

## 补充

1. 现在状态栏偶尔会冒一句“'VirtualXposed'正在运行”

2. 【异常】即使VirtualXposed多次异常退出，但MIUI未弹出错误反馈，所以我无法提供日志

3. 在前面底层为安卓8.1的MIUI中，VirtualXposed未出现任何异常

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by afteragain** [comment]
国内开发版也一样，闪退

**Comment by Teages** [comment]
发现和下列问题相同
#568
似乎最近上预装或更新上Android P的MIUI设备都出现了这个问题
怀疑与最近MIUI对Android P的魔改有关
其他基于VirtualApp的开源应用经测试也无法正常启动

**Comment by tiann** [comment]
@Teages 设置-高级设置-关闭Xposed 之后能否打开？

**Comment by afteragain** [comment]
> @Teages 设置-高级设置-关闭Xposed 之后能否打开？

是VXP闪退了，不是里面的软件闪退，所以，看不到vxp里面的界面和设置

**Comment by Teages** [comment]
@tiann 主程序直接闪退，尝试用软件调出vxp设置也是闪退，什么清除都做过了

**Comment by Teages** [comment]
@tiann  在MIUI国际开发版9.4.12的更新后，软件已恢复正常

**Comment by Teages** [comment]
@tiann 现在状态是：刚刚突然打开一次，退出后再打开又闪退了，目前和原来状态差不多

**Comment by Teages** [comment]
目前偶尔打开后，可以进入桌面和设置，但是安装软件提示成功但是vxp桌面不显示，xp插件管理也打不开

**Comment by cherrysakurali** [comment]
同为红米note5 安卓9.0 miui10 9.4.18。也是闪退。

**Comment by cicirori** [comment]
mi6 miui 开发版 9.5.9 安卓p 闪退

**Comment by kkkpc** [comment]
MIUI p都闪退 貌似有人给出方案了
作者也close issue了 期望早点发布新版本
目前只能用sandvxposed在p下撑着不闪退  但是那个ui没有vxp好

**Comment by gitskystar** [comment]
MI 8SE更新了系统后闪退 MIUI 10.3.1.0  
Android 9

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
