### ISSUE TITLE
ERROR: Failed to resolve: me.weishu.exposed:exposed-core:0.7.5

### ISSUE THREAD

**Issue by denkazzzget** [android-hacker/VAExposed#587]
**Describe the bug**
Getting `ERROR: Failed to resolve: me.weishu.exposed:exposed-core:0.7.5` after build syncing.

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Browser: -
 - Version: 0.17.3

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -
 - Version: -

**Additional context**
-

**Comment by jiafuzhang** [comment]
我也遇到同样的问题，环境和情况差不多一样

**Comment by owen5586331** [comment]
最新 vxp分支的 me.weishu.exposed:exposed-core:0.7.7-c 拉不下来

**Comment by owen5586331** [comment]
换 me.weishu.exposed:exposed-core:0.+ 编译成功
