### ISSUE TITLE
Xprivacylua 在android pie無法運作

### ISSUE THREAD

**Issue by mickychenchen** [android-hacker/VAExposed#588]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

套用xprivacylua的app都會卡在loading
無法運行

## 复现步骤

1. 開啟xprivacylua
2. 對任一app勾選限制
3. 開啟該app

## 环境

机型：Samsung Note8
系统版本：9.0
ROM版本：原廠
Xposed 插件以及插件版本：xprivacylua 1.24
VirtualXposed版本：0.17.3

## 补充

04-07 00:29:06.711 I/VClientImpl(10030): Binding application eu.faircode.xlua, (eu.faircode.xlua)
04-07 00:29:06.724 I/VClientImpl(10030): Xposed is enabled.
04-07 00:29:06.803 I/ExposedBridge(10030): module:/data/user/0/io.va.exposed/virtual/data/app/com.beattheq.android/base.apk is disabled, ignore
04-07 00:29:06.803 I/ExposedBridge(10030): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
04-07 00:29:06.803 I/ExposedBridge(10030): module:/data/user/0/io.va.exposed/virtual/data/app/com.android.vending/base.apk is disabled, ignore
04-07 00:29:06.803 I/ExposedBridge(10030): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk is disabled, ignore
04-07 00:29:06.804 I/ExposedBridge(10030): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gsf/base.apk is disabled, ignore
04-07 00:29:06.804 I/ExposedBridge(10030): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/eu.faircode.xlua/base.apk for process: eu.faircode.xlua i s c: false
04-07 00:29:06.828 I/ExposedBridge(10030):   Loading class eu.faircode.xlua.XLua
04-07 00:29:06.837 I/ExposedBridge(10030): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/com.thermatk.android.xf.fakegapps/base.apk for process: eu.faircode.xlua i s c: false
04-07 00:29:06.844 I/ExposedBridge(10030):   Loading class com.thermatk.android.xf.fakegapps.FakeSignatures
04-07 00:29:06.848 I/Runtime (10030): is64Bit: false, isArt: true, forceHook: true
04-07 00:29:06.849 I/EpicNative(10030): use unsafe ? false nativeOffset: 20
04-07 00:29:25.263 I/VClientImpl(10131): Binding application com.beattheq.android, (com.beattheq.android)
04-07 00:29:25.278 I/VClientImpl(10131): Xposed is enabled.
04-07 00:29:25.879 I/ExposedBridge(10131): com.beattheq.android is not a Xposed module, do not init epic.force
04-07 00:29:25.880 I/ExposedBridge(10131): module:/data/user/0/io.va.exposed/virtual/data/app/com.beattheq.android/base.apk is disabled, ignore
04-07 00:29:25.880 I/ExposedBridge(10131): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
04-07 00:29:25.881 I/ExposedBridge(10131): module:/data/user/0/io.va.exposed/virtual/data/app/com.android.vending/base.apk is disabled, ignore
04-07 00:29:25.881 I/ExposedBridge(10131): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk is disabled, ignore
04-07 00:29:25.881 I/ExposedBridge(10131): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gsf/base.apk is disabled, ignore
04-07 00:29:25.881 I/ExposedBridge(10131): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/eu.faircode.xlua/base.apk for process: com.beattheq.android i s c: false
04-07 00:29:25.905 I/ExposedBridge(10131):   Loading class eu.faircode.xlua.XLua
04-07 00:29:25.917 I/Runtime (10131): is64Bit: false, isArt: true, forceHook: false
04-07 00:29:25.917 I/EpicNative(10131): use unsafe ? false nativeOffset: 20
04-07 00:29:25.920 I/ExposedBridge(10131): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/com.thermatk.android.xf.fakegapps/base.apk for process: com.beattheq.android i s c: false
04-07 00:29:25.927 I/ExposedBridge(10131):   Loading class com.thermatk.android.xf.fakegapps.FakeSignatures
04-07 00:29:38.794 I/VClientImpl(10261): Binding application com.beattheq.android, (com.beattheq.android)
04-07 00:29:38.808 I/VClientImpl(10261): Xposed is enabled.
04-07 00:29:39.387 I/ExposedBridge(10261): com.beattheq.android is not a Xposed module, do not init epic.force
04-07 00:29:39.388 I/ExposedBridge(10261): module:/data/user/0/io.va.exposed/virtual/data/app/com.beattheq.android/base.apk is disabled, ignore
04-07 00:29:39.389 I/ExposedBridge(10261): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
04-07 00:29:39.389 I/ExposedBridge(10261): module:/data/user/0/io.va.exposed/virtual/data/app/com.android.vending/base.apk is disabled, ignore
04-07 00:29:39.389 I/ExposedBridge(10261): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk is disabled, ignore
04-07 00:29:39.389 I/ExposedBridge(10261): module:/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gsf/base.apk is disabled, ignore
04-07 00:29:39.389 I/ExposedBridge(10261): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/eu.faircode.xlua/base.apk for process: com.beattheq.android i s c: false
04-07 00:29:39.414 I/ExposedBridge(10261):   Loading class eu.faircode.xlua.XLua
04-07 00:29:39.426 I/Runtime (10261): is64Bit: false, isArt: true, forceHook: false
04-07 00:29:39.426 I/EpicNative(10261): use unsafe ? false nativeOffset: 20
04-07 00:29:39.429 I/ExposedBridge(10261): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/com.thermatk.android.xf.fakegapps/base.apk for process: com.beattheq.android i s c: false
04-07 00:29:39.435 I/ExposedBridge(10261):   Loading class com.thermatk.android.xf.fakegapps.FakeSignatures

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.0
