### ISSUE TITLE
Google Play Games instantly crash on launch

### ISSUE THREAD

**Issue by AndnixSH** [android-hacker/VAExposed#589]
**Describe the bug**
The app Google Play Games instantly crashes when launching it and the games what require Play It also instant crash when games attempt to request it to login. Google Service is already added

**To Reproduce**
1. Download Google Play Games from Play Store
2. Open Setings ->Advance Settings -> Add Google Service
3. Then Add App and install Google Play Games to VirtualXposed.
(If you don't see Play Games, that's because it was installed as system app. Backup apk to sdcard using APK backup app or similar then you can do Settings -> Add App -> Click blue plus button and select apk to install)
4. Open Google Play Games

**Expected behavior**
It is expected to open and ask for login if not logged in
In games, it's also expected to show green box Google Play Games logo when the game request it to appear

**Screenshots**
I don't think it's needed in this case

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 73.0.3683.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Sony XZ1
 - OS: Android 9.0
 - Browser Chrome
 - Version 73.0.3683.75 (Official Build) (64-bit)

**Additional context**
Logcat:
[VirtualXposed logcat.txt](https://github.com/android-hacker/VirtualXposed/files/3053935/VirtualXposed.logcat.txt)

**Comment by tiann** [comment]
Setings - Advance Settings - Add Google Service

**Comment by AndnixSH** [comment]
@tiann Already added Google Service before i install Google Play Games. Edited the issue

**Comment by yin2na** [comment]
I have the same problem@tiann

**Comment by vlt23** [comment]
Current microG doesn't have a game API implementation so Google Play Games will crash. Check: [https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status](url)

**Comment by vlt23** [comment]
Sorry, the url doesn't work, copy and paste in your browser...

**Comment by AndnixSH** [comment]
Lol really. RIP unsigned APK for non-rooted devices XD

Reference: https://github.com/microg/android_packages_apps_GmsCore/issues/163

**Comment by AndnixSH** [comment]
Reference https://github.com/microg/android_packages_apps_GmsCore/issues/163

**Comment by ghost** [comment]
same problem

**Comment by ghost** [comment]
I have the same problem too
Parralel space fully support Google services and Google Play Games, why not VirtualXposed??

**Comment by AndnixSH** [comment]
Workaround is to use VM for now using VMOS. Official Google services working perfectly on it and it can be rooted. My dream became true lol
This project is dead anyway

https://www.vmos.com/

**Comment by ghost** [comment]
Yes dead developers. they can't use Google Services even Parallel space and others can but some apps can't run so VMOS is best way for now

**Comment by ghost** [comment]
I'm surprised you can actually run VM on an Android devicee
it's working great, uninstalled VX because too buggy

**Comment by MujurID** [comment]
> Workaround is to use VM for now using VMOS. Official Google services working perfectly on it and it can be rooted. My dream became true lol
> This project is dead anyway
> 
> https://www.vmos.com/

thanks!
