### ISSUE TITLE
请问最新的三个版本有什么区别要具体怎么用以及老版本升级使用哪个版本？

### ISSUE THREAD

**Issue by erikaemma** [android-hacker/VAExposed#591]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

好比新发布了一款药然后告诉病人具体治什么病的你自己去试一试。。。建议能够完善README或者再Releases界面或者changelog详细说明一下新版本的变化

## 希望的解决方案

好比新发布了一款药然后告诉病人具体治什么病的你自己去试一试。。。建议能够完善README或者再Releases界面或者changelog详细说明一下新版本的变化

## 其他信息

好比新发布了一款药然后告诉病人具体治什么病的你自己去试一试。。。建议能够完善README或者再Releases界面或者changelog详细说明一下新版本的变化

**Comment by tiann** [comment]
文件名已经能说明问题了，为什么还要多此一举呢？

for_GameGuardian 给使用 GameGuardian 使用的。
FDROID 给 F-Droid 这个商店用的。
AOSP 普通的版本。

三个版本没有本质区别，F-Droid 去掉了 Fabric 统计，仅此而已。

PS: 为了避免麻烦，以后我自己只会发布 AOSP 和 GameGuardian 版本。

**Comment by erikaemma** [comment]
> 文件名已经能说明问题了，为什么还要多此一举呢？
> 
> for_GameGuardian 给使用 GameGuardian 使用的。
> FDROID 给 F-Droid 这个商店用的。
> AOSP 普通的版本。
> 
> 三个版本没有本质区别，F-Droid 去掉了 Fabric 统计，仅此而已。
> 
> PS: 为了避免麻烦，以后我自己只会发布 AOSP 和 GameGuardian 版本。

因为不是安卓开发从业者，谢谢解答
