### ISSUE TITLE
按照官方的方法双开微信后无法打开微信，打开即闪退

### ISSUE THREAD

**Issue by Winyer** [android-hacker/VAExposed#594]
## 问题描述

按照官方的方法双开微信后无法打开微信，打开即闪退，切换低版本VXP后也一样，不过低版本会提示一个太极被后台清理，建议将太极加入忽略电池优化，事实上太极活的好好的，该设置的也已经设置了，尝试了切换多个版本以及信任应用和双开相关插件后均无效。

## 复现步骤

首先正确安装太极和插件并从太极安装微信，确保微信能正常打开，然后下载VXP，关闭VXP自带的XP框架，然后添加微信，再然后打开微信，直接闪退。

## 环境

机型：荣耀 V10
系统版本：8.0.0
ROM版本：8.0.0.204
Xposed 插件以及插件版本：畅玩微信（1889版本），MDWechat（3.4.0版本），微X模块（1.25版本）
VirtualXposed版本：0.17.3

## 补充

（无）

**Comment by libingtong** [comment]
这里不是太极的项目啊！
