### ISSUE TITLE
Whatsapp is not working

### ISSUE THREAD

**Issue by uPenguin** [android-hacker/VAExposed#599]
**Describe the bug**
After installing Whatsapp it is not possible to launch it, google service is correctly installed.

**To Reproduce**
1. Using Yalp Store, Aurora Store, or "Add App" and clone the installed Whatsapp apk
2. Launch the APK
3. See error

**Expected behavior**
Launch Whatsapp without error.

**Screenshots**
https://postimg.cc/S2LT8RNs

**Smartphone (please complete the following information):**
 - Device: SAMSUNG S8
 - OS: Stock 9.0

**Additional context**
Latest version of VirtualXposed, latest version of Whatsapp
Module installed : FakeGapps, XPrivacyLUA (but no restriction activated for Whatsapp)

**Comment by hemantp66** [comment]
any solution??

**Comment by faitno** [comment]
still any solution?
