### ISSUE TITLE
VirtualXposed 里面的APP打不开

### ISSUE THREAD

**Issue by 456vv** [android-hacker/VAExposed#600]
## 问题描述
VirtualXposed 内部的 xposed 和其它APP都打不开。打开xposed，一直显示在“Opening Xposed installer...”

## 复现步骤
每次

## 环境

机型：一加5T
系统版本：OxygenOS 9.0.4
ROM版本：9
Xposed 插件以及插件版本：?
VirtualXposed版本：VirtualXposed_0.17.3

## 补充
1，我的手机有安装riru-core Magisk和 EdXposed
2，我在手机系统自带的“应用双开”，又开了微信。
不知以上操作会不会冲突造成VirtualXposed不能使用的原因。

**Comment by xingxiang1989** [comment]
我也出现这种情况，我用了OPPO R11来安装virtual Xposed，但是没有虚拟键来安装其他的应用。你是怎么操作的
