### ISSUE TITLE
在0.17.3版本下依然无法登录微信

### ISSUE THREAD

**Issue by libingtong** [android-hacker/VAExposed#601]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

与之前版本一样，使用VirtualXposed 0.17.3安装微信7.0.3和7.0.4后，登录时依然无法弹出webview，无法登录微信。

## 复现步骤

VirtualXposed 0.17.3中正常安装微信7.0.3，输入用户名密码登录后，无法跳转到微信验证页面。

## 环境

机型：华为Mate 20 Pro（LYA-AL00）
系统版本：9.9.9.201
ROM版本：9.0.0
Xposed 插件以及插件版本：未安装插件
VirtualXposed版本：0.17.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.0
