### ISSUE TITLE
我使用Oppo R11，没有虚拟键，无法添加应用。是我使用的不对吗？

### ISSUE THREAD

**Issue by xingxiang1989** [android-hacker/VAExposed#607]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by LooEv** [comment]
一样的问题，安装 VirtualXposed 之后，添加新的应用根本没有反应（不是克隆，是安装系统未安装的app或者模块）
