### ISSUE TITLE
xposed edge5.4.2运行失败

### ISSUE THREAD

**Issue by zc1248856165** [android-hacker/VAExposed#609]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
xposed edge模块运行失败
（请尽量详细地描述你遇到的问题）

## 复现步骤
勾选模块后重启VirtualXposed,打开软件加载不出来应用主界面
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：三星s10+
系统版本：9.0
ROM版本：国行原版系统（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：xposed edge5.4.2,xposed edge pro5.4.2
VirtualXposed版本：0.17.3

## 补充
目前VirtualXposed是否支持此模块
（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不支持也无法支持此模块，可以使用太极+Magisk
