### ISSUE TITLE
VirtualXposed打开微信显示启动失败

### ISSUE THREAD

**Issue by 15565201312** [android-hacker/VAExposed#611]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
VirtualXposed打开微信显示启动失败
华为手机：华为荣耀9型号：DUB-AL00 
版本号：DUB-AL00 8.2.0.172（C00）
EMUI版本：8.2.0 
Android版本8.1.0

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/1ab205cf208d58e1a72dca620051d0f006fb4139
