### ISSUE TITLE
R.string.about_donate哪来的？整个项目都找不到

### ISSUE THREAD

**Issue by weimingjue** [android-hacker/VAExposed#618]
**Describe the bug**
io.virtualapp.home.NewHomeActivity的264行
.setTitle（R.string.about_donate）
搜索了整个库都没有这个字符串

**To Reproduce**
无

**Expected behavior**
无

**Screenshots**
无
**Desktop (please complete the following information):**
无

**Smartphone (please complete the following information):**
无
**Additional context**
无

**Comment by tiann** [comment]
请仔细阅读 wiki
