### ISSUE TITLE
你好, 请问代码可以商用吗?

### ISSUE THREAD

**Issue by badboy-tian** [android-hacker/VAExposed#620]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

你好, 请问代码可以商用吗?

## 希望的解决方案

你好, 请问代码可以商用吗?

## 其他信息

你好, 请问代码可以商用吗?

**Comment by 687766616e** [comment]
让我来替各位说吧！
### **FUXK YOU!!!** 慢走不送了~8😠

**Comment by badboy-tian** [comment]
> 让我来替各位说吧！
> 
> ### **FUXK YOU!!!** 慢走不送了~8😠

出口成脏 关你X事 本项目也没有写license

**Comment by tiann** [comment]
双开部分的代码源自 [VirtualApp](https://github.com/asLody/VirtualApp) 这部分很难扯清楚：

1. VirtualApp 已经商业化了。
2. vxp 分支的代码源自 VirtualApp 商业化之前的last commit，这个分支的 license 为 GPLv3。

本项目除 VirtualApp之外的代码 license 为 Apache，不受限制。如果你要用于商业项目，最好是去找 VirtualApp 购买商业版。

**Comment by badboy-tian** [comment]
@tiann 感谢解答
