### ISSUE TITLE
在使用微信的时候无法保存图片和视频

### ISSUE THREAD

**Issue by 15565201312** [android-hacker/VAExposed#624]
## 问题描述
使用微信的时候保存图片视频保存不了到相册
（请尽量详细地描述你遇到的问题）
在使用微信版本为7.0.3 的时候，朋友给我发照片和视频，我进行保存，但是相册里并没有图片和视频呢
## 复现步骤
在使用微信版本为7.0.3 的时候，朋友给我发照片和视频，我进行保存，但是相册里并没有图片和视频呢，我也用VXP 开，关存储重定向， 感觉这个没什么用，最后还是没办法保存照片。
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：小米 Redmi 5A
系统版本：Android7.1.2
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：自带Xposed 
VirtualXposed版本： 0.17.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by 15565201312** [comment]
我在 VXP里面的微信如果保存图片都是通过截图保存的， 但是点击保存肯本不行， 视频也没办法保存

**Comment by shanzhijian** [comment]
微信将图片/视频保存在sd卡后，需要通知多媒体刷新，am/MethodProxies.java的handleMediaScannerIntent()函数将微信发送的多媒体刷新广播中的图片路径给改了，导致图库刷新的路径不是微信保存图片的路径，图库就不显示保存的图片

**Comment by batjoker** [comment]
这个问题我也遇到了，vxp里面的应用（我使用了qq和微信）保存媒体以后是无法即时刷新的，MTP方式连接电脑也就找不到。但是用文件管理器去相应路径是有保存下来的文件的。
我是最近几天升级到0.17.4的时候遇到的问题，之前一直使用了一年多的0.12.7版本是可以下载了直接找到媒体的。系统是EMUI 8.0.0。VXP里的软件版本没有变过，VXP外的软件保存图片都可以直接刷新，所以我认为是VXP的bug找过来的。。。
还没办法不卸载直接回滚旧版本应用，难受。

**Comment by jiachengliu** [comment]
这个问题要监听微信保存的图片路径（Environment.getExternalStorageDirectory()+"/tencent/MicroMsg/WeiXin/），然后有图片保存，就通知相册更新。MediaScannerConnection
