### ISSUE TITLE
miui10 9.0版本打开VXP崩溃

### ISSUE THREAD

**Issue by arthas55** [android-hacker/VAExposed#626]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

MIUI10 开发版9.5.16(内核9.10)打开VXP崩溃，
此版本miui更新了内核为9.0，0.17.3版本的VXP打开会崩溃，覆盖安装和卸载重装一样

## 复现步骤

直接打开，显示崩溃，日志如下：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/chiron/chiron:9/PKQ1.190118.001/9.5.16:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 23636, tid: 23641, name: Jit thread pool  >>> io.va.exposed <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb1187800
    r0  b1187800  r1  e3aa6214  r2  dd808000  r3  00000000
    r4  dd808000  r5  dbcaa680  r6  e352ae5a  r7  e352b632
    r8  00000043  r9  e357b374  r10 e357ceac  r11 0000005b
    ip  dd7ff8c8  sp  dd7ff8d0  lr  e3352797  pc  e3366554

backtrace:
    #00 pc 00260554  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity()+8)
    #01 pc 00007ffe  [anon:libc_malloc:dd800000]

## 环境

机型：mix2
系统版本：9.0
ROM版本：9.5.16
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by weimingjue** [comment]
https://github.com/android-hacker/VirtualXposed/issues/616
用这个回答解决了，你试试

**Comment by canyie** [comment]
XApp类的attachBaseContext方法有段禁用JIT的逻辑，试试修改成这样：
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
     if(OSUtils.getInstance().isMiui()) {
        //MIUI
        try {
            Class<?> klazz = Class.forName("dalvik.system.VMRuntime");
            Object vmRuntime = klazz.getMethod("getRuntime").invoke(null);
            klazz.getMethod("disableJitCompilation").invoke(vmRuntime);
        } catch(Exception e) {
            e.printStackTrace();
        }
     } else {
           NativeEngine.disableJit(Build.VERSION.SDK_INT);
     }
}
```

**Comment by weimingjue** [comment]
> XApp类的attachBaseContext方法有段禁用JIT的逻辑，试试修改成这样：
> 
> ```java
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
>      if(OSUtils.getInstance().isMiui()) {
>         //MIUI
>         try {
>             Class<?> klazz = Class.forName("dalvik.system.VMRuntime");
>             Object vmRuntime = klazz.getMethod("getRuntime").invoke(null);
>             klazz.getMethod("disableJitCompilation").invoke(vmRuntime);
>         } catch(Exception e) {
>             e.printStackTrace();
>         }
>      } else {
>            NativeEngine.disableJit(Build.VERSION.SDK_INT);
>      }
> }
> ```

能运行和使用了，但内置的xposed install运行不了，无法hook了，也没发现什么有用的报错，大神能解决吗

**Comment by canyie** [comment]
@weimingjue 试下太极能用吗？

**Comment by canyie** [comment]
> > XApp类的attachBaseContext方法有段禁用JIT的逻辑，试试修改成这样：
> > ```java
> > if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
> >      if(OSUtils.getInstance().isMiui()) {
> >         //MIUI
> >         try {
> >             Class<?> klazz = Class.forName("dalvik.system.VMRuntime");
> >             Object vmRuntime = klazz.getMethod("getRuntime").invoke(null);
> >             klazz.getMethod("disableJitCompilation").invoke(vmRuntime);
> >         } catch(Exception e) {
> >             e.printStackTrace();
> >         }
> >      } else {
> >            NativeEngine.disableJit(Build.VERSION.SDK_INT);
> >      }
> > }
> > ```
> 
> 能运行和使用了，但内置的xposed install运行不了，无法hook了，也没发现什么有用的报错，大神能解决吗

@weimingjue 问下启动不了是一直加载还是提示启动失败？

**Comment by hhhaiai** [comment]
<application
        android:name=".XApp"
        android:allowBackup="true"
        android:vmSafeMode="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/vxp"
        android:theme="@style/LauncherTheme"
        tools:replace="android:icon,android:label">

**Comment by hhhaiai** [comment]
<application
        android:name=".XApp"
        android:allowBackup="true"
        android:vmSafeMode="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/vxp"
        android:theme="@style/LauncherTheme"
        tools:replace="android:icon,android:label">

**Comment by hhhaiai** [comment]
```
 <application
        ...
        android:vmSafeMode="true"
        ...>
```

**Comment by qzztf** [comment]
> > > XApp类的attachBaseContext方法有段禁用JIT的逻辑，试试修改成这样：
> > > ```java
> > > if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
> > >      if(OSUtils.getInstance().isMiui()) {
> > >         //MIUI
> > >         try {
> > >             Class<?> klazz = Class.forName("dalvik.system.VMRuntime");
> > >             Object vmRuntime = klazz.getMethod("getRuntime").invoke(null);
> > >             klazz.getMethod("disableJitCompilation").invoke(vmRuntime);
> > >         } catch(Exception e) {
> > >             e.printStackTrace();
> > >         }
> > >      } else {
> > >            NativeEngine.disableJit(Build.VERSION.SDK_INT);
> > >      }
> > > }
> > > ```
> > 
> > 
> > 能运行和使用了，但内置的xposed install运行不了，无法hook了，也没发现什么有用的报错，大神能解决吗
> 
> @weimingjue 问下启动不了是一直加载还是提示启动失败？

一直在加载中。

`<application
        ...
        android:vmSafeMode="true"
        ...>`

加了这段代码，可以启动vxp，但是xposed install一直在加载中。

观察了一下logcat, 在opening xposed installer的过程中，installer的进程会出现然后消失，感觉像是被杀掉了，在不断重启。

**Comment by NeoXtreme** [comment]
Could you please make a release with this fix? As this is affecting all MIUI 10 users.
