### ISSUE TITLE
xposed not working fdroid

### ISSUE THREAD

**Issue by z2z** [android-hacker/VAExposed#635]
**Describe the bug**

Xposed not working in version installed from fdroid.

**To Reproduce**
1. Go to 'launcher'
2. Click on 'xposed installer'
3. See error ... https://del.dog/ukoxozoves.sql

**Expected behavior**

Start xposed

**Screenshots**

https://t.me/vxp_group/281514

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] lineage 16
 - Browser [e.g. chrome, safari] fennec
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] pocof1
 - OS: [e.g. iOS8.1] lineage 16
 - Browser [e.g. stock browser, safari] fennec
 - Version [e.g. 22] latest

**Additional context**

Guessing path or lib missing issue.

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.0
