### ISSUE TITLE
Crash on Redmi Note 7 Pro

### ISSUE THREAD

**Issue by amit996** [android-hacker/VAExposed#640]
**Describe the bug**
A clear and concise description of what the bug is. App crashed after opening

**To Reproduce**
1. Go to '...' default launcher
2. Click on '....' virtualxposed
4. See error screenshot attached

**Expected behavior**
App should start working

**Screenshots**

![Screenshot_2019-05-31-07-51-40-865_com miui bugreport](https://user-images.githubusercontent.com/29777583/58677862-3a123a80-837b-11e9-9c97-5661bcd45870.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Xiaomi Redmi Note 7 Pro
 - OS: [e.g. iOS8.1] MIUI 10
 - Browser [e.g. stock browser, safari] Brave
 - Version [e.g. 22] latest

**Additional context**

**Comment by Rishabhcom** [comment]
Same on Redmi note 7

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
