### ISSUE TITLE
安装后打开就报错：“很抱歉，VirtualXposed已停止运行”

### ISSUE THREAD

**Issue by kjxy** [android-hacker/VAExposed#645]
## 问题描述
安装好之后，一直不能打开VirtualXposed，提示“很抱歉，VirtualXposed已停止运行”
![image](https://user-images.githubusercontent.com/35479340/58939690-54e51480-87aa-11e9-8597-c41968ffec68.png)
会弹出来好几次停止运行的信息。

## 复现步骤

安装app，打开，报错

## 环境

安卓4.x 模拟器
VirtualXposed版本：GameGuardian

## 补充
无

**Comment by hyyz3293** [comment]
红米7 也是打开就报错 前段时间还不报错 
现在直接打开就报错了

**Comment by jiankunking** [comment]
小米6 安卓9.0 也是无法打开，具体错误信息如下：
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/sagit/sagit:9/PKQ1.190118.001/9.7.11:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 19478, tid: 19483, name: Jit thread pool  >>> io.va.exposed <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xedb61d9e
    r0  00000000  r1  eedae204  r2  e7f84000  r3  00000000
    r4  e7f84000  r5  e6350000  r6  edd2ab3a  r7  edd2b409
    r8  00000043  r9  edd7b374  r10 edd7cebc  r11 0000005b
    ip  e7f7f8c8  sp  e7f7f8d0  lr  edb4dfe7  pc  edb61d9e

backtrace:
    #00 pc 00260d9e  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity()+2)
    #01 pc 00003ffe  [anon:libc_malloc:e7f80000]`

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
