### ISSUE TITLE
微信无法登录

### ISSUE THREAD

**Issue by deeroad** [android-hacker/VAExposed#649]
## 问题描述

输入用户名和密码后，微信不会跳转到登录验证页面。

## 环境

机型：华为 p20
系统版本：9.0.0
ROM版本：Android 9
Xposed 插件以及插件版本：
VirtualXposed版本：VirtualXposed_AOSP_0.17.3

**Comment by yulele166** [comment]
同楼上

**Comment by shegongxue** [comment]
也遇到了，华为的EMUI8.2.0 android 8.1.0 华为畅享9

**Comment by moxuec** [comment]
同楼上

**Comment by hyyjf** [comment]
同楼上，登陆输入账号和密码后，黑屏，过一会自动返回到登陆页面，再点击登陆循环这样。在VirtualXposed里禁用了xposed,挂载的太极。
机型：华为畅玩6X 
系统版本：8.0.0 
ROM版本：Android 8 
VirtualXposed版本：从0.17.3至0.18.0各个版本都试过了，都是一样的

**Comment by Ayu8806** [comment]
同楼上，时好时坏的状态，有时候登陆上了，有时候登录不上去。
而且发消息这一块，有时候还会卡住 发送不出去，也接受不了。
机型：华为畅享9
EMUI版本：8.2.0
ROM版本：Android 8.1.0
Xposed 插件以及插件版本：xposed框架91
VirtualXposed版本：VirtualXposed_0.18.1

**Comment by Ayu8806** [comment]
> 也遇到了，华为的EMUI8.2.0 android 8.1.0 华为畅享9
你们有解决方案吗

**Comment by Ayu8806** [comment]
> 同楼上，登陆输入账号和密码后，黑屏，过一会自动返回到登陆页面，再点击登陆循环这样。在VirtualXposed里禁用了xposed,挂载的太极。
> 机型：华为畅玩6X
> 系统版本：8.0.0
> ROM版本：Android 8
> VirtualXposed版本：从0.17.3至0.18.0各个版本都试过了，都是一样的

目前我这边测试的手机 好像华为荣耀8 畅享9 这两个会出现此类问题，Android9.0 emui9.1 以上没有问题
