### ISSUE TITLE
as 编译失败

### ISSUE THREAD

**Issue by 594238813** [android-hacker/VAExposed#661]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

我看了wiki后
git clone https://github.com/android-hacker/VirtualXposed.git -b vxp --recursive
clone到本地 编译后
ERROR: Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@aospDebugAndroidTest/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@aospDebugUnitTest/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app

## 复现步骤

编译

## 环境

机型：
系统版本：
ROM版本：
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

无

**Comment by GitCod-Man** [comment]
我也遇到了同样的问题，你解决了吗？

---------------问题报错如下----------------------
ERROR: Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@aospDebugAndroidTest/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@aospDebugUnitTest/compileClasspath': Could not resolve project :launcher.
Show Details
Affected Modules: app

**Comment by simpleman1984** [comment]
gradle 5.1.1,将app项目下面的 
` implementation project(':launcher') `
改成
`implementation project(path:':launcher', configuration:'default')`
可以解决这个问题 @GitCod-Man

**Comment by simpleman1984** [comment]
@GitCod-Man 将launcher对应的子模块分支，切换为与virtualapp相同即可；比如 vxp
