### ISSUE TITLE
请问改怎么配置依赖？

### ISSUE THREAD

**Issue by tt328307109** [android-hacker/VAExposed#664]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
大佬！求助！
我下载的是最新的realease code 0.17.3
1.这份代码里面依赖了 api "me.weishu.exposed:exposed-core:0.7.5"
这个始终下不下来，maven上最新的是0.3.5
2.然后我改成0.3.5安装了常用模块里的MockLocation、文本自定义等软件，发现都没有效果
android studio报Logcat Error
3.但是使用您发布的VirtualXposed_AOSP_0.17.3.apk就可以成功。
4.此外额外还有一个问题，我发现一种基于您框架的软件，要添加应用不用安装，秒完成，这个您知道怎么做吗？可不可以优化呢

## 复现步骤
1.下载0.17.3的release code
2.android studio编译
## 环境

机型：
系统版本：android 8.0.0
ROM版本：samsung experience9.0
Xposed 插件以及插件版本：文本自定义2.3.1
VirtualXposed版本：0.17.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by ghost** [comment]
换SandVXposed，这个应用没有开源，源代码的epic是旧版。
