### ISSUE TITLE
安装应用变量3.3.2版打开黑屏

### ISSUE THREAD

**Issue by iseeyo** [android-hacker/VAExposed#671]
## 问题描述

vxp不支持应用变量3.3.2版，打开黑屏+卡顿

## 复现步骤

每次打开应用变量都出现

## 环境

机型：联想k5 pro
系统版本：安卓8.1.0
ROM版本：5.0.188
Xposed 插件以及插件版本：应用变量3.3.2版
VirtualXposed版本：0.17.3

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.0
