### ISSUE TITLE
多开应用的分身app启动时handleLoadPackage函数未调用

### ISSUE THREAD

**Issue by zdfdonny** [android-hacker/VAExposed#677]
## 问题描述

在virtualxposed中安装应用的分身，启动不是分身的app时可以成功hook，但是启动分身app时handleLoadPackage没被调用。

## 复现步骤

必现

## 环境

机型：OPPO K1
系统版本：8.1.0
ROM版本：ColorOS V5.2
Xposed 插件以及插件版本：90-beta3
VirtualXposed版本：0.17.3

**Comment by freyli007** [comment]
请问解决了吗？如何hook分身
