### ISSUE TITLE
谷歌框架安装成功，不能打开YouTube

### ISSUE THREAD

**Issue by Tangmn** [android-hacker/VAExposed#678]
## 问题描述

已经成功安装了谷歌框架，但是无法打开YouTube

## 复现步骤

1.在高级设置 中安装了谷歌框架
2.在xposed中启用了Fakes Gapps模块
3.打开YouTube显示打开应用失败(在海外，不存在网络问题）

## 环境

机型：
系统版本：Android9.0
ROM版本：EMUI9.1 
Xposed 插件以及插件版本：FakeGapps 2.0
VirtualXposed版本：0.17.3

## 补充

无

**Comment by silver-birch-wawa** [comment]
+1,google earth 也不行

**Comment by lokisama** [comment]
我也是 啥都运行不起来 咋玩google play求指点

**Comment by silver-birch-wawa** [comment]
> 我也是 啥都运行不起来 咋玩google play求指点

virtualxposed我没搞定，最后看的这个[Youtube教程](https://www.youtube.com/watch?v=bm9B2uk-2wI&list=PLurrbD4uBMWu8QF2VvuJL9trq8qInSXzH&index=7&t=834s)搞定的，我也是华为手机。
![1586194471212_cc046e3d-a598-49a5-8f52-b45af71fb1f](https://user-images.githubusercontent.com/19170791/79031442-3a9d7380-7bd1-11ea-8b04-8f717f59e306.jpg)

**Comment by lokisama** [comment]
非常感谢。。刚好是华为手机
> > 我也是 啥都运行不起来 咋玩google play求指点
> 
> virtualxposed我没搞定，最后看的这个[Youtube教程](https://www.youtube.com/watch?v=bm9B2uk-2wI&list=PLurrbD4uBMWu8QF2VvuJL9trq8qInSXzH&index=7&t=834s)搞定的，我也是华为手机。
> ![1586194471212_cc046e3d-a598-49a5-8f52-b45af71fb1f](https://user-images.githubusercontent.com/19170791/79031442-3a9d7380-7bd1-11ea-8b04-8f717f59e306.jpg)
