### ISSUE TITLE
部分从VX里启动的app会造成手机发烫严重

### ISSUE THREAD

**Issue by kotoricon** [android-hacker/VAExposed#679]
## 问题描述

一般类应用还行，但是凡涉及到大多游戏类app或者在框架中运行任何游戏没几分钟就会逐渐让手机温度大幅度飙升至55-70度左右，不从VX中启动不存在该问题

## 复现步骤

任意游戏从VX里启动基本均会发生

## 环境

机型：
系统版本：Android 9.0
ROM版本：三星N9600ZCU3CSF9（之前几个版本也有该问题）
Xposed 插件以及插件版本：无插件
VirtualXposed版本：0.17.3

**Comment by tiann** [comment]
GameGuardian 版本，这个属正常现象。
