### ISSUE TITLE
在VirtualXposed环境下，无法hook到微信小程序的代码（root xposed环境下正常）

### ISSUE THREAD

**Issue by liyixing1** [android-hacker/VAExposed#682]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
在VirtualXposed环境下，无法hook到微信小程序的代码（root xposed环境下正常）

看日志会出现：
提示 ignore moulde xxx for application。

## 复现步骤

确保安装的是
微信环境7.0.3,   如果没有可以私聊我，发一个。

打开任意小程序，只要调用了wx.getStorageSync(".....");
如果找不到这类小程序，可以私聊我分享一个小程序给你

## 环境

机型：oppo r11，夜神模拟器都试过
系统版本：android 7.1.1 ， android 5.1.1
ROM版本：coloros v3.2，夜神模拟器，5.1
Xposed 插件以及插件版本：3.14,    84
VirtualXposed版本：0.16.1，0.17.3，这两个版本都试过

## 补充

hook代码

```
clazz = cl.loadClass("com.tencent.mm.plugin.appbrand.jsapi.storage.i");

               //storage 监控
               Method[] methods = clazz.getDeclaredMethods();
               for (final Method m : methods) {
//此类a方法较多，同名重构方法，但是都会在wx.getStorageSync(".....");调用
                   if (m.getName().equals("a")) {
                       XposedBridge.hookMethod(m, new XC_MethodHook() {
                           @Override
                           protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                               XposedBridge.log("hook wx.getStorageSync");
                               super.afterHookedMethod(param);
                           }
                       });
                   }
               }
```

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by husseinmohammed1998** [comment]
Nice

**Comment by tiann** [comment]
Thank you for your feedback. We have tried our best to address the issue reported, however our product team has shifted work priority which doesn't include this issue. For now, we will be closing the issue as "Won't Fix (Obsolete)". If this issue still currently exists, we request that you log a new issue along with the latest bug report here: https://github.com/android-hacker/VirtualXposed/issues and reference this bug for context.

**Comment by NoahNyy** [comment]
请问解决了吗？
