### ISSUE TITLE
小米MIX 2S无法启动，打开就闪退

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#684]
## 问题描述

mix2s无法打开VirtualXposed,打开即闪退。

## 复现步骤

在系统桌面打开VirtualXposed，1秒后立刻报错，百分百出现。

## 环境

机型：小米mix2s
系统版本：9.7.17
ROM版本：开发版内测版
Xposed 插件以及插件版本：
VirtualXposed版本：0.7.13

## 补充

虽然开发版不修复，但还是反馈下，更新系统后才用不了的，所以以后可能都是这样了。

**Comment by sandy1108** [comment]
+1

**Comment by mytheshow** [comment]
米8也是，今天更新系统就阵亡了

**Comment by bitqiu** [comment]
红米也是

**Comment by wangfeng35** [comment]
> 米8也是，今天更新系统就阵亡了

同 手贱更新系统

**Comment by linxilee** [comment]
同，小米MIX2S 稳定版10.3.3.0 也无法打开

**Comment by bitqiu** [comment]
亲测 稳定版 10.2.2.0 可以正常使用

**Comment by peanutbutterli** [comment]
华为mate20pro 双开软件打不开 闪退

**Comment by mannialanck** [comment]
MIX3 稳定版 10.3.2.0 同闪退

**Comment by lulee007** [comment]
小米8 10.3.4 同闪退，手贱升级了系统版本

**Comment by crifan** [comment]
小米9  也是同样打开就闪退，无法使用。

小米9信息：

- MUMI版本： 10.2.31 稳定版   10.2.31.0(PFACNXM)
- Android版本：9

**Comment by haoyu592** [comment]
小米6，更新10.4.2 后立即阵亡 
MUMI版本：10.4.2稳定版
Android的版本：9

**Comment by ghost** [comment]
小米集体阵亡，被我说中了

**Comment by cnxobo** [comment]
同样，小米6，更新10.4.2 
MIUI版本：10.4.2稳定版
Android的版本：9

**Comment by hungvu193** [comment]
Redmi note 7, Android 9. MIUI Version 10.4.2

**Comment by CongAn** [comment]
小米MIX 2S 升级系统后阵亡，现在我在用虚拟大师，看起来还可以

**Comment by felipevlk** [comment]
Me have problem too

**Comment by XiaoPanPanKevinPan** [comment]
紅米 note 6 pro 也是
留下來的錯誤訊息
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/tulip/tulip:9/PKQ1.180904.001/V10.3.5.0.PEKMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 661, tid: 667, name: Jit thread pool  >>> io.va.exposed <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb1187800
    r0  b1187800  r1  70889cbc  r2  7073c268  r3  00000000
    r4  00080001  r5  e4cd7d20  r6  e545ce6a  r7  d2462e0b
    r8  00000043  r9  e54ad374  r10 e54aee9c  r11 0000005b
    ip  df5ff8c8  sp  df5ff8d0  lr  e5284767  pc  e529853c

backtrace:
    #00 pc 0026053c  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity()+8)
    #01 pc 00007ffe  [anon:libc_malloc:df600000]

**Comment by xinGCN** [comment]
同 Redmi K20 Pro.Android 9.MIUI Version 10.3.16

**Comment by yihu5566** [comment]
同样，小米6
MIUI版本：10.4.3稳定版
Android的版本：9

**Comment by ls19491314** [comment]
同样，小米8 启动闪退 100%
MIUI版本：10.3.6稳定版
Android的版本：9

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
