### ISSUE TITLE
VXP Forced Closed.

### ISSUE THREAD

**Issue by Cornysz** [android-hacker/VAExposed#694]
**Describe the bug**
Title says it all. idk how to describe, VXP always fc after i opened. 1 week ago my Vxp is normal, but now idk why its always fc. Ill send the report summary.

**To Reproduce**
1. Open VXP
2. FC.

**Expected behavior**
I want this error to be fixed ASAP. I already restart my phone and reinstalled vxp, but nothing hppnd.

**Screenshots**
![Screenshot_2019-08-02-17-17-54-449_com miui bugreport](https://user-images.githubusercontent.com/31491351/62378334-cbb24a00-b56e-11e9-8b00-6dd81fb50a7b.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser [Chrome]
 - Version [Latest]

**Smartphone (please complete the following information):**
 - Device: [Xiaomi POCOPHONE F1]
 - OS: [Android PIE]
 - Browser [Samsung Browser]
 - Version [9]

**Additional context**
-

**Comment by Cornysz** [comment]
WAITINGGGGG....

**Comment by Modify24x7** [comment]
try:
https://bit.ly/2MX11ZE

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
