### ISSUE TITLE
vxposed在小米-安卓9上闪退

### ISSUE THREAD

**Issue by GalaxySnail** [android-hacker/VAExposed#696]
## 问题描述
在小米平板4（安卓版本8.1）中可以正常安装使用，然而在小米8SE（安卓版本9）中则会闪退。
19.10.10更新：红米Note7Pro在MIUI10, MIUI11上也会闪退。看错误报告的情况，似乎和libart.so有关。

## 复现步骤
安装apk后运行，立即闪退。复现率100%。

## 环境

机型：小米8SE
系统版本：Android 9
ROM版本：MIUI 10.3 | 稳定版 10.3.1.0(PEBCNXM)
VirtualXposed版本：0.17.3、0.17.2、0.17.1、0.16.1、0.16.0、0.15.1

机型：小米平板4
系统版本：Android 8.1
ROM版本：MIUI 9（具体版本我白天看看，不过这个是可以运行的，我放在这里只是比对一下）
VirtualXposed版本：0.17.3

机型：红米Note7Pro
系统版本：Android 9
ROM版本：MIUI10稳定版、MUI10开发版、MIUI 11 9.8.26 开发版
VirtualXposed版本：0.17.3

## 错误报告
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/violet/violet:9/PKQ1.181203.001/9.9.26:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 10404, tid: 10410, name: Jit thread pool  >>> io.va.exposed <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0  00000000  r1  ea039d74  r2  e3188000  r3  00000000
    r4  e3188000  r5  00000001  r6  e8eebe1a  r7  e317fcac
    r8  00000043  r9  e8f3c374  r10 e8f3de9c  r11 0000005b
    ip  e317f8c8  sp  e317f8d0  lr  e8d0e9b9  pc  e8d22b28

backtrace:
    #00 pc 00264b28  /system/lib/libart.so (offset 0x258000) (art::ProfileSaver::NotifyJitActivity()+8)
    #01 pc 00007ffe  [anon:libc_malloc:e3180000]

**Comment by shiqwang** [comment]
升级了一下，现在闪退了 ……

**Comment by jspp** [comment]
关注

**Comment by MEi521010** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/perseus/perseus:9/PKQ1.180729.001/9.8.22:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 30002, tid: 30005, name: Jit thread pool  >>> io.va.exposed:x <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xed5295f9
    r0  00000000  r1  ed96d264  r2  e7689000  r3  00000000
    r4  e7689000  r5  e46d9350  r6  ed528d2a  r7  ed5295f9
    r8  00000043  r9  ed579374  r10 ed57aeac  r11 0000005b
    ip  e79518c8  sp  e79518d0  lr  ed34bfb7  pc  ed35fd84

backtrace:
    #00 pc 00260d84  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity())
    #01 pc 00008ffe  [anon:libc_malloc:e7680000]

**Comment by MEi521010** [comment]
> 建立指纹： '小米/修斯/修斯：9 / PKQ1.180729.001 / 22年9月8日：用户/释放密钥' 
> 修订： '0' 
> ABI： 'ARM' 
> PID：30002，TID：30005，名称：日新线程池> >> io.va.exposed:x <<< 
> 信号7（SIGBUS），代码1（BUS_ADRALN），故障地址0xed5295f9 
> r0 00000000 r1 ed96d264 r2 e7689000 r3 00000000 
> r4 e7689000 r5 e46d9350 r6 ed528d2a r7 ed5295f9 
> r8 00000043 r9 ed579374 r10 ed57aeac r11 0000005b 
> ip e79518c8 sp e79518d0 lr ed34bfb7 pc ed35fd84
> 
> 回溯：
> ＃00 pc 00260d84 /system/lib/libart.so（偏移量0x254000）（art :: ProfileSaver :: NotifyJitActivity（））
> [＃1](https://github.com/android-hacker/VirtualXposed/pull/1) pc 00008ffe [anon：libc_malloc：e7680000]

小米MIX 3             Open app  crash log

**Comment by shenxiaolei123** [comment]
小米9闪退怎么解决

**Comment by hiblacker** [comment]
同问

**Comment by a1023182899** [comment]
小米9闪退怎么解决

**Comment by GalaxySnail** [comment]
更新：在红米Note7Pro上存在同样的问题。包括MIUI10和MIUI11。

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
