### ISSUE TITLE
Mix2s MIUI Global 10.3.4 稳定版 无法打开

### ISSUE THREAD

**Issue by Sylphinford** [android-hacker/VAExposed#697]
## 问题描述
打开报错
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/polaris/polaris:9/PKQ1.180729.001/V10.3.4.0.PDGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 7369, tid: 7375, name: Jit thread pool  >>> io.va.exposed <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe70c5d8c
    r0  e70c5d8c  r1  00000000  r2  00000000  r3  00000002
    r4  00001ccf  r5  00000001  r6  00000000  r7  e6e5f5f9
    r8  00000043  r9  e6eaf374  r10 e6eb0eac  r11 0000005b
    ip  e11cd8c8  sp  e11cd8d0  lr  e6c81fb7  pc  e6c95d8a

backtrace:
    #00 pc 00260d8a  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity()+6)
    #01 pc 00019ffe  [anon:libc_malloc:e0f00000]

## 复现步骤

打开直接报错

## 环境

机型：Mix2s
系统版本：9 PKQ1.180729.001
ROM版本：MIUI Global 10.3.4 稳定版 (PDGMIXM)
Xposed 插件以及插件版本：应用进不去，无法查看。VX默认版本
VirtualXposed版本：0.17.3

## 补充

![Screenshot_2019-08-06-06-24-15-129_com miui bugreport](https://user-images.githubusercontent.com/43917892/62512143-18b84980-b817-11e9-9649-76d3e5581358.png)

**Comment by Cornysz** [comment]
I GOT SAME ERROR.. btw my phone is POCOPHONE miui 10.3.6

**Comment by Razor0719** [comment]
Mi 8 miui 10.3.5 start virtualxposed failed too

**Comment by Modify24x7** [comment]
try:
https://bit.ly/2MX11ZE

**Comment by Razor0719** [comment]
> try:
> https://bit.ly/2MX11ZE

There was a problem parsing the package on Mi8 MIUI10,and the installation failed

**Comment by felipevlk** [comment]
Mi 8 miuai 10.3.4 stable global virtualxposed failed too

I got same error

**Comment by mynamecool** [comment]
Mi 8 MIUI 10.3.4 me too

**Comment by lucass40** [comment]
Same problem redmi 7a miui 10.2.5

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/598
