### ISSUE TITLE
请问x86_64 CPU的小米平板2能用吗？

### ISSUE THREAD

**Issue by a3135134** [android-hacker/VAExposed#699]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

Xposed框架无法激活

## 复现步骤

安装了virtualxposed，发现框架无法激活

## 环境

机型：小米平板2
系统版本：安卓5.1
ROM版本：开发版
Xposed 插件以及插件版本：略
VirtualXposed版本：最新

## 补充

我知道xposed本身没有x86_64版本的支持，不知virtual xposed是否支持？

**Comment by tiann** [comment]
不支持 x86
