### ISSUE TITLE
根据wiki git clone之后，Android studio 3.5 编译分析出错 build sysnc error

### ISSUE THREAD

**Issue by aiweisir** [android-hacker/VAExposed#712]
git clone https://github.com/android-hacker/VirtualXposed.git -b vxp --recursive
vxp及子模块launcher git lone完成之后 android studio 编译出错，之前尝试过很多，删除文件重新clone 或修改提示错误的地方 都没编译成功！why?

ERROR: Unable to resolve dependency for ':lib@debug/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: lib

ERROR: Unable to resolve dependency for ':lib@debugAndroidTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: lib

ERROR: Unable to resolve dependency for ':lib@debugUnitTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: lib

ERROR: Unable to resolve dependency for ':launcher@aospDebug/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: launcher

ERROR: Unable to resolve dependency for ':launcher@aospDebugAndroidTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: launcher

ERROR: Unable to resolve dependency for ':launcher@aospDebugUnitTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: launcher

ERROR: Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@aospDebugAndroidTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@aospDebugUnitTest/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.
Show Details
Affected Modules: app

**Comment by liuyang77886** [comment]
我的也是同样的问题，你解决了吗
ERROR: Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve project :launcher.

**Comment by hongbowang** [comment]
ERROR: Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve me.weishu.exposed:exposed-core:0.7.7-c.

the same

**Comment by hongbowang** [comment]
the same error and can't resolve

**Comment by sweenwolf** [comment]
only 0.3.5 is available, cannot find core version 0.7.7

**Comment by qinyaoTAT** [comment]
change me.weishu.exposed:exposed-core:0.7.7-c to me.weishu.exposed:exposed-core:0.3.5 is ok

**Comment by tiann** [comment]
0.7.7-c 忘了传到jcenter了，刚刚已经上传了。
事实上，你只需要编译下 https://github.com/android-hacker/exposed 就可以生成这个依赖。
