### ISSUE TITLE
安卓10无法正常使用

### ISSUE THREAD

**Issue by eliasli77** [android-hacker/VAExposed#718]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

XposedInstaller无法打开，可以正常安装软件，但是无法打开

## 环境

机型：一加7pro  GM1910
系统版本：一加氧os 安卓10  公测2  
ROM版本：
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.3

**Comment by Adrvsh** [comment]
Same. I used android 10 too n it didn't work. I already use vxp since a long time before i updated my android version.

**Comment by MiracleLau** [comment]
同样无法使用，Miui11，红米k20 pro

**Comment by EricPHPH** [comment]
同样无法使用，一加7pro，氢OS Android10
VirtualXposed版本：0.17.4

**Comment by alongstorm** [comment]
同样无法使用，一加6T，氢OS Android10
VirtualXposed版本：0.17.4

**Comment by ancct** [comment]
同样无法使用，安卓10 pixel2，求解决

**Comment by Razor0719** [comment]
same problem
MIUI11 Android10
Virtual Xposed 0.17.4

**Comment by iseeyo** [comment]
更新之后有些应用闪退打不开了，比如陌陌

**Comment by tiann** [comment]
Supporting for Android 10 is WIP: https://github.com/android-hacker/VirtualXposed/commit/301d1144f31f4b538b3dc9dc0a839cd64527ed7d

**Comment by Adrvsh** [comment]
> Supporting for Android 10 is WIP: [301d114](https://github.com/android-hacker/VirtualXposed/commit/301d1144f31f4b538b3dc9dc0a839cd64527ed7d)

Thankyou sir.

**Comment by eliasli77** [comment]
> Supporting for Android 10 is WIP: [301d114](https://github.com/android-hacker/VirtualXposed/commit/301d1144f31f4b538b3dc9dc0a839cd64527ed7d)

Thankyou sir.

**Comment by diai0205** [comment]
什么时候更新啊，10没法用呢

**Comment by guorenxi** [comment]
自行编译最新的commit后可以打开xposed installer，但是提示xposed框架未安装

**Comment by qinlili23333** [comment]
zenfone6 zenui 10.0闪退+1

**Comment by hldh214** [comment]
readme 需要更新一下吗~
