### ISSUE TITLE
请问能否提供GameGuardian版的源码,谢谢~

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#722]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

在VirtualXposed中使用GameGuardian.

## 希望的解决方案

希望作者能将兼容GameGuardian版本的开源

## 其他信息

暂无.

**Comment by mahmoud303030** [comment]
jxcjvjvjckgkghsuaufjfjx

**Comment by jhoneybee** [comment]
这个没有问题，但是作者使用个人时间进行开发，希望您能够捐赠作者，让作者有更多的时间专注于开源项目。

**Comment by tiann** [comment]
源码是一样的。
