### ISSUE TITLE
高级管理-文件管理，文件管理器下载不下来。

### ISSUE THREAD

**Issue by XinYiWorld** [android-hacker/VAExposed#728]
## 问题描述

高级管理-文件管理，文件管理器下载不下来。

## 复现步骤

高级管理-文件管理，文件管理器下载不下来。

## 环境
应该是服务器没有文件，和机型没有关系。
机型：
系统版本：
ROM版本： 
Xposed 插件以及插件版本：
VirtualXposed版本：最新

## 补充

而且我通过DDMS将文件导出来，并没有dex文件。

**Comment by AndMy** [comment]
同问啊，你最后下载下来了吗

**Comment by XinYiWorld** [comment]
没有------------------ 原始邮件 ------------------
发件人: "恰好你来"<notifications@github.com>
发送时间: 2020年1月11日(星期六) 中午1:34
收件人: "android-hacker/VirtualXposed"<VirtualXposed@noreply.github.com>;
抄送: "XinYi"<1349308479@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [android-hacker/VirtualXposed] 高级管理-文件管理，文件管理器下载不下来。 (#728)



同问啊，你最后下载下来了吗
 
&mdash;

**Comment by XinYiWorld** [comment]
没有，我发现这些工具根本无法破解360。
反调试也过不了。



---原始邮件---
发件人: "恰好你来"<notifications@github.com&gt;
发送时间: 2020年1月11日(周六) 中午1:34
收件人: "android-hacker/VirtualXposed"<VirtualXposed@noreply.github.com&gt;;
抄送: "XinYi"<1349308479@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [android-hacker/VirtualXposed] 高级管理-文件管理，文件管理器下载不下来。 (#728)



同问啊，你最后下载下来了吗
