### ISSUE TITLE
TikTok（国际版抖音）可以打开但不能登录

### ISSUE THREAD

**Issue by HyperBioGhost** [android-hacker/VAExposed#730]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**
搜了一下似乎没有类似的问题

## 问题描述
TikTok（国际版抖音）可以在VirtualXposed内打开但不能登录

## 复现步骤
VirtualXposed + 环境变量（即AppEnv，下载地址：https://www.coolapk.com/apk/com.sollyu.xposed.hook.model）+ 国际版抖音TikTok（通过ApkPure下载）
环境变量与国际版抖音通过直接加载安装包的方式安装到VirtualXposed，将环境变量加入Module，在VirtualXposed桌面点击环境变量，修改tiktok app的运营商信息如下
日本
SIM代码（SIM序号） 44008
SIM名称（通信服务商名称）KDDI
SIM国家代码（SIM国际）JP
保存后重启VirtualXposed，点击tiktok可以进入APP，但不能通过facebook/twitter/ins注册或登录。

## 环境

机型：Xperia XZ3
系统版本：Android 9
ROM版本：52.0.A.8.131
Xposed 插件以及插件版本：AppEnv，国际版抖音（尝试长按app并拖拽至app info没有任何效果，无法查看安装至VirtualXposed内的app的信息）
VirtualXposed版本：0.17.4

## 补充
使用喵帕斯，挂载日本节点，V2rayNG，bypass Lan and mainland China

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by LidoCKT** [comment]
我直接是VXposed里面的抖音一点开就闪退，MIX2S Android 9

**Comment by sasaju** [comment]
小米8青春版 Android10 同样的运营商设置，打开后点击start watching后闪退
