### ISSUE TITLE
How run service

### ISSUE THREAD

**Issue by lahed** [android-hacker/VAExposed#734]
**Describe the bug**
Hey, 
I have a .so service elf. I want to run it as root so I want to use virtualxposed to run it, can it and how?. It is similar to gameguardian

In root I run it like this: 
```
ProcessBuilder pb = new ProcessBuilder("su");
Process su = pb.start();

DataOutputStream outputStream = new DataOutputStream(su.getOutputStream());

outputStream.writeBytes(getFilesDir().getAbsolutePath() + File.separator + nameProcess + " &>/dev/null &");
outputStream.flush();
outputStream.close();

su.waitFor();
```

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by tiann** [comment]
You cannot get root permission in VirtualXposed if the device doesn't have root.

**Comment by lahed** [comment]
hmmm and how does game guardian to run service ?

**Comment by tiann** [comment]
you can run the executable elf in VirtualXposed, it can access any memory of any process in VirtualXposed, no root needed.

**Comment by lahed** [comment]
Thank you, fixed !
