### ISSUE TITLE
tiktok 国际版无法打开  一直在opening tiktok

### ISSUE THREAD

**Issue by xwchengzi** [android-hacker/VAExposed#738]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

打开tiktok  一直在opening tiktok页面。
试过重新卸载再安装一次VirtualXposed，可以暂时解决这个问题，但没过多久再重新打开tiktok，就又一直停留opening tiktok页面了。

## 复现步骤

安装应用变量：改地区、营运商
安装tiktok 国际版 ，无法打开，一直在opening tiktok页面。

## 环境

机型：xiao mi 8
系统版本：Andriod 9
ROM版本：MIUI 11.0.4.0稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.0

## 补充

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by swat521** [comment]
MIUI 11 同样问题

**Comment by xwchengzi** [comment]
需要重新卸载再安装一次VirtualXposed才可以打开，但没过多久就又不能打开了。

**Comment by elfertower** [comment]
MIUI 11 xiao mi 6 同样问题

**Comment by Hedgehogking** [comment]
> MIUI 11 xiao mi 6 同样问题

我也是，这个问题很久了，下了最新的0.19.0都不行……
