### ISSUE TITLE
Not login game

### ISSUE THREAD

**Issue by lahed** [android-hacker/VAExposed#739]
**Describe the bug**
The game starts but you cannot log in

**To Reproduce**
1. Clone PUBGM
2. Login 

**Expected behavior**
pubgm work in virtualxposed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Android 9

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: Xiaomi Mi 9
 - OS: [e.g. iOS8.1]: Android 9

**Additional context**

**Comment by tiann** [comment]
VirtualXposed is banned by PUBG, but unfortunately i won't fix it.
I have no time to play mouse and cat with PUBG.
