### ISSUE TITLE
荣耀 9X 在 VXP 中无法打开微信

### ISSUE THREAD

**Issue by xinGCN** [android-hacker/VAExposed#747]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

如图，在 VXP 中无法打开微信，提示打开应用 com.tencent.mm 失败:( 

## 复现步骤

必现 bug，直接安装好微信点击打开即可复现。

## 环境

机型：荣耀 9X   HLK-AL00
系统版本：Android 9
ROM版本：EMUI版本：9.1.1 ；版本号：9.1.1.160(C00E160R5P3) GPU Turbo
Xposed 插件以及插件版本：没有启用 Xposed 插件
VirtualXposed版本：0.17.2、0.17.3、0.17.4、0.18.0 AOSP 版本都试过，都是会出现同样问题。

## 补充

希望得到作者大大的青睐

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by liangxiwei** [comment]
为什么你们提issue，一点log都不舍得放，是不会捉log吗
