### ISSUE TITLE
no enabled modules

### ISSUE THREAD

**Issue by KindlyOnes** [android-hacker/VAExposed#752]
**Describe the bug**
The modules I downloaded appear to be enable but never enabled.
**To Reproduce**
1. Go to 'manage modules'
2. Click on 'enable module'
3. Scroll down to 'reboot'
4. See error "nothing happen"

**Expected behavior**
I hope you can fix this issue.

**Smartphone (please complete the following information):**
 - Device: [Samsung s4 gt-i9500]
 - OS: [android-5.0.1 NO ROOT]

**Comment by KindlyOnes** [comment]
![20191117_233907](https://user-images.githubusercontent.com/50758669/69014639-59d70280-099d-11ea-9890-8f54a19fb269.png)

**Comment by KindlyOnes** [comment]
12-12 18:48:53.556 I/XposedInstaller(21581): updating modules.list

12-12 18:49:04.781 I/VClientImpl(22140): Binding application de.robv.android.xposed.installer, (de.robv.android.xposed.installer)

12-12 18:49:04.841 I/VClientImpl(22140): Xposed is enabled.

12-12 18:49:04.866 I/ExposedBridge(22140): de.robv.android.xposed.installer is not a Xposed module, do not init epic.force

12-12 18:49:04.866 I/Xposed  (22140): xposed config file exists, check version


12-12 18:49:04.866 I/ExposedBridge(22140): xposed version keep same, continue.

12-12 18:49:04.886 I/Runtime (22140): is64Bit: false, isArt: true

12-12 18:49:04.886 I/EpicNative(22140): use unsafe ? false

12-12 18:49:04.886 I/XposedInstaller(22140): null getActivityXposedVersion called.

12-12 18:49:05.931 I/VClientImpl(22165): Binding application com.google.android.gms, (com.google.android.gms)

12-12 18:49:06.001 I/VClientImpl(22165): Xposed is enabled.

12-12 18:49:06.036 I/ExposedBridge(22165): com.google.android.gms is not a Xposed module, do not init epic.force

12-12 18:49:06.041 I/ExposedBridge(22165): module:/data/data/io.va.exposed/virtual/data/app/com.ChillyRoom.DungeonShooter/base.apk is disabled, ignore

12-12 18:49:06.041 I/ExposedBridge(22165): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore

12-12 18:49:06.046 I/ExposedBridge(22165): module:/data/data/io.va.exposed/virtual/data/app/com.android.vending/base.apk is disabled, ignore

12-12 18:49:06.046 I/ExposedBridge(22165): module:/data/data/io.va.exposed/virtual/data/app/com.gtppmhnusag/base.apk is disabled, ignore

12-12 18:49:06.046 I/ExposedBridge(22165): module:/data/data/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk is disabled, ignore

12-12 18:49:06.046 I/ExposedBridge(22165): module:/data/data/io.va.exposed/virtual/data/app/com.google.android.gsf/base.apk is disabled, ignore

12-12 18:49:06.046 I/ExposedBridge(22165): Loading modules from /data/data/io.va.exposed/virtual/data/app/com.thermatk.android.xf.fakegapps/base.apk for process: com.google.android.gms i s c: false

12-12 18:49:06.256 I/ExposedBridge(22165):   Loading class''
 com.thermatk.android.xf.fakegapps.FakeSignatures
12-12 18:49:06.301 I/Runtime (22165): is64Bit: false, isArt: true

12-12 18:49:06.306 I/EpicNative(22165): use unsafe ? false

**Comment by nAiL-02** [comment]
Why shut down this issue? I have the same problem.
