### ISSUE TITLE
华为mate 30 pro。，QQ无法登陆

### ISSUE THREAD

**Issue by Fujiantulou** [android-hacker/VAExposed#759]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

安装最新版visualxposed，QQ版本8.1.8，登陆时提示“无法登陆，请检查你的网络”

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：Mate 30 Pro 8G+256G
系统版本：Android 10
ROM版本：EMUI 10.0.0
Xposed 插件以及插件版本：91
VirtualXposed版本：0.18.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by luciouskami** [comment]
+1

**Comment by tiann** [comment]
Fixed https://github.com/android-hacker/VirtualXposed/commit/effcb5e3cc55068ad4af2545efe42ff6c0e83cf5
