### ISSUE TITLE
华为p30p打开微信闪退

### ISSUE THREAD

**Issue by oatluo** [android-hacker/VAExposed#766]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

华为p30p打开微信闪退，未安装其它APP及XP插件，手机有安装太极，显示如下：
![Screenshot_20191120_013205_io va exposed](https://user-images.githubusercontent.com/11293920/69171480-00a2d680-0b37-11ea-8047-3c22563daa6c.jpg)

## 复现步骤
只要打开微信就出现闪退

## 环境

机型：
系统版本：安卓10
ROM版本：EMUI 10.0.0.166（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：未安装插件
VirtualXposed版本：0.18

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by jiachengliu** [comment]
你到“设置”-->"高级设置"-->“关闭Xposed” 关闭。试试

**Comment by tiann** [comment]
#815
