### ISSUE TITLE
Fragment 生命周期Hook 不正确

### ISSUE THREAD

**Issue by BelongsH** [android-hacker/VAExposed#770]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
 
问题出现在最新发布的版本`0.18`,两个包都试了

其中一个包（后缀为`GameGuardian.apk`）可以显示进程，进行调试。但是会发现生命周期的方法`hook`不了。（`fragment->onResume`）  

其中一个包不能显示进程，不能进行调试。正常`Hook`生命周期。

上面都可正常的`hook`->`fragment`->`onCreate`

相同的代码，在`xposed`环境下是正常`hook` 

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型： 华为
系统版本： 9.0
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by liangxiwei** [comment]
fragment有好几个呢，有系统的，有v4的，有androidx的，你要确定一下有没有搞错类的全名
