### ISSUE TITLE
Miui11无法正常使用vxp

### ISSUE THREAD

**Issue by arthur20150522** [android-hacker/VAExposed#771]
## 问题描述

app均不能正常使用，最多的表现是在vxp里面打开应用，一直在进度条而已，无法进入应用。
提示打开xx应用(包名)失败

## 复现步骤

必现，任意应用打开失败

## 环境

机型：小米8
系统版本：安卓10
ROM版本：开发版miui11，因为现在安卓10只有开发版的
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.0

## 补充

我之前是安卓9正常使用，看到前几天有支持安卓10 了才升级的系统~ 然后就挂了~

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by arthur20150522** [comment]
微信不可用，美团不可用，平安金管家不可用~~ 是不是这些app做了反xposed
扑扑超市 app可用。。。。~

**Comment by elfertower** [comment]
重启手机后，tiktok也有此问题

**Comment by tcc0lin** [comment]
服了，手机自动更新miui11版本，所有服务都挂了

**Comment by imtypist** [comment]
小米6 miui11 开发版 打开应用失败，或闪退

**Comment by tcc0lin** [comment]
有大神有思路吗？是不是要开始刷机了

**Comment by tcc0lin** [comment]
还是重刷10吧

**Comment by inkhog** [comment]
我的华为更新安卓10更是根本连接不了QQ，我觉得还是安卓10的某些权限问题，因为有时候其他的安装在本机的工具也是内置的联网功能没法启用比如MT管理器的ftp远程管理服务

**Comment by Noshilyah** [comment]
> ## 问题描述
> app均不能正常使用，最多的表现是在vxp里面打开应用，一直在进度条而已，无法进入应用。
> 提示打开xx应用(包名)失败
> 
> ## 复现步骤
> 必现，任意应用打开失败
> 
> ## 环境
> 机型：小米8
> 系统版本：安卓10
> ROM版本：开发版miui11，因为现在安卓10只有开发版的
> Xposed 插件以及插件版本：
> VirtualXposed版本：0.18.0
> 
> ## 补充
> 我之前是安卓9正常使用，看到前几天有支持安卓10 了才升级的系统~ 然后就挂了~
> 
> **写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by Ayu8806** [comment]
> > ## 问题描述
> > app均不能正常使用，最多的表现是在vxp里面打开应用，一直在进度条而已，无法进入应用。
> > 提示打开xx应用（包名）失败
> > ## 复现步骤
> > 必现，任意应用打开失败
> > ## 环境
> > 原型：小米8 
> > 系统版本：安卓10 
> > ROM版本：开发版miui11，因为现在安卓10只有开发版的
> > Xposed插件和插件版本：
> > VirtualXposed版本：0​​.18.0
> > ## 补充
> > 我之前是安卓9正常使用，看到前几天有支持安卓10了才升级的系统〜然后就挂了〜
> > **写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

你这个啊本来就不行的，0.18的vxp不支持Android10的

**Comment by five-of-fuli** [comment]
MIUI11使用框架里所有软件的联网都有问题

**Comment by inkhog** [comment]
> MIUI11使用框架里所有软件的联网都有问题

应该不止框架，只要是应用内置的工具好像都没有网络权限，赋予应用权限不能传递，是这个理吧？

**Comment by leewaro** [comment]
我安装了0.18.2版本，vxp打开微信失败，无法打开微信，请问有什么办法修复吗

**Comment by hw1020** [comment]
我的k20pro的virtual xposed 感觉正常使用，0.18，我的游戏正常，miui11安卓10

**Comment by tiann** [comment]
#815
