### ISSUE TITLE
微信谷歌商店版，版本号：v7.0.7(1519)

### ISSUE THREAD

**Issue by igit-cn** [android-hacker/VAExposed#772]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

微信谷歌商店版，版本号：v7.0.7(1519)，在VirtualXposed中打不开！！！

## 复现步骤

在VirtualXposed中，添加应用，微信谷歌商店版，版本号：v7.0.7(1519)，添加成功之后，打不开微信

## 环境

机型：
系统版本：
ROM版本：MIUI10 8.11.8稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：VirtualXposed 0.18.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
#815
