### ISSUE TITLE
框架内tiktok登陆不了账号

### ISSUE THREAD

**Issue by vyhvc** [android-hacker/VAExposed#778]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
tiktok软件能打开，但是点账号登陆就会闪退，直接退出软件

## 复现步骤

直接打开virtualxposed里的tiktok,然后账号登陆，我点的facebook,然后就直接闪退了，而且virtualxposed里facebook账号登陆不了facebook

## 环境

机型：华为nova,WAS-AL00
系统版本：android8.0.0,EMUI8.0.0
ROM版本:我不知道
Xposed 插件以及插件版本：这个我不知道，是xposed 
installer么，这个版本是3.1.5
VirtualXposed版本：3.1.5

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by nongzhenli** [comment]
请问如何解决了?我也遇到这个问题

**Comment by vyhvc** [comment]
> 请问如何解决了？我也遇到这个问题



> 请问如何解决了？我也遇到这个问题

不用tiktok，这是一个解决的好方法，我就使用的这个方案
