### ISSUE TITLE
微信打开启动页黑屏

### ISSUE THREAD

**Issue by javamavin** [android-hacker/VAExposed#785]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
打开微信先黑屏一段时间在进入，应该是启动页不显示直接黑屏了，打开速度慢
（请尽量详细地描述你遇到的问题）

## 复现步骤
微信退出后在打开每次都会出现
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：小米4，红米6a，小米9基本这边机型都会出现
系统版本：android 7.0
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.0

## 补充
有时黑屏后卡死
（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by weizeng** [comment]
我也遇到了，难道是太占用内存了

**Comment by Ayu8806** [comment]
我没有更改代码，只是清空了缓存，清空任务管理，杀掉vxp进程，重新打开，就好了。。。

**Comment by pychu-rx** [comment]
这个问题是因为VirtualXposed安装了位置定位软件，微信打开就会黑屏，我的解决办法是安装微信32位版本，可以避免黑屏，我的VirtualXposed版本为0.18.2
