### ISSUE TITLE
安卓10，微信启动失败（0.18.0 + 微信7.0.10）

### ISSUE THREAD

**Issue by theanswer910725** [android-hacker/VAExposed#790]
## 问题描述
VirtualXposed版本0.18.0，已经支持安卓10。克隆手机内的微信7.0.10版本后在环境内无法启动，提示“打开com.tencent.mm失败:(”

## 复现步骤

安卓10非ROOT环境，在0.18.0中安装7.0.10版微信后尝试打开。

## 环境

机型：三星S10
系统版本：Android 10
ROM版本：非ROOT稳定版
Xposed 插件以及插件版本：WeXposed 54_2.7
VirtualXposed版本：0.18.0

**Comment by cyxhh** [comment]
。。。。。

**Comment by Qwejay** [comment]
问题一样 三星S10最新版

**Comment by BongeZagh** [comment]
oneplus A6000
android 9
微信 7.0.10

同样 黑屏

大家有不黑屏的版本吗

**Comment by liangmingran** [comment]
同样的问题
三星 note10+ 
安卓10
微信7.0.10
VirtualXposed版本：0.18.0

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/1ab205cf208d58e1a72dca620051d0f006fb4139
