### ISSUE TITLE
apps inside will say keep crashing if in work profile.

### ISSUE THREAD

**Issue by NewUserHa** [android-hacker/VAExposed#800]
**Describe the bug**
apps inside will say keep crashing when using in the work profile, but not in normal profile. using shelter.

I had found like there're some permission stand-alone apps in some devices would not be cloned automatically into work profile like using the island.
so it's possible that it lacks other apps but I can't find it.

does vxp need some depends?

**To Reproduce**
1.open vxp
2.open any apps inside vxp
3. loading animation forever and the window disappear and popup say keep crashing if switch apps

**Expected behavior**
works normally

**Screenshots**
none

**Desktop (please complete the following information):**
none

**Smartphone (please complete the following information):**
Device: sony x1
OS: android9
Browser stock browser
Version 0.18 for GG

**Additional context**
#799

**Comment by tiann** [comment]
don't support work profile.

**Comment by NewUserHa** [comment]
Then is it possible to add the support? Is it difficult?
