### ISSUE TITLE
安卓10 虚拟环境内APP没有网络

### ISSUE THREAD

**Issue by imyjq** [android-hacker/VAExposed#801]
** **

## 问题描述

环境里边任何APP都不能连接网络

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：小米8
系统版本：安卓10
ROM版本：miui11.06（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.0

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/1ab205cf208d58e1a72dca620051d0f006fb4139
