### ISSUE TITLE
三星note10 安卓10 QQ无网络

### ISSUE THREAD

**Issue by zero-rp** [android-hacker/VAExposed#803]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
qq没有网络

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：安卓10
ROM版本：正式版本
Xposed 插件以及插件版本：无
VirtualXposed版本：0.18.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by photoshopjava** [comment]
应该是QQ用了第三方网络框架，不能hook,写了一个demo用第三方网络框架在Android10上有问题，用用原声的网络请求可以。

**Comment by umi0216** [comment]
@photoshopjava 具体怎么做，可以请教一下吗

**Comment by tiann** [comment]
Fixed https://github.com/android-hacker/VirtualXposed/commit/effcb5e3cc55068ad4af2545efe42ff6c0e83cf5
