### ISSUE TITLE
支持安装split apk

### ISSUE THREAD

**Issue by andywu91** [android-hacker/VAExposed#807]
## 场景描述

我这边需要针对split apk也就是应用由多个apk（一个base apk及配置相关的多个apk）组成，实现安装在虚拟化环境中

## 希望的解决方案

希望提供api实现

## 其他信息

VirtualCore.get().installPackage只是针对单个apk安装，而通过 VPackageManager.get().getPackageInstaller()得到IPackageInstaller,open session,提示java.lang.SecurityException: Caller has no access to session

**Comment by liangxiwei** [comment]
这个是googleplay的功能吧，由googleplay加上android framework的支持实现的。google service在系统上有root权限，所以无障碍调用

**Comment by andywu91** [comment]
并不是，我在真实的android系统中，调用PackageInstaller的api，开启session进行安装，可以安装成功，并不依赖google play,具体我是参考：https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java，其中的代码。
然后我在项目中使用VPackageManager.get().getPackageInstaller()，得到IPackageInstaller,在openSesssoin时，提示java.lang.SecurityException: Caller has no access to session

**Comment by andywu91** [comment]
> 这个是googleplay的功能吧，由googleplay加上android framework的支持实现的。google service在系统上有root权限，所以无障碍调用

并不是，我在真实的android系统中，调用PackageInstaller的api，开启session进行安装，可以安装成功，并不依赖google play,具体我是参考：https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java，其中的代码。
然后我在项目中使用VPackageManager.get().getPackageInstaller()，得到IPackageInstaller,在openSesssoin时，提示java.lang.SecurityException: Caller has no access to session

**Comment by liangxiwei** [comment]
> > 这个是googleplay的功能吧，由googleplay加上android framework的支持实现的。google service在系统上有root权限，所以无障碍调用
> 
> 并不是，我在真实的android系统中，调用PackageInstaller的api，开启session进行安装，可以安装成功，并不依赖google play,具体我是参考：[https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java，其中的代码。](https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E3%80%82)
> 然后我在项目中使用VPackageManager.get().getPackageInstaller()，得到IPackageInstaller,在openSesssoin时，提示java.lang.SecurityException: Caller has no access to session

你调用这个api的时候也需要系统权限吧，就是说一般的三方app是没这个权限的。。

**Comment by andywu91** [comment]
> > > 这个是googleplay的功能吧，由googleplay加上android framework的支持实现的。google service在系统上有root权限，所以无障碍调用
> > 
> > 
> > 并不是，我在真实的android系统中，调用PackageInstaller的api，开启session进行安装，可以安装成功，并不依赖google play,具体我是参考：[https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java，其中的代码。](https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/content/InstallApkSessionApi.java%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E3%80%82)
> > 然后我在项目中使用VPackageManager.get().getPackageInstaller()，得到IPackageInstaller,在openSesssoin时，提示java.lang.SecurityException: Caller has no access to session
> 
> 你调用这个api的时候也需要系统权限吧，就是说一般的三方app是没这个权限的。。

并不需要系统权限，因为我们是第三方应用，而在华为，小米（关闭miui优化），oppo，三星的手机系统上，调用PackageInstaller的api，都执行成功了，并且这些测试手机系统上，并未安装google play及google play service

**Comment by gewyvoso** [comment]
maybe this can help [https://github.com/Aefyr/SAI](https://github.com/Aefyr/SAI)

**Comment by andywu91** [comment]
> maybe this can help https://github.com/Aefyr/SAI

In the end, we decided not to achieve this.
thanks!
