### ISSUE TITLE
vxp不支持64位so

### ISSUE THREAD

**Issue by ChenFeya** [android-hacker/VAExposed#815]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

在mate30 vxp中安装华为应用商店的微信，打开微信，微信闪退

## 复现步骤

1. 在mate30 从应用商店下载安装微信最新版本7.0.12
2.vxp中克隆微信app安装到vxp内，打开微信，必现闪退

## 环境

机型：
系统版本：
ROM版本：mate30
Xposed 插件以及插件版本：181
VirtualXposed版本：

## 补充

mate30应用商店中下载安装的微信apk中的lib是64位（arm64-v8a），但是vxp获取的runtime是32位也就是VMRuntime.is64Bit.call(VMRuntime.getRuntime.call())为false，导致微信中lib的so没有copy过去，所以打开微信，必现闪退。如果将64位的so全部copy到vxp的微信lib下面，运行微信提示不支持64位，去官网下载32位。

从微信官网下载32位的微信安装到vxp中，微信正常使用，猜测是vxp运行环境是不支持64位，导致copy64的so也不兼容。

能否考虑让vxp支持64位。

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by jiachengliu** [comment]
同问，我也遇到这个问题了，小米3 plus和小米5plus，打不开微信。

**Comment by jiachengliu** [comment]
请问，32位的微信，你哪里找的。https://weixin.qq.com/cgi-bin/readtemplate?t=page/faq/android/7012/index&faq=android_7012   官网没有找到32位的，

**Comment by ChenFeya** [comment]
> 请问，32位的微信，你哪里找的。https://weixin.qq.com/cgi-bin/readtemplate?t=page/faq/android/7012/index&faq=android_7012 官网没有找到32位的，

官网默认下载就是32位的，只有点击下载64位的才是支持64的。

**Comment by jiachengliu** [comment]
> > 请问，32位的微信，你哪里找的。https://weixin.qq.com/cgi-bin/readtemplate?t=page/faq/android/7012/index&faq=android_7012 官网没有找到32位的，
> 
> 官网默认下载就是32位的，只有点击下载64位的才是支持64的。

我发现有的手机，安装微信以后，看不了微信里面的腾讯新闻。微信直接黑屏闪退。可能是x5内核没有处理好。

**Comment by tuomao** [comment]
遇到了类似的问题

**Comment by Ayu8806** [comment]
微信点击登录，不能进入滑块验证界面，就直接返回输入密码界面了。

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/d65b4df0a680bb1f16e20ffbb7b80987b89cd1d7
