### ISSUE TITLE
Improvement to Google services support

### ISSUE THREAD

**Issue by LolHacksRule** [android-hacker/VAExposed#817]
**Is your feature request related to a problem? Please describe.**

I want Yalp Store in the Google Services installation replaced because it is deprecated according to its GitHub and signing in and out of both a Yalp Store account or a non-2FA'ed Google account doesn't work, says malformed request.

**Describe the solution you'd like**

Replace Yalp Store with the given store below

**Describe alternatives you've considered**

http://auroraoss.com/ (Aurora Store)

**Additional context**

Thanks so much, love this VSpace.

**Comment by jwmh** [comment]
Bump.  Cannot get Aurora Store working
Issue:
0. Install Aurora Stora inside VE,  via APK.
1.  Launch it.
2. Accept the changelog, and/or play w Settings, or just go ahead...
3. Click "Anonymous"  for login type.
4. It will start to spin...
... then freezes.
.
Stuck app (Aurora Store).
Repeats.
.
Test:
Same app in main phone OS (stock rom,  NOT rooted).
Works fine.
