### ISSUE TITLE
virtualxposed no internet access in installed applications

### ISSUE THREAD

**Issue by s3l1t3z** [android-hacker/VAExposed#819]
**Describe the bug**
No internet connection in installed applications

**To Reproduce**
- install any applications which using internet
- applications not connected to internet
**Expected behavior**
 - get working internet in installed applications

**Screenshots**
 - none

**Desktop**
- none

**Smartphone** 
 - Device: [xiaomi redmi note 8 pro]
 - OS: [android 10 miui 11]
 - Browser [stock browser]

**Additional context**
phone not rooted
virtualxposed version 18.2 gg

**Comment by tiann** [comment]
Fixed https://github.com/android-hacker/VirtualXposed/commit/effcb5e3cc55068ad4af2545efe42ff6c0e83cf5
