### ISSUE TITLE
VX不能正常运行武动乾坤手游！

### ISSUE THREAD

**Issue by tghrh1977** [android-hacker/VAExposed#821]
问题描述

VX不能正常运行武动乾坤手游，表现为屏幕分为左右两部分，无法正常点击运行游戏。游戏下载：九游或阿里游戏。

复现步骤

VX不能正常运行武动乾坤手游，表现为屏幕分为左右两部分，无法正常点击运行游戏。

环境

机型：realme x2 pro
系统版本：安卓10
ROM版本：realme UI RMX1931_11_C.21
Xposed 插件以及插件版本：无
VirtualXposed版本：0.18.2

补充

虚拟大师可正常运行武动乾坤手游。
应用隐藏大师之前不能正常运行武动乾坤手游，表现和VX一样，经反馈后，最新版已可正常运行武动乾坤手游阿里版，但仍不能正常运行武动乾坤手游九游版。

**Comment by revolutionxuanbei** [comment]
描述一个陈述句后面还要加个感叹号…
