### ISSUE TITLE
YouTube打不开

### ISSUE THREAD

**Issue by fjx2019** [android-hacker/VAExposed#825]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

打开YouTube失败（请尽量详细地描述你遇到的问题）

## 复现步骤

 设置，高级设置，安装谷歌服务，安装成功。xp模块启用。克隆主系统youtube成功，打开失败。通过Aurora Store下载安装成功，打开失败。重新下载vxp还是不行。
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：OPPO Reno z
系统版本：安卓9
ROM版本：PCDM10_11_A.25
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2
![Screenshot_2020-03-29-12-00-38-21](https://user-images.githubusercontent.com/53590628/77840255-df728680-71b7-11ea-8044-c273f6828d73.png)

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by Ayu8806** [comment]
我碰到这类情况的一般都是，在任务管理 里边发任务清空，然后杀掉vxp的进程，重新打开vxp，或者清空vxp的缓存。。。
