### ISSUE TITLE
VirtualXposed出现没有网络的情况

### ISSUE THREAD

**Issue by Ayu8806** [android-hacker/VAExposed#826]
## 问题描述
1.打开微信，长时间息屏不管，再次打开会出现没网络的情况。一般几率
2.在使用中，经常出现微信发送消息延迟，和接收消息延迟，看了一下都是没有网络的情况。
3.总结问题： VirtualXposed里会出现没有网络的情况。出现率很高。

## 复现步骤

几分钟~几十分钟内，会自己回复正常

## 环境

机型：OPPO R11
系统版本： V5.2.1
ROM版本：Android 8.1.0
Xposed 插件以及插件版本：自己写的hook插件，就是读取insert数据库。
VirtualXposed版本：0.18.0

## 补充
没有网络的情况，真机内的环境里是有网络的。

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by jiachengliu** [comment]
请问，解决了吗

**Comment by tiann** [comment]
Fixed https://github.com/android-hacker/VirtualXposed/commit/effcb5e3cc55068ad4af2545efe42ff6c0e83cf5
