### ISSUE TITLE
平安金管家无法获取步数

### ISSUE THREAD

**Issue by 15871722713** [android-hacker/VAExposed#829]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

平安金管家无法获取步数

## 复现步骤

打开virtualxposed， 再打开平安金管家，点击平安RUN，弹出‘获取运动步数失败’提示。

## 环境

机型：华为荣耀v20（PCT-AL10）
系统版本：安卓10
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2

## 补充
![image](https://user-images.githubusercontent.com/31395543/78522528-4cad9980-7800-11ea-80a3-75a7055b62b4.png)

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
被检测到了
