### ISSUE TITLE
virtual xposed0.18.2版本安装LINE9.10.2版本，手机型号红米5plus，进入line聊天页面会黑屏+闪退

### ISSUE THREAD

**Issue by wenjing-meng** [android-hacker/VAExposed#831]
## 问题描述

安装LINE9.10.2版本，进入line聊天页面会黑屏+闪退

## 复现步骤

安装virtual xposed，在virtual xpoesd内安装LINE，登录，选择“聊天”，选择一个好友，进入聊天页面，此时进不去聊天页面，并且黑屏

## 环境

机型：红米5plus、魅蓝note5
系统版本：MIUI10.1稳定版、Flyme6.3.0.2Q
ROM版本：
Xposed 插件以及插件版本：
VirtualXposed版本：virtual xposed0.18.2

## 补充

目前试了五种机型，其中三种都是黑屏，还有两种可以进入聊天

**Comment by sunriseXu** [comment]
这个问题是vxp对安卓10的某些api没有支持，可以从logcat崩溃日志看出来，你可以自己修改vxp
