### ISSUE TITLE
能否使用vx对内部应用隐藏root

### ISSUE THREAD

**Issue by 2767321434** [android-hacker/VAExposed#833]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

目前能隐藏root的只有面具，可实在不想刷，看到该应用可以存储重定向，便研究源码想重定向su文件所在位置，可多次修改也无效，感觉还是能力不行，求助大佬帮忙给个思路

## 希望的解决方案

magisk查看源码是利用了namespace去umount了sbin的挂载，vx可以完全代理内部应用的方法调用，理论上是可以欺骗内部应用这个路径的真实情况

## 其他信息

希望能给个思路，代码中哪里可以利用

**Comment by QGB** [comment]
magisk

**Comment by tiann** [comment]
vxp 本身就是免 root 的。另外，vx 的隐藏通过拦截系统调用实现，因此很容易被发现，没有意义。
