### ISSUE TITLE
拼多多APP启动crash

### ISSUE THREAD

**Issue by sunshinex** [android-hacker/VAExposed#835]
**问题描述**

拼多多APP启动crash，APP版本：5.8.0

**复现步骤**

必现

**环境**

机型：
系统版本：Android 9
ROM版本：MIUI 11.0.5
Xposed 插件以及插件版本：无
VirtualXposed版本：0.18.2

**补充**
04-10 10:23:16.251 31180 31234 W System.err: java.lang.SecurityException: Permission Denial: opening provider com.xunmeng.pinduoduo.oksharedprefs.OkSharedPrefContentProvider from ProcessRecord{160da8d 31180:io.va.exposed:p0/u0a191} (pid=31180, uid=10191) that is not exported from UID 10157
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Parcel.createException(Parcel.java:1953)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Parcel.readException(Parcel.java:1921)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Parcel.readException(Parcel.java:1871)
04-10 10:23:16.251 31180 31234 W System.err:    at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:849)
04-10 10:23:16.251 31180 31234 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-10 10:23:16.251 31180 31234 W System.err:    at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
04-10 10:23:16.251 31180 31234 W System.err:    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
04-10 10:23:16.251 31180 31234 W System.err:    at $Proxy23.registerContentObserver(Unknown Source)
04-10 10:23:16.251 31180 31234 W System.err:    at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1988)
04-10 10:23:16.251 31180 31234 W System.err:    at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1977)
04-10 10:23:16.251 31180 31234 W System.err:    at com.xunmeng.pinduoduo.oksharedprefs.c$1.run(SharedPreferencesImpl.java:54)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.Looper.loop(Looper.java:201)
04-10 10:23:16.251 31180 31234 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)
04-10 10:23:16.252 31180 31234 W System.err: Caused by: android.os.RemoteException: Remote stack trace:
04-10 10:23:16.252 31180 31234 W System.err:    at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
04-10 10:23:16.252 31180 31234 W System.err:    at android.content.IContentService$Stub.onTransact(IContentService.java:76)
04-10 10:23:16.252 31180 31234 W System.err:    at com.android.server.content.ContentService.onTransact(ContentService.java:262)
04-10 10:23:16.252 31180 31234 W System.err:    at android.os.Binder.execTransact(Binder.java:735)

**Comment by xiangyingchang** [comment]
遇到同样的问题，求解答。

**Comment by RainyJiang22** [comment]
I have the same problem , my machine is readmeK30, the android version is android 10 , the Rom version is MIUI12.0.1
so how can I solve this problem

**Comment by Lucas-Yang** [comment]
同样的问题，哔哩哔哩

**Comment by sunshinex** [comment]
放弃吧，作者根本就不看我们反馈的issue，我关闭了~
