### ISSUE TITLE
打开ZArchiver闪退

### ISSUE THREAD

**Issue by CaoHaoFeng** [android-hacker/VAExposed#845]
## 问题描述
打开ZArchiver闪退 
## 复现步骤
只要打开ZArchiver就闪退
## 环境
机型：魅族16spro
系统版本：安卓9
ROM版本：flyme 7.3.4.2a 出厂版
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2

## 补充
原因是ZArchiver 调用了ShortcutManager的removeAllDynamicShortcuts方法
而代理ShortcutManager的ShortcutServiceStub类中没有添加 removeAllDynamicShortcuts方法

在ShortcutServiceStub类的onBindMethods方法中添加 addMethodProxy(new ReplacePkgAndShortcutMethodProxy("removeAllDynamicShortcuts"));
我用Xposed插件Hook后可以修复
![Uploading S00503-00363470.jpg…]()

**Comment by tiann** [comment]
你可以提个 PR

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/c91eaf7c73b41a76c732923192dc8857ff441918
