### ISSUE TITLE
自己的APP里加载so动态库，桌面系统安装可运行，在xposed里面会提示无法找到so

### ISSUE THREAD

**Issue by bbajie** [android-hacker/VAExposed#846]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

我自己的app调用jni动态库，在手机桌面安装可以正常，但是到了xposed里面就提示无法找到动态库so文件

已编译的cpu类型：
arm64-v8a
armeabi-v7a
x86
x86_64

## 复现步骤

java里面调用方法  		System.loadLibrary("*****");

这个问题真机上必现，我试了好几个非自己项目，在电脑的模拟器，x86的动态库可以加载，手机的不行。

## 环境

机型：华为荣耀10
系统版本：8.0.0
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：0.18.2
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
64位的？

**Comment by bbajie** [comment]
嗯嗯，应该是的。手机外面加载的是arm64那个编译so

**Comment by bbajie** [comment]
后面我用别的项目测试： [https://github.com/pgyszhh/CPUTypeHelper.git](https://github.com/pgyszhh/CPUTypeHelper.git)

**Comment by tiann** [comment]
你需要编译 32 位的so，vxp 现在不支持 64位的。

**Comment by tiann** [comment]
#815
