### ISSUE TITLE
小米8，QQ在框架内无网络，微信无法进入

### ISSUE THREAD

**Issue by leewaro** [android-hacker/VAExposed#847]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tiann** [comment]
用源码编译最新的代码试试

**Comment by leewaro** [comment]
> 用源码编译最新的代码试试

本人小白，不知道操作，好难受

**Comment by anylys** [comment]
qq无法登录，提示无网络,华为p40

**Comment by tiann** [comment]
fixed https://github.com/android-hacker/VirtualXposed/commit/effcb5e3cc55068ad4af2545efe42ff6c0e83cf5
