### ISSUE TITLE
0.18.2 打不开微信

### ISSUE THREAD

**Issue by minggangLu** [android-hacker/VAExposed#852]
## 问题描述
下载完virtualxposed 0.18.2 版本后克隆微信7.0.14 版本打不开

## 复现步骤
提示打开应用失败，必现

## 环境

机型：荣耀v30pro
系统版本：android 10
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：  3.1.5
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by Mike-Ty** [comment]
我也是呀，这怎么办，太极不好使呀

**Comment by Huangshuboo** [comment]
华为p30也是一样

**Comment by tiann** [comment]
#815
