### ISSUE TITLE
安卓10，微信启动失败（0.18.2 + 微信7.0.13)

### ISSUE THREAD

**Issue by LoveCppp** [android-hacker/VAExposed#853]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
  在 VXP 中无法打开微信，提示打开应用 com.tencent.mm 失败:(
  百度贴吧也一样

## 复现步骤

**直接安装VirtualXposed 0.18.2版本 没有装任何模块 添加应用-微信 -打开-打开失败**

## 环境

机型：三星S9
系统版本：安卓10
ROM版本：稳定版本
Xposed 插件以及插件版本：无插件
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by LoveCppp** [comment]
log-
-------- beginning of main
--------- beginning of system
05-08 15:37:13.402 I/VClientImpl(27205): Binding application com.tencent.mm, (com.tencent.mm)
05-08 15:37:13.443 I/VClientImpl(27205): Xposed is enabled.
05-08 15:37:15.159 I/ExposedBridge(27205): com.tencent.mm is not a Xposed module, do not init epic.force
05-08 15:37:15.161 I/Runtime (27205): is64Bit: false, isArt: true
05-08 15:37:15.161 I/EpicNative(27205): use unsafe ? false
05-08 15:37:15.165 D/ExposedBridge(27205): xposed installer's modules not exist, ignore.
05-08 15:37:15.165 I/ExposedBridge(27205): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:37:15.166 D/ExposedBridge(27205): xposed installer's modules not exist, ignore.
05-08 15:37:15.166 I/ExposedBridge(27205): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:37:15.166 D/ExposedBridge(27205): xposed installer's modules not exist, ignore.
05-08 15:37:15.166 I/ExposedBridge(27205): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
--------- beginning of crash
05-08 15:37:28.854 I/VClientImpl(27427): Binding application com.wm.dmall, (com.wm.dmall)
05-08 15:37:28.869 I/VClientImpl(27427): Xposed is enabled.
05-08 15:37:29.526 I/ExposedBridge(27427): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:37:29.526 D/ExposedBridge(27427): xposed installer's modules not exist, ignore.
05-08 15:37:29.526 I/ExposedBridge(27427): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:37:29.527 D/ExposedBridge(27427): xposed installer's modules not exist, ignore.
05-08 15:37:29.527 I/ExposedBridge(27427): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:37:29.527 D/ExposedBridge(27427): xposed installer's modules not exist, ignore.
05-08 15:37:29.527 I/ExposedBridge(27427): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:38:34.969 I/VClientImpl(29480): Binding application com.wm.dmall, (com.wm.dmall:pushservice)
05-08 15:38:34.990 I/VClientImpl(29480): Xposed is enabled.
05-08 15:38:35.222 I/VClientImpl(29523): Binding application com.tencent.mm, (com.tencent.mm)
05-08 15:38:35.258 I/VClientImpl(29523): Xposed is enabled.
05-08 15:38:35.418 I/VClientImpl(29561): Binding application com.wm.dmall, (com.wm.dmall:core)
05-08 15:38:35.444 I/VClientImpl(29561): Xposed is enabled.
05-08 15:38:35.877 I/ExposedBridge(29480): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:38:35.880 D/ExposedBridge(29480): xposed installer's modules not exist, ignore.
05-08 15:38:35.880 I/ExposedBridge(29480): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:38:35.881 D/ExposedBridge(29480): xposed installer's modules not exist, ignore.
05-08 15:38:35.881 I/ExposedBridge(29480): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:38:35.881 D/ExposedBridge(29480): xposed installer's modules not exist, ignore.
05-08 15:38:35.881 I/ExposedBridge(29480): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:38:36.239 I/ExposedBridge(29561): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:38:36.240 D/ExposedBridge(29561): xposed installer's modules not exist, ignore.
05-08 15:38:36.240 I/ExposedBridge(29561): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:38:36.241 D/ExposedBridge(29561): xposed installer's modules not exist, ignore.
05-08 15:38:36.241 I/ExposedBridge(29561): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:38:36.241 D/ExposedBridge(29561): xposed installer's modules not exist, ignore.
05-08 15:38:36.241 I/ExposedBridge(29561): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:38:38.700 I/ExposedBridge(29523): com.tencent.mm is not a Xposed module, do not init epic.force
05-08 15:38:38.708 I/Runtime (29523): is64Bit: false, isArt: true
05-08 15:38:38.710 I/EpicNative(29523): use unsafe ? false
05-08 15:38:38.719 D/ExposedBridge(29523): xposed installer's modules not exist, ignore.
05-08 15:38:38.719 I/ExposedBridge(29523): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:38:38.724 D/ExposedBridge(29523): xposed installer's modules not exist, ignore.
05-08 15:38:38.724 I/ExposedBridge(29523): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:38:38.725 D/ExposedBridge(29523): xposed installer's modules not exist, ignore.
05-08 15:38:38.725 I/ExposedBridge(29523): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:39:01.086 I/VClientImpl(30360): Binding application com.tencent.mm, (com.tencent.mm:push)
05-08 15:39:01.126 I/VClientImpl(30360): Xposed is enabled.
05-08 15:39:04.891 I/ExposedBridge(30360): com.tencent.mm is not a Xposed module, do not init epic.force
05-08 15:39:04.894 I/Xposed  (30360): ignore process for wechat push.
05-08 15:39:04.895 I/Xposed  (30360): ignore process for wechat push.
05-08 15:39:16.827 I/VClientImpl(30642): Binding application com.wm.dmall, (com.wm.dmall:core)
05-08 15:39:16.863 I/VClientImpl(30642): Xposed is enabled.
05-08 15:39:17.896 I/ExposedBridge(30642): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:39:17.898 D/ExposedBridge(30642): xposed installer's modules not exist, ignore.
05-08 15:39:17.898 I/ExposedBridge(30642): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:39:17.899 D/ExposedBridge(30642): xposed installer's modules not exist, ignore.
05-08 15:39:17.899 I/ExposedBridge(30642): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:39:17.900 D/ExposedBridge(30642): xposed installer's modules not exist, ignore.
05-08 15:39:17.900 I/ExposedBridge(30642): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:39:18.808 I/VClientImpl(30771): Binding application com.wm.dmall, (com.wm.dmall:pushservice)
05-08 15:39:18.864 I/VClientImpl(30771): Xposed is enabled.
05-08 15:39:19.098 I/VClientImpl(30836): Binding application com.wm.dmall, (com.wm.dmall:filedownloader)
05-08 15:39:19.128 I/VClientImpl(30836): Xposed is enabled.
05-08 15:39:19.539 I/ExposedBridge(30771): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:39:19.540 D/ExposedBridge(30771): xposed installer's modules not exist, ignore.
05-08 15:39:19.540 I/ExposedBridge(30771): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:39:19.541 D/ExposedBridge(30771): xposed installer's modules not exist, ignore.
05-08 15:39:19.541 I/ExposedBridge(30771): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:39:19.542 D/ExposedBridge(30771): xposed installer's modules not exist, ignore.
05-08 15:39:19.542 I/ExposedBridge(30771): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:39:19.816 I/ExposedBridge(30836): com.wm.dmall is not a Xposed module, do not init epic.force
05-08 15:39:19.816 D/ExposedBridge(30836): xposed installer's modules not exist, ignore.
05-08 15:39:19.817 I/ExposedBridge(30836): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:39:19.817 D/ExposedBridge(30836): xposed installer's modules not exist, ignore.
05-08 15:39:19.817 I/ExposedBridge(30836): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:39:19.817 D/ExposedBridge(30836): xposed installer's modules not exist, ignore.
05-08 15:39:19.817 I/ExposedBridge(30836): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore
05-08 15:39:24.787 I/VClientImpl(31099): Binding application de.robv.android.xposed.installer, (de.robv.android.xposed.installer)
05-08 15:39:24.804 I/VClientImpl(31099): Xposed is enabled.
05-08 15:39:24.877 I/ExposedBridge(31099): de.robv.android.xposed.installer is not a Xposed module, do not init epic.force
05-08 15:39:24.892 I/Runtime (31099): is64Bit: false, isArt: true
05-08 15:39:24.892 I/EpicNative(31099): use unsafe ? false
05-08 15:39:24.893 I/XposedInstaller(31099): null getActivityXposedVersion called.
05-08 15:39:32.145 I/VClientImpl(31299): Binding application com.tencent.mm, (com.tencent.mm)
05-08 15:39:32.174 I/VClientImpl(31299): Xposed is enabled.
05-08 15:39:33.849 I/ExposedBridge(31299): com.tencent.mm is not a Xposed module, do not init epic.force
05-08 15:39:33.851 I/Runtime (31299): is64Bit: false, isArt: true
05-08 15:39:33.852 I/EpicNative(31299): use unsafe ? false
05-08 15:39:33.855 D/ExposedBridge(31299): xposed installer's modules not exist, ignore.
05-08 15:39:33.855 I/ExposedBridge(31299): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
05-08 15:39:33.855 D/ExposedBridge(31299): xposed installer's modules not exist, ignore.
05-08 15:39:33.855 I/ExposedBridge(31299): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
05-08 15:39:33.855 D/ExposedBridge(31299): xposed installer's modules not exist, ignore.
05-08 15:39:33.855 I/ExposedBridge(31299): module:/data/user/0/io.va.exposed/virtual/data/app/com.wm.dmall/base.apk is disabled, ignore

**Comment by tcc0lin** [comment]
老哥解决了吗，刚升10的时候就发现这个问题了

**Comment by Mike-Ty** [comment]
我也是

**Comment by LoveCppp** [comment]
没有解决

**Comment by Mike-Ty** [comment]
老哥，那这个咋办

**Comment by LoveCppp** [comment]
放弃了 换个测试机

**Comment by zy990081568** [comment]
ActivityManagerStub.onBindMethods加上这个
addMethodProxy(new ReplaceCallingPkgMethodProxy("getIntentSenderWithSourceToken"));

**Comment by ChenFeya** [comment]
到官网下载一个32位的微信试试

**Comment by Ayu8806** [comment]
> 到官网下载一个32位的微信试试

一般都是下载的32位的吧？ 我这边问题比较严重的是 能输入密码，在滑块验证界面卡了一下就闪退。需要重新登录

**Comment by mocobk** [comment]
遇到了同样的问题

**Comment by Looper-01** [comment]
机型：华为P30
系统版本：安卓10
ROM版本：稳定版本
Xposed 插件以及插件版本：无插件
VirtualXposed版本：0.18.2

一样无法打开微信，错误消息”打开应用 com.tencent.mm 失败:(“

**Comment by tiann** [comment]
#815

**Comment by rinranx** [comment]
我也是
