### ISSUE TITLE
想问下大家,在VXP中hook使用VX有封号风险么?

### ISSUE THREAD

**Issue by Young-Joe** [android-hacker/VAExposed#857]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

想hook下vx做一些自动检测(聊天记录等..),但不知道风险概率如何.有经验的大佬可否分享下.
      感谢!

**Comment by liangxiwei** [comment]
有,要养号

**Comment by Young-Joe** [comment]
> 有,要养号

养的号,进行hook操作风险小么?WX不是对hook操作封号率很高么?

**Comment by liangxiwei** [comment]
> > 有,要养号
> 
> 养的号,进行hook操作风险小么?WX不是对hook操作封号率很高么?

新号才容易封,养三个月再hook一般没啥问题,当然群发消息之类的也不能滥发.
