### ISSUE TITLE
无法打开tiktok

### ISSUE THREAD

**Issue by Daytimesleep** [android-hacker/VAExposed#859]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
在VirtualXposed中打开tiktok，设置完gender和interests后，在swipe up页面，无论是往下滑还是点击start watching都会退回到VirtualXposed页面

## 复现步骤
1.安装VirtualXposed 2.安装tiktok和应用变量 3.将tiktok和应用变量复制进VirtualXposed 
4.在应用变量设置tiktok，填写sim国际，sim名称，sim序号 5.保存应用变量配置，重启VirtualXposed 
6.打开tiktok 7.choose your gender页面 和 choose your interests页面设置完成
8.swipe up
![choose your gender](https://user-images.githubusercontent.com/51350381/83159716-e0cd1a80-a138-11ea-94a5-a477c2ce0a5a.jpg)
![choose your interests](https://user-images.githubusercontent.com/51350381/83159722-e3c80b00-a138-11ea-9ce3-686ee7eda74f.jpg)
![swipe up](https://user-images.githubusercontent.com/51350381/83159726-e4f93800-a138-11ea-84d6-052041d71aa1.jpg)
![最后闪退出的页面](https://user-images.githubusercontent.com/51350381/83159729-e591ce80-a138-11ea-8c07-823d16dfb250.jpg)

页面，往下滑和点击start watching都会退回到VirtualXposed页面，无法打开tiktok

## 环境

机型：小米8
系统版本：miui 11.0.7（安卓10）
ROM版本：稳定版
Xposed 插件以及插件版本：应用变量版本：3.3.2   Xposed Installer：3.1.5
VirtualXposed版本：0.18.2

## 补充
我觉得跟应用变量没有直接关系，尝试过卸载应用变量还是一样

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by revolutionxuanbei** [comment]
我也遇到了类似问题

**Comment by tiann** [comment]
#815
