### ISSUE TITLE
系统升级后 应用全部不见了

### ISSUE THREAD

**Issue by 994539** [android-hacker/VAExposed#861]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
更新MIUI11后，打开里面的应用都不见了，但是发现占用数据还是跟之前一样 怎么解决？或者能不能找到之前在里面安装的安装包提取出来

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

**Comment by tiann** [comment]
#744
