### ISSUE TITLE
重新编译最新代码（没有做任何修改），安装快手、抖音短视频直接闪退。

### ISSUE THREAD

**Issue by hugoxue1** [android-hacker/VAExposed#874]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
您好，我把0.18.2的代码拉下来重新的编译了一下，然后安装在我手机上，然后clone快手和抖音短视频发现两个都直接闪退，而使用您编译过的APK发现快手没有问题，但是抖音任然闪退。

## 复现步骤
我使用的IDE从3.0.1到4.x发现都会存在这样的问题，偶尔也有编译后可以打开快手的情况，但是很少，基本上大部分重新编译后均不能打开快手。
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：Android 10
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：3.1.5
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by zksyp** [comment]
请问解决了吗？我也遇到同样的问题。
