### ISSUE TITLE
Xposed框架91版已安装,但未激活,请检查日志的详细信息

### ISSUE THREAD

**Issue by jaryf** [android-hacker/VAExposed#877]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

打开这个软件之后安装了xposed installer,出现上述提示

## 复现步骤

网易木木模拟器,2.2.16版本

## 环境

网易木木模拟器,2.2.16版本
VirtualXposed_0.16.0

**Comment by jaryf** [comment]
日志信息
Cannot read log/data/data/de.robv.android.xposed.installer/log/error.log: open failed: ENOENT (No such file or directory)

**Comment by tiann** [comment]
不支持模拟器。

**Comment by studyflutter** [comment]
辣鸡的很，一个XPOSED框架 写的稀烂，各种不兼容

**Comment by tiann** [comment]
你行你上啊，我写好了为什么要免费给你用，你又不是我儿子。
