### ISSUE TITLE
能否和EdXposed 同时使用

### ISSUE THREAD

**Issue by niphor** [android-hacker/VAExposed#878]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

手机是 K20Pro MIUI12 稳定版装了 Magisk 和 EdXposed(SandHook)， 存储空间隔离

在ED里 给 VXP 设置 黑名单，用存储空间隔离 隔离了VXP

如果系统里安装了 Xposed 的插件
然后 ED里也装一样的插件

则 只会有一边的插件正常使用，要么ED里的正常，要么VXP的正常

尝试过 关闭VXP的 Xposed,卸载插件，在ED里去掉黑名单，也是一样

以 微X助手  为例 VXP里提示 和 io.va.virtualxposed 有冲突，然后就就自己禁用了
实际MIUI里的微X助手也变成禁用了，然后重启系统里的微信，助手正常加载，VXP里的也会加载但是提示 👆的冲突，如此反复
## 希望的解决方案

有没有 方法 VXP 和 ED 共存 两个的插件独立运行？

**Comment by tiann** [comment]
套娃是要干啥。。。

**Comment by niphor** [comment]
@tiann 
当 平行空间 用啊， 不然得买两三个手机 😂
用手机自带的分身功能，只能运行相同版本的，不能不同版本。
更不能不同版本用不同Xposed插件

其实是想把VXP当手机端的Docker用....

**Comment by tiann** [comment]
从原理上讲有可能，但是不现实。

很多模块会判断宿主的包名，比如微信相关的模块会判断当前进程是不是微信；当 ED 这样的框架在 VXP 内部加载模块的时候，宿主的包名实际上是 VXP 的包名，因此模块是被加载了，但是**它会觉得这不是它要运行的目标 App**从而不执行任何逻辑。

就拿你这个具体问题来说，更加与 VXP 没关系了；因为微X模块本身不允许这样运行。

**Comment by niphor** [comment]
> 从原理上讲有可能，但是不现实。
> 
> 很多模块会判断宿主的包名，比如微信相关的模块会判断当前进程是不是微信；当 ED 这样的框架在 VXP 内部加载模块的时候，宿主的包名实际上是 VXP 的包名，因此模块是被加载了，但是**它会觉得这不是它要运行的目标 App**从而不执行任何逻辑。
> 
> 就拿你这个具体问题来说，更加与 VXP 没关系了；因为微X模块本身不允许这样运行。

感谢大佬解答，那我就断了这个念想吧😭
