### ISSUE TITLE
下版本将不再支持 32 位应用程序 / 32bits apps is not supported in next version.

### ISSUE THREAD

**Issue by tiann** [android-hacker/VAExposed#879]
0.18.2 是最后一个支持 32 位应用的版本。

**Comment by tianyah** [comment]
好

**Comment by ghost** [comment]
不支持32位了QQ，微信，等国产毒瘤在不可root的安卓11上面怎么办啊

**Comment by tiann** [comment]
去play下 64位的。

**Comment by xiaoqiqiya** [comment]
> 去play下 64位的。

那个地方下载

**Comment by ghost** [comment]
> 去play下 64位的。

华为它没有办法安装play商店

**Comment by xz592** [comment]
华为只支持安装32位的版本的咋办啊

**Comment by isanwenyu** [comment]
@tiann  请问移除32位应用支持的主要原因是什么？

**Comment by tiann** [comment]
> @tiann 请问移除32位应用支持的主要原因是什么？

1. Google 已经在2019年9月强制所有新上架 Google Play 的应用提供 64 位版本，64取代32是趋势。
2. 没有精力同时维护32位和64位，在一个应用中同时支持 32 位和 64 位要付出额外的工作。

**Comment by kzmafia** [comment]
> 0.18.2是最后一个支持32位应用的版本。

Hello, I currently install the virtual xposed virtual.20.2 version, but it does not support the use of GameGuardian。
The version I used earlier is v0.19 that supports all software.  During this period of time, I upgraded my Samsung s10+ system from 10.0 to 11 and now it does not support virtual xposed.  Is there any way to solve it? Ask God for help

**Comment by Will-power-i** [comment]
``
Good

**Comment by dev-xiaosa** [comment]
> > 0.18.2是最后一个支持32位应用的版本。
> 
> Hello, I currently install the virtual xposed virtual.20.2 version, but it does not support the use of GameGuardian。
> The version I used earlier is v0.19 that supports all software. During this period of time, I upgraded my Samsung s10+ system from 10.0 to 11 and now it does not support virtual xposed. Is there any way to solve it? Ask God for help

I can help you

**Comment by ATPQ** [comment]
> 0.18.2 是最后一个支持 32 位应用的版本。

黑色Android 11
黑色国内32位

**Comment by henrykkg** [comment]
Hi I want to connect

**Comment by didiaodanding** [comment]
您好，您的邮件已收到，谢谢。                                    --------李峰
