### ISSUE TITLE
能否提供一个修复了QQ网络问题的18.2版本

### ISSUE THREAD

**Issue by np5cm1s** [android-hacker/VAExposed#886]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

新的19.0版本不支持32位应用 无法添加国内版QQ应用

而18.2版本安卓10使用QQ有无法连接网络的问题

两个版本都无法正常使用QQ

## 希望的解决方案

(你希望如何解决这个问题？)

所以能否提供一个支持32位QQ并修复了网络连接问题的版本

## 其他信息

(其他你认为有用的信息)

**Comment by ghost** [comment]
32位换SandVXposed就行

**Comment by Chastinian** [comment]
> 32位换SandVXposed就行

SandVXP不加载QNotified模块
