### ISSUE TITLE
希望支持安装xapk文件

### ISSUE THREAD

**Issue by sorosunrain** [android-hacker/VAExposed#896]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

一些app现在都是xapk形式提供的

## 希望的解决方案

希望支持xapk选择安装

## 其他信息

(其他你认为有用的信息)

**Comment by Chastinian** [comment]
请将附带的obb文件放在手机/sdcard/Android/obb/❴软件包名❵ 文件夹里
