### ISSUE TITLE
colorqq2模块无法打开主页面

### ISSUE THREAD

**Issue by raging-flames** [android-hacker/VAExposed#897]
## 问题描述

打开后一直显示打开中，并没有提示打开失败也不会卡顿

## 复现步骤

安装应用，打开

## 环境

机型：荣耀7A
系统版本：安卓8.0.0
ROM版本：稳定版
Xposed 插件以及插件版本：colorqq2，版本1.3.6
VirtualXposed版本：1.8.2

## 补充

colorqq2模块，1.1和1.2版本可以正常打开，1.3至1.3.6版本均无法打开

**Comment by ycyzjluhx** [comment]
good
