### ISSUE TITLE
Facebook无法打开

### ISSUE THREAD

**Issue by moster1h** [android-hacker/VAExposed#899]
## 问题描述

添加Facebook应用后，打不开facebook一直在加载中

## 复现步骤

添加Facebook应用并打开

## 环境

机型：
系统版本：Android10
ROM版本：miui12稳定版
Xposed 插件以及插件版本：3.1.5版本框架91
VirtualXposed版本：0.19.0

**Comment by B13-F** [comment]
添加Line应用后，也打不开
机型：华为mate20
系统：Android10.1.0.160
 VirtualXposed版本：0.19.2

**Comment by tiann** [comment]
fixed in https://github.com/android-hacker/VirtualXposed/commit/d3b1f0724a0abda2535551d2b358e1eefa093af1, https://github.com/android-hacker/VirtualXposed/commit/fe87e43b584cb897a53c35d5eed83bf80133ea7e
