### ISSUE TITLE
希望能够支持apks安装

### ISSUE THREAD

**Issue by Chastinian** [android-hacker/VAExposed#900]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

在VirtualXposed中，无法使用VirtualXposed里的应用来安装应用，只能通过VirtualXposed自带的apk安装器安装应用，但这样无法安装apks

## 希望的解决方案

在添加APP界面里支持添加apks

## 其他信息

使用的apks安装器：SAI，点击安装会闪退

**Comment by funsilver76** [comment]
Cannot create symbolic link /storage/emulated/0/Android/data/com.rarlab.rar/files/_rartemp_open_1597391008291/fake_pom_install.xml
• Permission denied

**Comment by Chastinian** [comment]
> Cannot create symbolic link /storage/emulated/0/Android/data/com.rarlab.rar/files/_rartemp_open_1597391008291/fake_pom_install.xml
> • Permission denied

Android系统规定，创建链接需Root权限，请确认您的手机是否获取了Root权限。

**Comment by tiann** [comment]
#896
