### ISSUE TITLE
Google账号无法登录

### ISSUE THREAD

**Issue by Chastinian** [android-hacker/VAExposed#903]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

在VirtualXposed中，无法登录Google账号。

## 复现步骤

在VirtualXposed里安装来自microG官网的最新版microG，再启用xposed模块，然后登录Google账号，填入账号密码后显示失败，若使用原版的GMS点击登录会直接闪退，Play商店打不开。
（本bug必现）

## 环境

机型：DUB-AL00
系统版本：Android 8.1.0
ROM版本：本机唯一的一个系统版本（稳定版）
Xposed 插件以及插件版本：Fake Gapps,2.0
VirtualXposed版本：0.18.2,0.19.0

## 补充

暂无

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
使用新版 microG
