### ISSUE TITLE
support web browser

### ISSUE THREAD

**Issue by WymanWMTan** [android-hacker/VAExposed#904]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

当我把游戏分身加进来VXP，继承游戏账号需要跳转到Web版Twitter授权。结果框架外的浏览器被打开，回调了框架外的游戏。游戏分身授权失败。
但是VXP没法选择并添加uc浏览器/chrom/qq浏览器/win Edge，不知这是bug还是限制。能不能支持随便一种浏览器，让这种app-web-app调转能在vxp框架内发生？

## 复现步骤

1，添加游戏分身one piece treasure cruise
2，利用SNS继承twitter账号
3，游戏打开浏览器
4，登录twitter并确认授权
5，浏览器打开vxp框架外游戏本体

## 环境

机型：魅族pro17
系统版本：Android10
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）8.1.2.2A稳定
Xposed 插件以及插件版本：
VirtualXposed版本：0.19.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by Chastinian** [comment]
试试via浏览器

**Comment by WymanWMTan** [comment]
感谢Chastinian，建议非常有用。简洁的浏览器，实现了VXP内跳转
