### ISSUE TITLE
VirtualXposed无法安装应用

### ISSUE THREAD

**Issue by ati46** [android-hacker/VAExposed#905]
## 问题描述
进入VirtualXposed0.19,在添加应用界面，无法选择QQ等App，克隆和内部文件安装都无法选中。
左上角选中图标永远是灰色的， 其他有一些应用是可以选中的。
qq8.2、钉钉5.0.6 不可以
微信7.0.15是可以选中的
## 环境

机型：红米Note4X
系统版本：安卓7.0
ROM版本：官方稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：0.19

**Comment by tiann** [comment]
不再支持 32 位应用。

**Comment by songzhiyong** [comment]
从哪个版本开始不支持的？

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/issues/879
