### ISSUE TITLE
能增加时区修改吗

### ISSUE THREAD

**Issue by Mortalit** [android-hacker/VAExposed#914]
## 场景描述

电信卡会强锁手机时区,现在有些软件会通过检测手机时区来锁区

## 希望的解决方案

能在这个虚拟机内增加设定特定时区的功能吗

## 其他信息

(其他你认为有用的信息)

**Comment by Chastinian** [comment]
VirtualXposed不是虚拟机，它没有独立的时间设置。请在手机设置里修改时区。
