### ISSUE TITLE
需要0.18.2共存版

### ISSUE THREAD

**Issue by qinlili23333** [android-hacker/VAExposed#918]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

0.19不支持32位而0.18不支持64位,但现在在同一台设备上同时有64位和32位需求
尝试用共存工具制作0.18.2的共存版但共存版会无法加载所有native lib文件

## 希望的解决方案

制作一个包名不同的0.18.2的共存版

## 其他信息

(其他你认为有用的信息)

**Comment by ghost** [comment]
Use SandVXposed instead

**Comment by tiann** [comment]
可以使用旧版本自行编译
