### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by jcespi2005** [android-hacker/VAExposed#932]
Describe the bug
Application not working on Android 11

To Reproduce
Just install the app and they to add an application, it hangs

Expected behavior
Should let add an application

Smartphone (please complete the following information):
OnePlus 8T Android 11

**Comment by ghost** [comment]
安卓11打开设置菜单会闪退，添加应用也会闪退

**Comment by bykenx** [comment]
+1, OnePlus 8T Android11

**Comment by silsuer** [comment]
+1, OnePlus 8T Android11

**Comment by theowenyoung** [comment]
Same problem here

**Comment by ghost** [comment]
Try this version: [https://github.com/lianglixin/SandVXposed](url)

**Comment by tiann** [comment]
try this: https://github.com/android-hacker/VirtualXposed/commit/4e13b95342088dd7f94ed9620170eaae4aa17df1

or use my build: 
[app-aosp-release.apk.zip](https://github.com/android-hacker/VirtualXposed/files/5581250/app-aosp-release.apk.zip)

**Comment by jcespi2005** [comment]
> Try this version: [https://github.com/lianglixin/SandVXposed](url)

Seems works, but I can't access external data application for cloned apps.
On Virtual Xposed apps uses same external storage, so your app have same data in case it saves on external storage...
So for now it's nos useful, but seems works fine executing apps cloned

**Comment by jcespi2005** [comment]
> try this: [4e13b95](https://github.com/android-hacker/VirtualXposed/commit/4e13b95342088dd7f94ed9620170eaae4aa17df1)
> 
> or use my build:
> [app-aosp-release.apk.zip](https://github.com/android-hacker/VirtualXposed/files/5581250/app-aosp-release.apk.zip)

Installs fine but can't enter main menu not clone any app...
Seems doesn't work

![Screenshot_20201123-094037](https://user-images.githubusercontent.com/12409352/99942502-0ea1bd80-2d70-11eb-8699-69d53350f6ff.jpg)

**Comment by ghost** [comment]
> > Try this version: [https://github.com/lianglixin/SandVXposed](url)
> 
> Seems works, but I can't access external data application for cloned apps.
> On Virtual Xposed apps uses same external storage, so your app have same data in case it saves on external storage...
> So for now it's nos useful, but seems works fine executing apps cloned

Android 11 and targetsdk 30+ force use virtual storage，so app inside can not access outside storage. Same as targetsdk29. Use SAF plugin for fix.

**Comment by jcespi2005** [comment]
> > > Try this version: [https://github.com/lianglixin/SandVXposed](url)
> > 
> > 
> > Seems works, but I can't access external data application for cloned apps.
> > On Virtual Xposed apps uses same external storage, so your app have same data in case it saves on external storage...
> > So for now it's nos useful, but seems works fine executing apps cloned
> 
> Android 11 and targetsdk 30+ force use virtual storage，so app inside can not access outside storage. Same as targetsdk29. Use SAF plugin for fix.

Can you point me to SAF plugin info or link?

Thanks in advance

**Comment by jcespi2005** [comment]
> try this: [4e13b95](https://github.com/android-hacker/VirtualXposed/commit/4e13b95342088dd7f94ed9620170eaae4aa17df1)
> 
> or use my build:
> [app-aosp-release.apk.zip](https://github.com/android-hacker/VirtualXposed/files/5581250/app-aosp-release.apk.zip)

Finally getting working, and getting working GameGaurd 10.0, but RealRacing last version cloned fails to execute

**Comment by RubinTry** [comment]
0.20.0可以在Android 11上运行，但是必须要64位的app

**Comment by RubinTry** [comment]
最新版里已经修复，目前主页里暂未发布apk，有需要的可以自行clone此项目编译一个
