### ISSUE TITLE
android 7 添加应用点不上

### ISSUE THREAD

**Issue by 950919** [android-hacker/VAExposed#934]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

小米mix 2 android 7.1.1添加应用到virtualXposed时，点不了某些app进行添加应用

## 复现步骤

1、在克隆app板块中，有些app点不了添加不上

## 环境

机型：小米mix2
系统版本：android 7.1.1
ROM版本：稳定版（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：JustTrustme 2
VirtualXposed版本：0.19.0

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不支持32位应用。
