### ISSUE TITLE
2 different build of app

### ISSUE THREAD

**Issue by Ananas-Kuchen** [android-hacker/VAExposed#940]
**Is your feature request related to a problem? Please describe.**

when you build virtualxposed for 64bit devices. This app also only supports apps with arm64-v8a compatibility only. and any app with armeabi-v7a compatibility cannot be installed.

**Describe the solution you'd like**

because you are making virtualxposed for 64bit compatibility. please make another virtualxposed with 32bit only. what I mean is to create 2 virtualxposed with 2 different compatibility but have the same functionality. like become "virtualxposed-32" and "virtualxposed-64" or what

**Describe alternatives you've considered**

Is it really difficult to make another application which is the same as armeabi-v7a compatibility? I can't edit / modify the app. and I still need to use the app in 32bit device

**Additional context**

I was so desperate to ask like a fool. but i can only ask only for the dev who can do something. no matter I failed to ask the request. I still hope you are kind enough to consider it before closing this ticket.

I know you are pinning a ticket stating if you no longer make app support to 32bit. but I'm also doing this useless request because I really want to be able to use the app. Good to see lots of developers creating games and apps only for 64bit in new tech devices is good but bad for me who only uses outdated devices and apps with old ABI. 

Now the app supports split apk, of course I can't use it. great.....

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/6e4e26a4c6e5954061013031de951b2faadf8ccf

**Comment by Ananas-Kuchen** [comment]
> [6e4e26a](https://github.com/android-hacker/VirtualXposed/commit/6e4e26a4c6e5954061013031de951b2faadf8ccf)

So basically you only change the name of the apk code only for 64bit support only ??? come on please consider making virtualxposed with 32bit support. PLEASE

I need virtualxposed with 32bit support and split apk. THIS APP IS BETTER THAN ANY OTHER APP I HAVE EVER TRIED!

Is it possible to build an apk from source code on Android dev?

Can you lead me to a tutorial that helped me get vx with 32bit support myself???

**Comment by Ananas-Kuchen** [comment]
> [6e4e26a](https://github.com/android-hacker/VirtualXposed/commit/6e4e26a4c6e5954061013031de951b2faadf8ccf)

So basically you only change the name of the apk code only for 64bit support only ??? come on please consider making virtualxposed with 32bit support. PLEASE

I need virtualxposed with 32bit support and split apk. THIS APP IS BETTER THAN ANY OTHER APP I HAVE EVER TRIED!

Is it possible to build an apk from source code on Android dev?

Can you lead me to a tutorial that helped me get virtualxposed with 32bit support myself???
I can't do it alone anyway, it's so sad

**Comment by tiann** [comment]
[How to compile](https://github.com/android-hacker/VirtualXposed/wiki/How-to-compile)

You can cherry-pick the commit of split apk in 0.18.2

**Comment by Ananas-Kuchen** [comment]
> [How to compile](https://github.com/android-hacker/VirtualXposed/wiki/How-to-compile)
> 
> You can cherry-pick the commit of split apk in 0.18.2

After seeing that page I didn't understand anything after reading it.

New apps with compatibility 5.0 and above mostly use the apk bundle. if I extract the base.apk only and install it then the app can't run because the lib doesn't participate in the install process. I can't think of any way or method to make split apk work in virtualxposed 0.18.2

Some apps with compatibility 4.4 universal / fat have started migrating to 5.0 and becoming apk bundles. I can't imagine if all the apps change and I don't know what to do with it later

**Comment by tiann** [comment]
reference this commit: https://github.com/android-hacker/VirtualXposed/commit/edfb987193299c696265e18c4338ec21ffd8a00d
