### ISSUE TITLE
Where Is Supersu?

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#957]
**Describe the bug**
Trying To Use Root App And There Is No Superuser Request If Not Added Take It As Request On Next Update

**To Reproduce**
1. Open VXP
2. Download And Instal Any App (That Required Root)
3. Open The Installed App
4. No Supersu Request  :-( 

**Expected behavior**
The Application Should Request Access To Supersu

**Screenshots**
No Screenshot Available

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Ungoogled Chromium 
 - Version: v85

**Smartphone (please complete the following information):**
 - Device: Realme 5i
 - OS: Android 10 (Q) Realme UI
 - Browser Ungoogled Chromium
 - Version v85
 
**Additional context**
Why We Can't Use Supersu?
If Not Available Please Add It 
We Want To Use VXP With Root Availabe :)

@Tiann

Best Regards
NST_Adventure

**Comment by ghost** [comment]
Author Note:
Welp I Confused
Should I Report This As Bug Or Suggestion?
@tiann

Best Regards
NST_Adventure

**Comment by tiann** [comment]
Please read the README and Wiki, VXP can not use root.
