### ISSUE TITLE
Luck Patcher Crash

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#958]
**Describe the bug**
When Trying To Launch LP They Opened For A While Then Crashed (Module Enabled)

**To Reproduce**
1. Download And Instal LP
2. Enable LP Module
3. Reboot VXP And Launch
4. LP Crash

**Expected behavior**
It shouldn't Crashed And Working Correctly

**Screenshots**
No Screenshot Available

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Ungoogled Chromium
 - Version v85
**Smartphone (please complete the following information):**
 - Device: Realme 5i
 - OS: Android Q
 - Browser Ungoogled Chromium
 - Version v85

**Additional context**
Problem Are Same For
-MinMin Guard
-Xprivacy
(Note: Will Edited For Future App Report Please Re Check This As Many As Possible @tiann )

**Comment by tiann** [comment]
Please read the README, Luck Packer is not supported.

**Comment by ghost** [comment]
@tiann where is english version of readme?
