### ISSUE TITLE
I can't open any apps in VirtualXposed

### ISSUE THREAD

**Issue by LasisIkaros** [android-hacker/VAExposed#962]
**Describe the bug**
I can install apps in  VirtualXposed but I can't open any apps especially like WeChat in VirtualXposed.
It's just display black background but it final said the app keep stoping. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: ASUS Rog phone 1
 - OS: android 9
 - Browser chrome
 - Version 87.0.4280.88 

**Additional context**

![135085240_759933161534418_6795530439519632189_n](https://user-images.githubusercontent.com/76839410/103438821-515d8c00-4c72-11eb-997e-c5fd941dfb2f.jpg)

![133550264_464060554601201_864267703714294610_n](https://user-images.githubusercontent.com/76839410/103438817-4c004180-4c72-11eb-8b04-e1ed91dc8993.jpg)

![134070791_306960140720267_8597796444089641824_n](https://user-images.githubusercontent.com/76839410/103438839-92ee3700-4c72-11eb-886c-2bccce3b0a03.jpg)

https://user-images.githubusercontent.com/76839410/103439088-02652600-4c75-11eb-95b6-6b4ec4435b0f.mp4

**Comment by LasisIkaros** [comment]
@

**Comment by smoothdvd** [comment]
@LasisIkaros same  here. Do you resolve this issue?
