### ISSUE TITLE
有交流群吗 我像加入开发学习

### ISSUE THREAD

**Issue by q760986433** [android-hacker/VAExposed#964]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述

(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by dev-xiaosa** [comment]
> **BUG反馈请不要用这个模版，否则直接关闭！！**
> 
> ## 场景描述
> (请详细和精确地表述你的使用场景)
> 
> ## 希望的解决方案
> (你希望如何解决这个问题？)
> 
> ## 其他信息
> (其他你认为有用的信息)

一起交流

**Comment by tiann** [comment]
https://t.me/vxp_devs
