### ISSUE TITLE
va++.so异常

### ISSUE THREAD

**Issue by Yononony** [android-hacker/VAExposed#966]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

本地用0.18.2 tag编译的release包在打开插件（安装在VX里面的apk）几秒钟之后崩溃退出。通过对比发现本地编译的va++.so库和https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.2 下给出的apk里面的so库差异很大，本地编译的so库只有600k，而tag/0.18.2下面带的apk里面的so有700k左右。

## 复现步骤

使用https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.2分支编译

## 环境

与机型无关。

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
贴崩溃 log，比较 so 大小对解决问题有帮助吗？用不同的 ndk 版本编译，大小会不一样啊吧。
