### ISSUE TITLE
make other virtualxposed with 32bit support

### ISSUE THREAD

**Issue by Ananas-Kuchen** [android-hacker/VAExposed#977]
**Is your feature request related to a problem? Please describe.**

Since the 64bit special update and with the split apk support update, 32bit support didn't get any updates. The new GooglePlay store can't also be used

**Describe the solution you'd like**

Please update virtualxposed 32bit support with split apk support + playstore and gms (original)

**Describe alternatives you've considered**

if playstore+gms support can't. just update this virtualxposed with 32bit support and split apk only!

**Additional context**

virtualxposed with 64bit support can't be used on my phone, and my phone only supports 32bit apps

I'm also not using virtualxposed with GG and using regular virtualxposed and regular usage so please consider making virtualxposed with 32bit support back!

please create virtualxposed with the package name "io.va.exposed32", with type LIB armeabi-v7a

**Comment by tiann** [comment]
32bit is abandoned.
