### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by kzmafia** [android-hacker/VAExposed#978]
02-07 14:21:09.775 I/VClientImpl( 8623): Binding application com.heliogames.westland, (com.heliogames.westland)
02-07 14:21:09.795 I/VClientImpl( 8623): Xposed is enabled.
02-07 14:21:09.908 I/ExposedBridge( 8623): com.heliogames.westland is not a Xposed module, do not init epic.force
02-07 14:21:09.908 D/ExposedBridge( 8623): xposed installer's modules not exist, ignore.
02-07 14:21:09.909 I/ExposedBridge( 8623): module:/data/user/0/io.va.exposed64/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
02-07 14:21:09.909 D/ExposedBridge( 8623): xposed installer's modules not exist, ignore.
02-07 14:21:09.909 I/ExposedBridge( 8623): module:/data/user/0/io.va.exposed64/virtual/data/app/com.heliogames.westland/base.apk is disabled, ignore
02-07 14:21:09.909 D/ExposedBridge( 8623): xposed installer's modules not exist, ignore.
02-07 14:21:09.909 I/ExposedBridge( 8623): module:/data/user/0/io.va.exposed64/virtual/data/app/com.gzjmwuw/base.apk is disabled, ignore

**Comment by tiann** [comment]
Please give me a link

**Comment by kzmafia** [comment]
02-07 15:28:27.483 I/VClientImpl(31783): Binding application com.heliogames.westland, (com.heliogames.westland)02-07 15:28:27.508 I/VClientImpl(31783): Xposed is enabled.02-07 15:28:27.631 I/ExposedBridge(31783): com.heliogames.westland is not a Xposed module, do not init epic.force02-07 15:28:27.633 D/ExposedBridge(31783): xposed installer's modules not exist, ignore.02-07 15:28:27.633 I/ExposedBridge(31783): module:/data/user/0/io.va.exposed64/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore02-07 15:28:27.633 D/ExposedBridge(31783): xposed installer's modules not exist, ignore.02-07 15:28:27.633 I/ExposedBridge(31783): module:/data/user/0/io.va.exposed64/virtual/data/app/com.heliogames.westland/base.apk is disabled, ignore02-07 15:28:27.633 D/ExposedBridge(31783): xposed installer's modules not exist, ignore.02-07 15:28:27.633 I/ExposedBridge(31783): module:/data/user/0/io.va.exposed64/virtual/data/app/com.gzjmwuw/base.apk is disabled, ignore发送自我的盖乐世发送自我的盖乐世

**Comment by kzmafia** [comment]
能否加个微信或者QQ说?
