### ISSUE TITLE
OPPO安卓11 SC防火墙模块无效

### ISSUE THREAD

**Issue by slvlio** [android-hacker/VAExposed#988]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

sc防火墙我主要用于修改sim卡，用来打开tiktok使用。
现在升级11系统后，sc防火墙和tiktok在virtualxposed内可以安装和打开，但sc防火墙设置地区后，tiktok打开是明显的封sim卡状态无法浏览视频。
于是特地装了个imei信息查看器，发现依然运营商是中国电信，应该是模块无效了。

## 复现步骤

之前是装的v0.20.2版本vxp跑着安卓10的，基本可以使用。然后我升级安卓11后，一开始也是可以正常用的！！
然后由于手贱及折腾心理，把装的好好的virtualxposed卸载重装了下，就开始不行了。
再后来安装v0.20.3的vxp，也是老样子了。
我怀疑是那sc防火墙插件，在安卓10的时候成功的修改了vxp中的sim卡信息，修改效果倒是能延续到安卓11，但却没法重新再修改了。。

## 环境

机型：oppo reno2 十倍变焦版
系统版本：ColorOS v11.1正式版
ROM版本：PCCM00_11_F.04
Xposed 插件以及插件版本：sc防火墙 v9.1.2
VirtualXposed版本：v0.20.3

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
模块问题，与框架无关。

**Comment by slvlio** [comment]
我又折腾了下，反馈下情况：
类似sc防火墙的
还有个 应用变量的模块（v3.3.2）。
我在另一个沙盒sandvxposed上安装该模块可以有效修改imei信息，tiktok也能开，只是那沙盒很久没更新，tiktok兼容差一直闪退。。
然后这个应用变量，在vxp里面是无效的，打开该模块，屏幕底部显示“xposed没有工作”

**Comment by slvlio** [comment]
sandvxp用的这个
https://wwi.lanzous.com/iYGBQls3a0h
