### ISSUE TITLE
VirtualXposed是否支持虚拟机

### ISSUE THREAD

**Issue by echos2019** [android-hacker/VAExposed#998]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

请问下VirtualXposed是否支持虚拟机，在android8.0 32位64位的都试了下无法安装Xposed，打开Xposed Installer即崩溃，重新安装xposedinstaller打开也会崩溃
## 复现步骤

在android studio自带虚拟机上安装VirtualXposed之后通过VirtualXposed打开Xposed installer即显示VirtualXposed has stopped

## 环境

机型：
系统版本：android8.0
ROM版本：google pixel 3xl
Xposed 插件以及插件版本：3.1.5
VirtualXposed版本：0.18.2 （32位） 0.20.3 （64位）

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
应该是不支持的

**Comment by echos2019** [comment]
感谢回答
